local _, internal = ...

internal.appendData({
	{
		id = 10940,
		name = "Strange Dust",
		icon = "Interface\\Icons\\INV_Enchant_DustStrange",
		categories = { 333 },
	},
	{
		id = 10938,
		name = "Lesser Magic Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceMagicSmall",
		categories = { 333 },
	},
	{
		id = 10939,
		name = "Greater Magic Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceMagicLarge",
		categories = { 333 },
	},
	{
		id = 10978,
		name = "Small Glimmering Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardGlimmeringSmall",
		categories = { 333 },
	},
	{
		id = 11084,
		name = "Large Glimmering Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardGlimmeringLarge",
		categories = { 333 },
	},
	{
		id = 11083,
		name = "Soul Dust",
		icon = "Interface\\Icons\\INV_Enchant_DustSoul",
		categories = { 333, 755 },
	},
	{
		id = 10998,
		name = "Lesser Astral Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceAstralSmall",
		categories = { 333 },
	},
	{
		id = 11082,
		name = "Greater Astral Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceAstralLarge",
		categories = { 333 },
	},
	{
		id = 11138,
		name = "Small Glowing Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardGlowingSmall",
		categories = { 333 },
	},
	{
		id = 11139,
		name = "Large Glowing Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardGlowingLarge",
		categories = { 333 },
	},
	{
		id = 11137,
		name = "Vision Dust",
		icon = "Interface\\Icons\\INV_Enchant_DustVision",
		categories = { 333, 755, 197 },
	},
	{
		id = 11134,
		name = "Lesser Mystic Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceMysticalSmall",
		categories = { 333 },
	},
	{
		id = 11135,
		name = "Greater Mystic Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceMysticalLarge",
		categories = { 333 },
	},
	{
		id = 11176,
		name = "Dream Dust",
		icon = "Interface\\Icons\\INV_Enchant_DustDream",
		categories = { 333, 171, 197, 186 },
	},
	{
		id = 11174,
		name = "Lesser Nether Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceNetherSmall",
		categories = { 333 },
	},
	{
		id = 11175,
		name = "Greater Nether Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceNetherLarge",
		categories = { 333 },
	},
	{
		id = 11177,
		name = "Small Radiant Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardRadientSmall",
		categories = { 333 },
	},
	{
		id = 11178,
		name = "Large Radiant Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardRadientLarge",
		categories = { 333, 755 },
	},
	{
		id = 16204,
		name = "Illusion Dust",
		icon = "Interface\\Icons\\INV_Enchant_DustIllusion",
		categories = { 333 },
	},
	{
		id = 16202,
		name = "Lesser Eternal Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceEternalSmall",
		categories = { 333 },
	},
	{
		id = 16203,
		name = "Greater Eternal Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceEternalLarge",
		categories = { 333, 197 },
	},
	{
		id = 14343,
		name = "Small Brilliant Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardBrilliantSmall",
		categories = { 333 },
	},
	{
		id = 14344,
		name = "Large Brilliant Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardBrilliantLarge",
		categories = { 197, 333 },
	},
	{
		id = 20725,
		name = "Nexus Crystal",
		icon = "Interface\\Icons\\INV_Enchant_ShardNexusLarge",
		categories = { 164, 333 },
	},
	{
		id = 22445,
		name = "Arcane Dust",
		icon = "Interface\\Icons\\INV_Enchant_DustArcane",
		categories = { 197, 333, 164, 202, 165 },
	},
	{
		id = 22447,
		name = "Lesser Planar Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceArcaneSmall",
		categories = { 333 },
	},
	{
		id = 22446,
		name = "Greater Planar Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceArcaneLarge",
		categories = { 333, 197 },
	},
	{
		id = 22448,
		name = "Small Prismatic Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardPrismaticSmall",
		categories = { 333, 202, 165 },
	},
	{
		id = 22449,
		name = "Large Prismatic Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardPrismaticLarge",
		categories = { 333, 164, 202 },
	},
	{
		id = 22450,
		name = "Void Crystal",
		icon = "Interface\\Icons\\INV_Enchant_VoidCrystal",
		categories = { 333, 165, 197, 164 },
	},
	{
		id = 34054,
		name = "Infinite Dust",
		icon = "Interface\\Icons\\INV_Misc_Dust_Infinite",
		categories = { 333, 197, 755, 164 },
	},
	{
		id = 34056,
		name = "Lesser Cosmic Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceCosmicLesser",
		categories = { 333 },
	},
	{
		id = 34055,
		name = "Greater Cosmic Essence",
		icon = "Interface\\Icons\\INV_Enchant_EssenceCosmicGreater",
		categories = { 333, 165 },
	},
	{
		id = 34052,
		name = "Dream Shard",
		icon = "Interface\\Icons\\INV_Enchant_DreamShard_02",
		categories = { 333, 755, 202, 197 },
	},
	{
		id = 34057,
		name = "Abyss Crystal",
		icon = "Interface\\Icons\\INV_Enchant_AbyssCrystal",
		categories = { 333, 165 },
	},
	{
		id = 38682,
		name = "Armor Vellum",
		icon = "Interface\\Icons\\INV_Inscription_ArmorScroll01",
		categories = { 333, 773 },
	},
	{
		id = 37602,
		name = "Armor Vellum II",
		icon = "Interface\\Icons\\INV_Inscription_ArmorScroll02",
		categories = { 333, 773 },
	},
	{
		id = 43145,
		name = "Armor Vellum III",
		icon = "Interface\\Icons\\INV_Inscription_ArmorScroll03",
		categories = { 333, 773 },
	},
	{
		id = 39349,
		name = "Weapon Vellum",
		icon = "Interface\\Icons\\INV_Inscription_WeaponScroll01",
		categories = { 333, 773 },
	},
	{
		id = 39350,
		name = "Weapon Vellum II",
		icon = "Interface\\Icons\\INV_Inscription_WeaponScroll02",
		categories = { 333, 773 },
	},
	{
		id = 43146,
		name = "Weapon Vellum III",
		icon = "Interface\\Icons\\INV_Inscription_WeaponScroll03",
		categories = { 333, 773 },
	},
})
