local _, internal = ...

internal.appendData({
	{
		id = 6303,
		name = "Raw Slitherskin Mackerel",
		icon = "Interface\\Icons\\INV_Misc_Fish_24",
		categories = { 185 },
	},
	{
		id = 6291,
		name = "Raw Brilliant Smallfish",
		icon = "Interface\\Icons\\INV_Misc_Fish_08",
		categories = { 185 },
	},
	{
		id = 6361,
		name = "Raw Rainbow Fin Albacore",
		icon = "Interface\\Icons\\INV_Misc_Fish_25",
		categories = { 185 },
	},
	{
		id = 6289,
		name = "Raw Longjaw Mud Snapper",
		icon = "Interface\\Icons\\INV_Misc_Fish_32",
		categories = { 185 },
	},
	{
		id = 6317,
		name = "Raw Loch Frenzy",
		icon = "Interface\\Icons\\INV_Misc_Fish_03",
		categories = { 185 },
	},
	{
		id = 5468,
		name = "Soft Frenzy Flesh",
		icon = "Interface\\Icons\\INV_Misc_Fish_04",
		categories = { 185 },
	},
	{
		id = 21071,
		name = "Raw Sagefish",
		icon = "Interface\\Icons\\INV_Misc_Fish_20",
		categories = { 185 },
	},
	{
		id = 6522,
		name = "Deviate Fish",
		icon = "Interface\\Icons\\INV_Misc_MonsterHead_01",
		categories = { 185, 171 },
	},
	{
		id = 6308,
		name = "Raw Bristle Whisker Catfish",
		icon = "Interface\\Icons\\INV_Misc_Fish_30",
		categories = { 185 },
	},
	{
		id = 6362,
		name = "Raw Rockscale Cod",
		icon = "Interface\\Icons\\INV_Misc_Fish_04",
		categories = { 185 },
	},
	{
		id = 8365,
		name = "Raw Mithril Head Trout",
		icon = "Interface\\Icons\\INV_Misc_Fish_02",
		categories = { 185 },
	},
	{
		id = 21153,
		name = "Raw Greater Sagefish",
		icon = "Interface\\Icons\\INV_Misc_Fish_21",
		categories = { 185 },
	},
	{
		id = 13754,
		name = "Raw Glossy Mightfish",
		icon = "Interface\\Icons\\INV_Misc_MonsterHead_03",
		categories = { 185 },
	},
	{
		id = 13758,
		name = "Raw Redgill",
		icon = "Interface\\Icons\\INV_Misc_Fish_06",
		categories = { 185 },
	},
	{
		id = 4603,
		name = "Raw Spotted Yellowtail",
		icon = "Interface\\Icons\\INV_Misc_Fish_01",
		categories = { 185 },
	},
	{
		id = 13755,
		name = "Winter Squid",
		icon = "Interface\\Icons\\INV_Misc_Fish_13",
		categories = { 185 },
	},
	{
		id = 13756,
		name = "Raw Summer Bass",
		icon = "Interface\\Icons\\INV_Misc_Fish_03",
		categories = { 185 },
	},
	{
		id = 13759,
		name = "Raw Nightfin Snapper",
		icon = "Interface\\Icons\\INV_Misc_Fish_23",
		categories = { 185 },
	},
	{
		id = 13760,
		name = "Raw Sunscale Salmon",
		icon = "Interface\\Icons\\INV_Misc_Fish_19",
		categories = { 185 },
	},
	{
		id = 13889,
		name = "Raw Whitescale Salmon",
		icon = "Interface\\Icons\\INV_Misc_Fish_20",
		categories = { 185 },
	},
	{
		id = 13893,
		name = "Large Raw Mightfish",
		icon = "Interface\\Icons\\INV_Misc_MonsterHead_02",
		categories = { 185 },
	},
	{
		id = 27422,
		name = "Barbed Gill Trout",
		icon = "Interface\\Icons\\INV_Misc_Fish_37",
		categories = { 185 },
	},
	{
		id = 33823,
		name = "Bloodfin Catfish",
		icon = "Interface\\Icons\\INV_Misc_Fish_29",
		categories = { 185 },
	},
	{
		id = 27425,
		name = "Spotted Feltail",
		icon = "Interface\\Icons\\INV_Misc_Fish_39",
		categories = { 185 },
	},
	{
		id = 13757,
		name = "Lightning Eel",
		icon = "Interface\\Icons\\INV_Misc_Fish_12",
		categories = { 185 },
	},
	{
		id = 27429,
		name = "Zangarian Sporefish",
		icon = "Interface\\Icons\\INV_Misc_Fish_34",
		categories = { 185 },
	},
	{
		id = 27435,
		name = "Figluster's Mudfish",
		icon = "Interface\\Icons\\INV_Misc_Fish_41",
		categories = { 185 },
	},
	{
		id = 27437,
		name = "Icefin Bluefish",
		icon = "Interface\\Icons\\INV_Misc_Fish_23",
		categories = { 185 },
	},
	{
		id = 33824,
		name = "Crescent-Tail Skullfish",
		icon = "Interface\\Icons\\INV_Misc_Fish_40",
		categories = { 185 },
	},
	{
		id = 27438,
		name = "Golden Darter",
		icon = "Interface\\Icons\\INV_Misc_Fish_36",
		categories = { 185 },
	},
	{
		id = 41810,
		name = "Fangtooth Herring",
		icon = "Interface\\Icons\\INV_Misc_Fish_67",
		categories = { 185 },
	},
	{
		id = 41808,
		name = "Bonescale Snapper",
		icon = "Interface\\Icons\\INV_Misc_Fish_48",
		categories = { 185 },
	},
	{
		id = 41812,
		name = "Barrelhead Goby",
		icon = "Interface\\Icons\\INV_Misc_Fish_57",
		categories = { 185 },
	},
	{
		id = 41803,
		name = "Rockfin Grouper",
		icon = "Interface\\Icons\\INV_Misc_Fish_46",
		categories = { 185 },
	},
	{
		id = 41802,
		name = "Imperial Manta Ray",
		icon = "Interface\\Icons\\INV_Misc_Fish_59",
		categories = { 185 },
	},
	{
		id = 41806,
		name = "Musselback Sculpin",
		icon = "Interface\\Icons\\INV_Misc_Fish_62",
		categories = { 185 },
	},
	{
		id = 41813,
		name = "Nettlefish",
		icon = "Interface\\Icons\\INV_Misc_Fish_72",
		categories = { 185 },
	},
	{
		id = 41809,
		name = "Glacial Salmon",
		icon = "Interface\\Icons\\INV_Misc_Fish_51",
		categories = { 185 },
	},
	{
		id = 27515,
		name = "Huge Spotted Feltail",
		icon = "Interface\\Icons\\INV_Misc_Fish_39",
		categories = { 185 },
	},
	{
		id = 27516,
		name = "Enormous Barbed Gill Trout",
		icon = "Interface\\Icons\\INV_Misc_Fish_37",
		categories = { 185 },
	},
	{
		id = 41807,
		name = "Dragonfin Angelfish",
		icon = "Interface\\Icons\\INV_Misc_Fish_54",
		categories = { 185 },
	},
	{
		id = 41801,
		name = "Moonglow Cuttlefish",
		icon = "Interface\\Icons\\INV_Misc_Fish_70",
		categories = { 185 },
	},
	{
		id = 41800,
		name = "Deep Sea Monsterbelly",
		icon = "Interface\\Icons\\INV_Misc_Fish_60",
		categories = { 185 },
	},
})
