local _, internal = ...

internal.appendData({
	{
		id = 2835,
		name = "Rough Stone",
		icon = "Interface\\Icons\\INV_Stone_06",
		categories = { 164, 202, 755, 186 },
	},
	{
		id = 4357,
		name = "Rough Blasting Powder",
		icon = "Interface\\Icons\\INV_Misc_Dust_01",
		categories = { 202 },
	},
	{
		id = 3470,
		name = "Rough Grinding Stone",
		icon = "Interface\\Icons\\INV_Stone_GrindingStone_01",
		categories = { 164 },
	},
	{
		id = 2836,
		name = "Coarse Stone",
		icon = "Interface\\Icons\\INV_Stone_09",
		categories = { 164, 202, 755, 186 },
	},
	{
		id = 4364,
		name = "Coarse Blasting Powder",
		icon = "Interface\\Icons\\INV_Misc_Dust_02",
		categories = { 202 },
	},
	{
		id = 3478,
		name = "Coarse Grinding Stone",
		icon = "Interface\\Icons\\INV_Stone_GrindingStone_02",
		categories = { 164 },
	},
	{
		id = 2838,
		name = "Heavy Stone",
		icon = "Interface\\Icons\\INV_Stone_12",
		categories = { 164, 202, 755, 186 },
	},
	{
		id = 4377,
		name = "Heavy Blasting Powder",
		icon = "Interface\\Icons\\INV_Misc_Dust_06",
		categories = { 202 },
	},
	{
		id = 3486,
		name = "Heavy Grinding Stone",
		icon = "Interface\\Icons\\INV_Stone_GrindingStone_03",
		categories = { 164 },
	},
	{
		id = 7912,
		name = "Solid Stone",
		icon = "Interface\\Icons\\INV_Stone_10",
		categories = { 164, 202, 755, 186 },
	},
	{
		id = 10505,
		name = "Solid Blasting Powder",
		icon = "Interface\\Icons\\INV_Misc_Powder_Black",
		categories = { 202 },
	},
	{
		id = 7966,
		name = "Solid Grinding Stone",
		icon = "Interface\\Icons\\INV_Stone_GrindingStone_04",
		categories = { 164 },
	},
	{
		id = 12365,
		name = "Dense Stone",
		icon = "Interface\\Icons\\INV_Misc_StoneTablet_07",
		categories = { 164, 202, 755, 186 },
	},
	{
		id = 15992,
		name = "Dense Blasting Powder",
		icon = "Interface\\Icons\\INV_Misc_Ammo_Gunpowder_01",
		categories = { 202 },
	},
	{
		id = 12644,
		name = "Dense Grinding Stone",
		icon = "Interface\\Icons\\INV_Stone_GrindingStone_05",
		categories = { 164 },
	},
	{
		id = 2770,
		name = "Copper Ore",
		icon = "Interface\\Icons\\INV_Ore_Copper_01",
		categories = { 186 },
	},
	{
		id = 2840,
		name = "Copper Bar",
		icon = "Interface\\Icons\\INV_Ingot_02",
		categories = { 186, 164, 202, 755, 165 },
	},
	{
		id = 2771,
		name = "Tin Ore",
		icon = "Interface\\Icons\\INV_Ore_Tin_01",
		categories = { 186 },
	},
	{
		id = 3576,
		name = "Tin Bar",
		icon = "Interface\\Icons\\INV_Ingot_05",
		categories = { 186 },
	},
	{
		id = 2841,
		name = "Bronze Bar",
		icon = "Interface\\Icons\\INV_Ingot_Bronze",
		categories = { 164, 202, 755 },
	},
	{
		id = 2775,
		name = "Silver Ore",
		icon = "Interface\\Icons\\INV_Stone_16",
		categories = { 186 },
	},
	{
		id = 2842,
		name = "Silver Bar",
		icon = "Interface\\Icons\\INV_Ingot_01",
		categories = { 164, 202, 755 },
	},
	{
		id = 2776,
		name = "Gold Ore",
		icon = "Interface\\Icons\\INV_Ore_Gold_01",
		categories = { 186 },
	},
	{
		id = 3577,
		name = "Gold Bar",
		icon = "Interface\\Icons\\INV_Ingot_03",
		categories = { 164, 202, 197, 755 },
	},
	{
		id = 2772,
		name = "Iron Ore",
		icon = "Interface\\Icons\\INV_Ore_Iron_01",
		categories = { 186, 333 },
	},
	{
		id = 3575,
		name = "Iron Bar",
		icon = "Interface\\Icons\\INV_Ingot_Iron",
		categories = { 164, 186, 202, 171, 755 },
	},
	{
		id = 3857,
		name = "Coal",
		icon = "Interface\\Icons\\INV_Ore_Tin_01",
		categories = { 186 },
	},
	{
		id = 3466,
		name = "Strong Flux",
		icon = "Interface\\Icons\\INV_Misc_Ammo_Gunpowder_01",
		categories = { 164 },
	},
	{
		id = 3859,
		name = "Steel Bar",
		icon = "Interface\\Icons\\INV_Ingot_Steel",
		categories = { 164, 202 },
	},
	{
		id = 3858,
		name = "Mithril Ore",
		icon = "Interface\\Icons\\INV_Ore_Mithril_02",
		categories = { 171, 186 },
	},
	{
		id = 3860,
		name = "Mithril Bar",
		icon = "Interface\\Icons\\INV_Ingot_06",
		categories = { 164, 171, 202, 755 },
	},
	{
		id = 7911,
		name = "Truesilver Ore",
		icon = "Interface\\Icons\\INV_Ore_TrueSilver_01",
		categories = { 186 },
	},
	{
		id = 6037,
		name = "Truesilver Bar",
		icon = "Interface\\Icons\\INV_Ingot_08",
		categories = { 164, 197, 202, 333, 755 },
	},
	{
		id = 10620,
		name = "Thorium Ore",
		icon = "Interface\\Icons\\INV_Ore_Thorium_02",
		categories = { 186, 171 },
	},
	{
		id = 12359,
		name = "Thorium Bar",
		icon = "Interface\\Icons\\INV_Ingot_07",
		categories = { 164, 333, 171, 202, 755, 186 },
	},
	{
		id = 12655,
		name = "Enchanted Thorium Bar",
		icon = "Interface\\Icons\\INV_Ingot_Eternium",
		categories = { 164 },
	},
	{
		id = 11370,
		name = "Dark Iron Ore",
		icon = "Interface\\Icons\\INV_Ore_Mithril_01",
		categories = { 186 },
	},
	{
		id = 11371,
		name = "Dark Iron Bar",
		icon = "Interface\\Icons\\INV_Ingot_Mithril",
		categories = { 164, 202, 755 },
	},
	{
		id = 12363,
		name = "Arcane Crystal",
		icon = "Interface\\Icons\\INV_Misc_Gem_Topaz_01",
		categories = { 171, 755, 333, 186 },
	},
	{
		id = 12360,
		name = "Arcanite Bar",
		icon = "Interface\\Icons\\INV_Misc_StoneTablet_05",
		categories = { 164, 202, 197, 755, 186 },
	},
	{
		id = 17203,
		name = "Sulfuron Ingot",
		icon = "Interface\\Icons\\Spell_Fire_SealOfFire",
		categories = { 164 },
	},
	{
		id = 18562,
		name = "Elementium Ore",
		icon = "Interface\\Icons\\INV_Stone_SharpeningStone_01",
		categories = { 186, 164 },
	},
	{
		id = 17771,
		name = "Elementium Bar",
		icon = "Interface\\Icons\\INV_Ingot_Thorium",
		categories = { 164 },
	},
	{
		id = 22202,
		name = "Small Obsidian Shard",
		icon = "Interface\\Icons\\INV_Misc_StoneTablet_01",
		categories = { 164, 186 },
	},
	{
		id = 22203,
		name = "Large Obsidian Shard",
		icon = "Interface\\Icons\\INV_Stone_15",
		categories = { 164, 186 },
	},
	{
		id = 2798,
		name = "Rethban Ore",
		icon = "Interface\\Icons\\INV_Ore_Iron_01",
		categories = { 186 },
	},
	{
		id = 3340,
		name = "Incendicite Ore",
		icon = "Interface\\Icons\\INV_Ore_Thorium_01",
		categories = { 186 },
	},
	{
		id = 4278,
		name = "Lesser Bloodstone Ore",
		icon = "Interface\\Icons\\INV_Ore_Thorium_01",
		categories = { 186 },
	},
	{
		id = 5833,
		name = "Indurium Ore",
		icon = "Interface\\Icons\\INV_Ore_Mithril_01",
		categories = { 186 },
	},
	{
		id = 11184,
		name = "Blue Power Crystal",
		icon = "Interface\\Icons\\INV_Misc_Gem_Sapphire_03",
		categories = { 164 },
	},
	{
		id = 11185,
		name = "Green Power Crystal",
		icon = "Interface\\Icons\\INV_Misc_Gem_Emerald_02",
		categories = { 164 },
	},
	{
		id = 11186,
		name = "Red Power Crystal",
		icon = "Interface\\Icons\\INV_Misc_Gem_Ruby_03",
		categories = { 164 },
	},
	{
		id = 11188,
		name = "Yellow Power Crystal",
		icon = "Interface\\Icons\\INV_Misc_Gem_Topaz_02",
		categories = { 164 },
	},
	-- Burning Crusade
	{
		id = 23424,
		name = "Fel Iron Ore",
		icon = "Interface\\Icons\\INV_Ore_FelIron",
		categories = { 186 },
	},
	{
		id = 23445,
		name = "Fel Iron Bar",
		icon = "Interface\\Icons\\INV_Ingot_FelIron",
		categories = { 186, 164, 202, 755 },
	},
	{
		id = 23448,
		name = "Felsteel Bar",
		icon = "Interface\\Icons\\INV_Ingot_Felsteel",
		categories = { 164, 202, 755 },
	},
	{
		id = 23427,
		name = "Eternium Ore",
		icon = "Interface\\Icons\\INV_Ore_Eternium",
		categories = { 186, 333 },
	},
	{
		id = 23447,
		name = "Eternium Bar",
		icon = "Interface\\Icons\\INV_Ingot_11",
		categories = { 186, 164, 755 },
	},
	{
		id = 23781,
		name = "Elemental Blasting Powder",
		icon = "Interface\\Icons\\Inv_Misc_ammo_Gunpowder_07",
		categories = { 202 },
	},
	{
		id = 23425,
		name = "Adamantite Ore",
		icon = "Interface\\Icons\\INV_Ore_Adamantium",
		categories = { 186 },
	},
	{
		id = 23446,
		name = "Adamantite Bar",
		icon = "Interface\\Icons\\INV_Ingot_10",
		categories = { 186, 164, 202, 755 },
	},
	{
		id = 23573,
		name = "Hardened Adamantite Bar",
		icon = "Interface\\Icons\\INV_Ingot_Adamantite",
		categories = { 164, 202, 755, 186 },
	},
	{
		id = 23426,
		name = "Khorium Ore",
		icon = "Interface\\Icons\\INV_Ore_Khorium",
		categories = { 186 },
	},
	{
		id = 23449,
		name = "Khorium Bar",
		icon = "Interface\\Icons\\INV_Ingot_09",
		categories = { 164, 202, 755, 186 },
	},
	{
		id = 35128,
		name = "Hardened Khorium",
		icon = "Interface\\Icons\\INV_Ingot_Thorium",
		categories = { 202, 164, 755 },
	},
	{
		id = 22634,
		name = "Underlight Ore",
		icon = "Interface\\Icons\\INV_Ore_Mithril_01",
		categories = { 186 },
	},
	{
		id = 32464,
		name = "Nethercite Ore",
		icon = "Interface\\Icons\\INV_Ore_Ethernium_01",
		categories = { 186 },
	},
	-- Wrath of the Lich King
	{
		id = 36909,
		name = "Cobalt Ore",
		icon = "Interface\\Icons\\INV_Ore_Cobalt",
		categories = { 186 },
	},
	{
		id = 36916,
		name = "Cobalt Bar",
		icon = "Interface\\Icons\\INV_Ingot_Cobalt",
		categories = { 164, 202 },
	},
	{
		id = 36912,
		name = "Saronite Ore",
		icon = "Interface\\Icons\\INV_Ore_Saronite_01",
		categories = { 186 },
	},
	{
		id = 36913,
		name = "Saronite Bar",
		icon = "Interface\\Icons\\INV_Ingot_Yoggthorite",
		categories = { 202, 164, 171 },
	},
	{
		id = 36910,
		name = "Titanium Ore",
		icon = "Interface\\Icons\\INV_Ore_Platinum_01",
		categories = { 186 },
	},
	{
		id = 41163,
		name = "Titanium Bar",
		icon = "Interface\\Icons\\INV_Ingot_Platinum",
		categories = { 202, 333, 186, 164, 755 },
	},
	{
		id = 37663,
		name = "Titansteel Bar",
		icon = "Interface\\Icons\\INV_Ingot_Titansteel_blue",
		categories = { 164, 202, 333 },
	},
	{
		id = 49908,
		name = "Primordial Saronite",
		icon = "Interface\\Icons\\spell_fire_felflamebreath",
		categories = { 164, 165, 197 },
	},
})
