local _, internal = ...

internal.appendData({
	{
		id = 12811,
		name = "Righteous Orb",
		icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_03",
		categories = { 164, 197, 333 },
	},
	{
		id = 17010,
		name = "Fiery Core",
		icon = "Interface\\Icons\\Spell_Fire_FlameBolt",
		categories = { 197, 165, 164, 202, 186 },
	},
	{
		id = 17011,
		name = "Lava Core",
		icon = "Interface\\Icons\\Spell_Nature_Earthquake",
		categories = { 197, 165, 164, 202 },
	},
	{
		id = 4402,
		name = "Small Flame Sac",
		icon = "Interface\\Icons\\INV_Misc_Organ_06",
		categories = { 202, 171, 185 },
	},
	{
		id = 4096,
		name = "Coarse Gorilla Hair",
		icon = "Interface\\Icons\\INV_Misc_MonsterTail_03",
		categories = { 165 },
	},
	{
		id = 5635,
		name = "Sharp Claw",
		icon = "Interface\\Icons\\INV_Misc_MonsterClaw_03",
		categories = { 171, 164 },
	},
	{
		id = 5637,
		name = "Large Fang",
		icon = "Interface\\Icons\\INV_Misc_Bone_08",
		categories = { 165, 171, 164, 333, 755 },
	},
	{
		id = 8146,
		name = "Wicked Claw",
		icon = "Interface\\Icons\\INV_Misc_MonsterClaw_01",
		categories = { 164, 165 },
	},
	{
		id = 8151,
		name = "Flask of Mojo",
		icon = "Interface\\Icons\\INV_Potion_15",
		categories = { 165, 202, 755 },
	},
	{
		id = 8152,
		name = "Flask of Big Mojo",
		icon = "Interface\\Icons\\INV_Potion_12",
		categories = { 165, 755 },
	},
	{
		id = 12804,
		name = "Powerful Mojo",
		icon = "Interface\\Icons\\Spell_Nature_AstralRecalGroup",
		categories = { 164, 165, 197, 171, 202, 755 },
	},
	{
		id = 19943,
		name = "Massive Mojo",
		icon = "Interface\\Icons\\Spell_Nature_Strength",
		categories = { 171 },
	},
	{
		id = 12938,
		name = "Blood of Heroes",
		icon = "Interface\\Icons\\INV_Potion_33",
		categories = { 171, 755 },
	},
	{
		id = 12662,
		name = "Demonic Rune",
		icon = "Interface\\Icons\\INV_Misc_Rune_04",
		categories = { 164, 197, 755 },
	},
	{
		id = 12753,
		name = "Skin of Shadow",
		icon = "Interface\\Icons\\INV_Misc_ShadowEgg",
		categories = { 165, 164 },
	},
	{
		id = 12809,
		name = "Guardian Stone",
		icon = "Interface\\Icons\\INV_Stone_02",
		categories = { 164, 197, 165 },
	},
	{
		id = 20520,
		name = "Dark Rune",
		icon = "Interface\\Icons\\Spell_Shadow_SealOfKings",
		categories = { 197, 164 },
	},
	{
		id = 22682,
		name = "Frozen Rune",
		icon = "Interface\\Icons\\INV_Misc_Rune_09",
		categories = { 197, 165, 164 },
	},
	{
		id = 45087,
		name = "Runed Orb",
		icon = "Interface\\Icons\\inv_misc_runedorb_01",
		categories = { 164, 165, 197 },
	},
	{
		id = 47556,
		name = "Crusader Orb",
		icon = "Interface\\Icons\\spell_holy_rune",
		categories = { 164, 165, 197 },
	},
	{
		id = 8150,
		name = "Deeprock Salt",
		icon = "Interface\\Icons\\INV_Misc_Dust_02",
		categories = { 165, 202, 185 },
	},
	{
		id = 9061,
		name = "Goblin Rocket Fuel",
		icon = "Interface\\Icons\\INV_Cask_02",
		categories = { 202, 185 },
	},
	{
		id = 12735,
		name = "Frayed Abomination Stitching",
		icon = "Interface\\Icons\\INV_Misc_Pelt_Boar_Ruin_03",
		categories = { 0, 333 },
	},
	{
		id = 11291,
		name = "Star Wood",
		icon = "Interface\\Icons\\INV_TradeskillItem_03",
		categories = { 333, 202 },
	},
	{
		id = 17034,
		name = "Maple Seed",
		icon = "Interface\\Icons\\INV_Misc_Food_02",
		categories = { 333 },
	},
	{
		id = 17035,
		name = "Stranglethorn Seed",
		icon = "Interface\\Icons\\INV_Misc_Food_02",
		categories = { 333 },
	},
	{
		id = 814,
		name = "Flask of Oil",
		icon = "Interface\\Icons\\INV_Drink_07",
		categories = { 202 },
	},
	{
		id = 6530,
		name = "Nightcrawlers",
		icon = "Interface\\Icons\\INV_Misc_MonsterTail_03",
		categories = { 202 },
	},
	{
		id = 5056,
		name = "Root Sample",
		icon = "Interface\\Icons\\INV_Misc_Herb_07",
		categories = { 182 },
	},
	{
		id = 11514,
		name = "Fel Creep",
		icon = "Interface\\Icons\\Spell_Nature_Acid_01",
		categories = { 0, 182 },
	},
	{
		id = 24401,
		name = "Unidentified Plant Parts",
		icon = "Interface\\Icons\\INV_Misc_Flower_03",
		categories = { 182 },
	},
	{
		id = 32468,
		name = "Netherdust Pollen",
		icon = "Interface\\Icons\\INV_Enchant_DustSoul",
		categories = { 182 },
	},
	{
		id = 32506,
		name = "Netherwing Egg",
		icon = "Interface\\Icons\\INV_Misc_ShadowEgg",
		categories = { 186, 182 },
	},
	{
		id = 35229,
		name = "Nether Residue",
		icon = "Interface\\Icons\\INV_Misc_Dust_03",
		categories = { 393, 186, 182 },
	},
	{
		id = 4289,
		name = "Salt",
		icon = "Interface\\Icons\\INV_Misc_Dust_02",
		categories = { 165 },
	},
	{
		id = 5373,
		name = "Lucky Charm",
		icon = "Interface\\Icons\\INV_Misc_ArmorKit_06",
		categories = { 165 },
	},
	{
		id = 7071,
		name = "Iron Buckle",
		icon = "Interface\\Icons\\INV_Misc_ArmorKit_12",
		categories = { 165, 197 },
	},
	{
		id = 15409,
		name = "Refined Deeprock Salt",
		icon = "Interface\\Icons\\INV_Misc_Dust_01",
		categories = { 165 },
	},
	{
		id = 18240,
		name = "Ogre Tannin",
		icon = "Interface\\Icons\\INV_Potion_08",
		categories = { 197, 165 },
	},
	{
		id = 18512,
		name = "Larval Acid",
		icon = "Interface\\Icons\\INV_Potion_22",
		categories = { 165 },
	},
	{
		id = 5075,
		name = "Blood Shard",
		icon = "Interface\\Icons\\INV_Misc_Gem_Ruby_01",
		categories = { 186 },
	},
	{
		id = 11513,
		name = "Tainted Vitriol",
		icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_01",
		categories = { 0, 186 },
	},
	{
		id = 36728,
		name = "Ice Shard Cluster",
		icon = "Interface\\Icons\\INV_Jewelry_Talisman_17",
		categories = { 186 },
	},
	{
		id = 11512,
		name = "Patch of Tainted Skin",
		icon = "Interface\\Icons\\INV_Misc_Pelt_02",
		categories = { 0, 393 },
	},
	{
		id = 11040,
		name = "Morrowgrain",
		icon = "Interface\\Icons\\INV_Misc_Herb_05",
		categories = { 197 },
	},
	{
		id = 21882,
		name = "Soul Essence",
		icon = "Interface\\Icons\\Spell_Shadow_SoulLeech_3",
		categories = { 197 },
	},
	{
		id = 4582,
		name = "Soft Bushy Tail",
		icon = "Interface\\Icons\\INV_Misc_MonsterTail_02",
		categories = { 0 },
	},
	{
		id = 5117,
		name = "Vibrant Plume",
		icon = "Interface\\Icons\\INV_Feather_12",
		categories = { 0 },
	},
	{
		id = 5134,
		name = "Small Furry Paw",
		icon = "Interface\\Icons\\Ability_Hunter_MendPet",
		categories = { 0 },
	},
	{
		id = 11018,
		name = "Un'Goro soil",
		icon = "Interface\\Icons\\INV_Misc_Dust_02",
		categories = { 0 },
	},
	{
		id = 11022,
		name = "Packet of Tharlendris Seeds",
		icon = "Interface\\Icons\\Spell_Nature_ProtectionFormNature",
		categories = { 0 },
	},
	{
		id = 11404,
		name = "Evil Bat Eye",
		icon = "Interface\\Icons\\INV_Misc_Eye_01",
		categories = { 0 },
	},
	{
		id = 11407,
		name = "Torn Bear Pelt",
		icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_05",
		categories = { 0 },
	},
	{
		id = 11515,
		name = "Corrupted Soul Shard",
		icon = "Interface\\Icons\\INV_Enchant_ShardRadientSmall",
		categories = { 0 },
	},
	{
		id = 11516,
		name = "Cenarion Plant Salve",
		icon = "Interface\\Icons\\INV_Drink_17",
		categories = { 0 },
	},
	{
		id = 12840,
		name = "Minion's Scourgestone",
		icon = "Interface\\Icons\\INV_Jewelry_Talisman_14",
		categories = { 0 },
	},
	{
		id = 12841,
		name = "Invader's Scourgestone",
		icon = "Interface\\Icons\\INV_Jewelry_Talisman_13",
		categories = { 0 },
	},
	{
		id = 12843,
		name = "Corruptor's Scourgestone",
		icon = "Interface\\Icons\\INV_Jewelry_Talisman_12",
		categories = { 0 },
	},
	{
		id = 18944,
		name = "Incendosaur Scale",
		icon = "Interface\\Icons\\INV_Misc_MonsterScales_16",
		categories = { 0 },
	},
	{
		id = 18945,
		name = "Dark Iron Residue",
		icon = "Interface\\Icons\\INV_Enchant_DustSoul",
		categories = { 0 },
	},
	{
		id = 19933,
		name = "Glowing Scorpid Blood",
		icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",
		categories = { 0 },
	},
	{
		id = 21377,
		name = "Deadwood Headdress Feather",
		icon = "Interface\\Icons\\INV_Feather_13",
		categories = { 0 },
	},
	{
		id = 21383,
		name = "Winterfall Spirit Beads",
		icon = "Interface\\Icons\\INV_Jewelry_Amulet_05",
		categories = { 0 },
	},
	{
		id = 25744,
		name = "Dampscale Basilisk Eye",
		icon = "Interface\\Icons\\INV_Misc_Eye_01",
		categories = { 0 },
	},
	{
		id = 29425,
		name = "Mark of Kil'jaeden",
		icon = "Interface\\Icons\\Spell_Shadow_DemonicFortitude",
		categories = { 0 },
	},
	{
		id = 29426,
		name = "Firewing Signet",
		icon = "Interface\\Icons\\INV_Jewelry_Ring_23",
		categories = { 0 },
	},
	{
		id = 25433,
		name = "Obsidian Warbeads",
		icon = "Interface\\Icons\\INV_Jewelry_Necklace_19",
		categories = { 0 },
	},
	{
		id = 25802,
		name = "Dreadfang Venom Sac",
		icon = "Interface\\Icons\\INV_Misc_Organ_04",
		categories = { 0 },
	},
})
