-- ============================================================
-- AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
-- Produced by the F-011 Goblin Zone extraction pipeline
-- (Zeppelin-Craft/Scripts/Goblin Zone Port/). Any manual edit
-- here is overwritten the next time the pipeline runs.
--   * To change this output: edit the migration/translation script.
--   * For a one-off manual fix: add a separate zz_[I-xxx]_*.sql file
--     (it loads after these rows and overrides the ones it needs).
-- ============================================================

-- F-011 vendor items (wago ItemSparse 4.4.2, appended 84424+). Icons deferred.

-- Cata 49241 -> 84424 (Waterlogged Cloth Vest)
DELETE FROM item_template WHERE entry = 84424;
INSERT INTO item_template SET `entry`=84424, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Waterlogged Cloth Vest', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=48, `SellPrice`=9, `InventoryType`=5, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49242 -> 84425 (Waterlogged Cloth Belt)
DELETE FROM item_template WHERE entry = 84425;
INSERT INTO item_template SET `entry`=84425, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Waterlogged Cloth Belt', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=24, `SellPrice`=4, `InventoryType`=6, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49243 -> 84426 (Waterlogged Cloth Pants)
DELETE FROM item_template WHERE entry = 84426;
INSERT INTO item_template SET `entry`=84426, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Waterlogged Cloth Pants', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=48, `SellPrice`=9, `InventoryType`=7, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49244 -> 84427 (Waterlogged Cloth Boots)
DELETE FROM item_template WHERE entry = 84427;
INSERT INTO item_template SET `entry`=84427, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Waterlogged Cloth Boots', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=36, `SellPrice`=7, `InventoryType`=8, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49245 -> 84428 (Waterlogged Cloth Bracers)
DELETE FROM item_template WHERE entry = 84428;
INSERT INTO item_template SET `entry`=84428, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Waterlogged Cloth Bracers', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=24, `SellPrice`=4, `InventoryType`=9, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49246 -> 84429 (Waterlogged Cloth Gloves)
DELETE FROM item_template WHERE entry = 84429;
INSERT INTO item_template SET `entry`=84429, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Waterlogged Cloth Gloves', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=24, `SellPrice`=4, `InventoryType`=10, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49247 -> 84430 (Drenched Leather Belt)
DELETE FROM item_template WHERE entry = 84430;
INSERT INTO item_template SET `entry`=84430, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Drenched Leather Belt', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=30, `SellPrice`=6, `InventoryType`=6, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49248 -> 84431 (Drenched Leather Boots)
DELETE FROM item_template WHERE entry = 84431;
INSERT INTO item_template SET `entry`=84431, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Drenched Leather Boots', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=45, `SellPrice`=9, `InventoryType`=8, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49249 -> 84432 (Drenched Leather Bracers)
DELETE FROM item_template WHERE entry = 84432;
INSERT INTO item_template SET `entry`=84432, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Drenched Leather Bracers', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=30, `SellPrice`=6, `InventoryType`=9, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49250 -> 84433 (Drenched Leather Gloves)
DELETE FROM item_template WHERE entry = 84433;
INSERT INTO item_template SET `entry`=84433, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Drenched Leather Gloves', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=30, `SellPrice`=6, `InventoryType`=10, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49251 -> 84434 (Drenched Leather Pants)
DELETE FROM item_template WHERE entry = 84434;
INSERT INTO item_template SET `entry`=84434, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Drenched Leather Pants', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=60, `SellPrice`=12, `InventoryType`=7, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49252 -> 84435 (Drenched Leather Vest)
DELETE FROM item_template WHERE entry = 84435;
INSERT INTO item_template SET `entry`=84435, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Drenched Leather Vest', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=60, `SellPrice`=12, `InventoryType`=5, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49253 -> 84436 (Slightly Worm-Eaten Hardtack)
DELETE FROM item_template WHERE entry = 84436;
INSERT INTO item_template SET `entry`=84436, `class`=0, `subclass`=5, `SoundOverrideSubclass`=-1, `name`='Slightly Worm-Eaten Hardtack', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=5, `BuyPrice`=25, `SellPrice`=1, `InventoryType`=0, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=20, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='The worms add flavor!', `Material`=0, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49254 -> 84437 (Tarp Collected Dew)
DELETE FROM item_template WHERE entry = 84437;
INSERT INTO item_template SET `entry`=84437, `class`=0, `subclass`=5, `SoundOverrideSubclass`=-1, `name`='Tarp Collected Dew', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=5, `BuyPrice`=25, `SellPrice`=1, `InventoryType`=0, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=5, `RequiredLevel`=1, `maxcount`=0, `stackable`=20, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='The sand keeps the teeth shiny.', `Material`=0, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49257 -> 84438 (Seashell Throwing Axe)
DELETE FROM item_template WHERE entry = 84438;
INSERT INTO item_template SET `entry`=84438, `class`=2, `subclass`=16, `SoundOverrideSubclass`=-1, `name`='Seashell Throwing Axe', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=15, `SellPrice`=3, `InventoryType`=25, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=3, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=2, `dmg_max1`=4, `dmg_type1`=0, `bonding`=0, `description`='Jungle Edition', `Material`=1, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49258 -> 84439 (Light Throwing Tusk)
DELETE FROM item_template WHERE entry = 84439;
INSERT INTO item_template SET `entry`=84439, `class`=2, `subclass`=16, `SoundOverrideSubclass`=-1, `name`='Light Throwing Tusk', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=15, `SellPrice`=3, `InventoryType`=25, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=3, `RequiredLevel`=1, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=1, `dmg_max1`=3, `dmg_type1`=0, `bonding`=0, `description`='Don''t ask how we got them. They didn''t.', `Material`=1, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49259 -> 84440 (Salvaged Chain Armor)
DELETE FROM item_template WHERE entry = 84440;
INSERT INTO item_template SET `entry`=84440, `class`=4, `subclass`=3, `SoundOverrideSubclass`=-1, `name`='Salvaged Chain Armor', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=434, `SellPrice`=86, `InventoryType`=5, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=5, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49260 -> 84441 (Salvaged Chain Belt)
DELETE FROM item_template WHERE entry = 84441;
INSERT INTO item_template SET `entry`=84441, `class`=4, `subclass`=3, `SoundOverrideSubclass`=-1, `name`='Salvaged Chain Belt', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=218, `SellPrice`=43, `InventoryType`=6, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=5, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49261 -> 84442 (Salvaged Chain Boots)
DELETE FROM item_template WHERE entry = 84442;
INSERT INTO item_template SET `entry`=84442, `class`=4, `subclass`=3, `SoundOverrideSubclass`=-1, `name`='Salvaged Chain Boots', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=331, `SellPrice`=66, `InventoryType`=8, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=5, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49262 -> 84443 (Salvaged Chain Bracers)
DELETE FROM item_template WHERE entry = 84443;
INSERT INTO item_template SET `entry`=84443, `class`=4, `subclass`=3, `SoundOverrideSubclass`=-1, `name`='Salvaged Chain Bracers', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=220, `SellPrice`=44, `InventoryType`=9, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=5, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49263 -> 84444 (Salvaged Chain Gloves)
DELETE FROM item_template WHERE entry = 84444;
INSERT INTO item_template SET `entry`=84444, `class`=4, `subclass`=3, `SoundOverrideSubclass`=-1, `name`='Salvaged Chain Gloves', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=221, `SellPrice`=44, `InventoryType`=10, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=5, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49264 -> 84445 (Salvaged Chain Leggings)
DELETE FROM item_template WHERE entry = 84445;
INSERT INTO item_template SET `entry`=84445, `class`=4, `subclass`=3, `SoundOverrideSubclass`=-1, `name`='Salvaged Chain Leggings', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=437, `SellPrice`=87, `InventoryType`=7, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=5, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49265 -> 84446 (Recovered Knit Belt)
DELETE FROM item_template WHERE entry = 84446;
INSERT INTO item_template SET `entry`=84446, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Recovered Knit Belt', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=147, `SellPrice`=29, `InventoryType`=6, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49266 -> 84447 (Recovered Knit Boots)
DELETE FROM item_template WHERE entry = 84447;
INSERT INTO item_template SET `entry`=84447, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Recovered Knit Boots', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=224, `SellPrice`=44, `InventoryType`=8, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49267 -> 84448 (Recovered Knit Bracers)
DELETE FROM item_template WHERE entry = 84448;
INSERT INTO item_template SET `entry`=84448, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Recovered Knit Bracers', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=148, `SellPrice`=29, `InventoryType`=9, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49268 -> 84449 (Recovered Knit Gloves)
DELETE FROM item_template WHERE entry = 84449;
INSERT INTO item_template SET `entry`=84449, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Recovered Knit Gloves', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=150, `SellPrice`=30, `InventoryType`=10, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49269 -> 84450 (Recovered Knit Pants)
DELETE FROM item_template WHERE entry = 84450;
INSERT INTO item_template SET `entry`=84450, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Recovered Knit Pants', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=298, `SellPrice`=59, `InventoryType`=7, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49270 -> 84451 (Recovered Knit Vest)
DELETE FROM item_template WHERE entry = 84451;
INSERT INTO item_template SET `entry`=84451, `class`=4, `subclass`=1, `SoundOverrideSubclass`=-1, `name`='Recovered Knit Vest', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=296, `SellPrice`=59, `InventoryType`=5, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49271 -> 84452 (Water-Stained Leather Belt)
DELETE FROM item_template WHERE entry = 84452;
INSERT INTO item_template SET `entry`=84452, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Water-Stained Leather Belt', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=182, `SellPrice`=36, `InventoryType`=6, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49272 -> 84453 (Water-Stained Leather Boots)
DELETE FROM item_template WHERE entry = 84453;
INSERT INTO item_template SET `entry`=84453, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Water-Stained Leather Boots', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=275, `SellPrice`=55, `InventoryType`=8, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49273 -> 84454 (Water-Stained Leather Bracers)
DELETE FROM item_template WHERE entry = 84454;
INSERT INTO item_template SET `entry`=84454, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Water-Stained Leather Bracers', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=184, `SellPrice`=36, `InventoryType`=9, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49274 -> 84455 (Water-Stained Leather Gloves)
DELETE FROM item_template WHERE entry = 84455;
INSERT INTO item_template SET `entry`=84455, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Water-Stained Leather Gloves', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=184, `SellPrice`=36, `InventoryType`=10, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49275 -> 84456 (Water-Stained Leather Harness)
DELETE FROM item_template WHERE entry = 84456;
INSERT INTO item_template SET `entry`=84456, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Water-Stained Leather Harness', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=371, `SellPrice`=74, `InventoryType`=5, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49276 -> 84457 (Water-Stained Leather Pants)
DELETE FROM item_template WHERE entry = 84457;
INSERT INTO item_template SET `entry`=84457, `class`=4, `subclass`=2, `SoundOverrideSubclass`=-1, `name`='Water-Stained Leather Pants', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=1, `BuyPrice`=372, `SellPrice`=74, `InventoryType`=7, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=10, `RequiredLevel`=5, `maxcount`=0, `stackable`=1, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=8, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49600 -> 84458 (Goblin Shortbread)
DELETE FROM item_template WHERE entry = 84458;
INSERT INTO item_template SET `entry`=84458, `class`=0, `subclass`=5, `SoundOverrideSubclass`=-1, `name`='Goblin Shortbread', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=5, `BuyPrice`=125, `SellPrice`=6, `InventoryType`=0, `AllowableClass`=-1, `AllowableRace`=-1, `ItemLevel`=15, `RequiredLevel`=5, `maxcount`=0, `stackable`=20, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=0, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

-- Cata 49601 -> 84459 (Volcanic Spring Water)
DELETE FROM item_template WHERE entry = 84459;
INSERT INTO item_template SET `entry`=84459, `class`=0, `subclass`=5, `SoundOverrideSubclass`=-1, `name`='Volcanic Spring Water', `displayid`=0, `Quality`=1, `Flags`=0, `FlagsExtra`=0, `BuyCount`=5, `BuyPrice`=125, `SellPrice`=6, `InventoryType`=0, `AllowableClass`=32767, `AllowableRace`=-1, `ItemLevel`=15, `RequiredLevel`=5, `maxcount`=0, `stackable`=20, `ContainerSlots`=0, `stat_type1`=0, `stat_value1`=0, `stat_type2`=0, `stat_value2`=0, `stat_type3`=0, `stat_value3`=0, `stat_type4`=0, `stat_value4`=0, `stat_type5`=0, `stat_value5`=0, `stat_type6`=0, `stat_value6`=0, `stat_type7`=0, `stat_value7`=0, `stat_type8`=0, `stat_value8`=0, `stat_type9`=0, `stat_value9`=0, `stat_type10`=0, `stat_value10`=0, `dmg_min1`=0, `dmg_max1`=0, `dmg_type1`=0, `bonding`=0, `description`='', `Material`=7, `sheath`=0, `BagFamily`=0, `startquest`=0, `RequiredDisenchantSkill`=-1, `duration`=0;

