-- I-246 — strip ported "Quest Invisibility" auras that nothing can ever detect.
--
-- Retail 4.x parks quest props under a `Quest Invisibility <n>` aura
-- (SPELL_AURA_MOD_INVISIBILITY = 18, invisibility TYPE in the misc value) and
-- reveals them with the matching `Quest Invisibility Detect` (aura 19, same
-- type) granted by the quest phase spells — which sit in the unportable 1511xx
-- range (I-274). F-011 ports the hide half only, so the creature is invisible
-- to every player, permanently, and nothing in the 3.3.5a client can detect it:
-- stock has detect spells for invisibility types 0-5, 7-11 and 36, and for
-- NEITHER of the two types below.
--
-- creature_addon.py keeps any aura whose spell exists in the target DBC, so
-- these rows only started shipping once the derived-spell walk ported the
-- spells themselves — 90940 arrived with I-311 (2026-08-06), three weeks after
-- I-246 was verified in-game, which is why a closed quest broke on its own.
-- Fixed at source too (`_undetectable_invisibility` in creature_addon.py); this
-- override carries the live rows until the next full regen and is re-applied by
-- the I-244 cascade after one.
--
-- 37179 Bilgewater Buccaneer  <- 90940 "Quest Invisibility 17"        (type 25)
--   The rideable shredder for 24502 "Necessary Roughness" / 28414 "Fourth and
--   Goal". Riding is gated by the spellclick conditions in
--   zz_[I-246]_necessary_roughness_field.sql, not by invisibility, so the aura
--   buys nothing here and costs the whole quest.
-- 36403 Trade Prince Gallywix <- 81717 "Generic Quest Invisibility 14" (type 22)
--   Same defect, one spawn (11001543) on the Lost Isles.
--
-- Both rows are AUTO-owned (zz_[AUTO,F-011]_11_creature_template_addon.sql)
-- -> one consolidated UPDATE per entry, never a DELETE+INSERT.
UPDATE creature_template_addon SET auras = '' WHERE entry = 37179;
UPDATE creature_template_addon SET auras = '' WHERE entry = 36403;
