-- I-337 — scope the Pygmy Helmet disguise (66987) to the village quest only.
--
-- Reported as "the oomlot are showing friendly". Confirmed from the live character: guid 98
-- carries aura 66987 with amount0 = 4 (REP_FRIENDLY) and maxDuration -1, alongside quest
-- 24901 at status 3 (INCOMPLETE, 15/30 credits).
--
-- This is the disguise working as designed, now that I-337's faction restore gave the Oomlot
-- a template whose faction (1157 Pygmy) a forced reaction can actually match. 66987 is
-- APPLY_AURA 139 FORCE_REACTION, misc 1157, base 3 + die 1 = amount 4 = REP_FRIENDLY, and the
-- donor casts it as the SourceSpell of BOTH 24901 and 24924. On 24924 "Oomlot Village" that is
-- the point — you walk into their village unmolested ("The pygmies will think that you're one
-- of them!"). On 24901 it is self-defeating: the quest wants 30 Oomlot kills from the turret,
-- and a permanently friendly invasion neither fights the town nor reads as hostile.
--
-- Why retail gets away with it: Cata's 66987 has a THIRD effect our port never had —
-- eff2 = APPLY_AURA 23 PERIODIC_TRIGGER_SPELL, period 1000, trigger **83641** (verified in
-- Zeppelin-Tools/wago-cata-classic/SpellEffect.csv). 83641 appears in neither SpellEffect.csv
-- nor Spell.csv, i.e. it is a server/hotfix-side id with no client data at all — the same
-- class of unportable spell as the 1511xx mid-quest phase spells. A once-per-second server
-- ticker on a disguise aura is a state check; the obvious job is dropping the disguise while
-- you are in the town (which is exactly the 24901 window). We cannot reproduce it, so scope
-- the disguise by QUEST instead of by position — here those coincide, because 24901 is the
-- town-defence quest and 24924 is the village quest.
--
-- DELIBERATE DIVERGENCE, documented: 24901 loses the SourceSpell, 24924 keeps it.
-- Alternative considered and rejected: keep the aura on 24901 but drop effect_die_sides_1 to 0
-- so the forced rank is 3 REP_NEUTRAL — the pygmies would then be attackable and show yellow,
-- but they would also ignore the player for the whole town assault, which guts the encounter.
--
-- Row is owned by zz_[AUTO,F-011]_31_quest_template_addon.sql -> consolidated UPDATE here.
UPDATE quest_template_addon SET `SourceSpellID` = 0 WHERE `ID` = 24901;
