-- ============================================================
-- AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
-- Produced by the F-011 Goblin Zone extraction pipeline
-- (Zeppelin-Craft/Scripts/Goblin Zone Port/). Any manual edit
-- here is overwritten the next time the pipeline runs.
--   * To change this output: edit the migration/translation script.
--   * For a one-off manual fix: add a separate zz_[I-xxx]_*.sql file
--     (it loads after these rows and overrides the ones it needs).
-- ============================================================

-- F-011 quest_template_addon (chains, prereqs, provided items)

DELETE FROM quest_template_addon WHERE ID = 14007;
INSERT INTO quest_template_addon SET `ID`=14007, `MaxLevel`=0, `AllowableClasses`=4, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14008;
INSERT INTO quest_template_addon SET `ID`=14008, `MaxLevel`=0, `AllowableClasses`=128, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14009;
INSERT INTO quest_template_addon SET `ID`=14009, `MaxLevel`=0, `AllowableClasses`=16, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14010;
INSERT INTO quest_template_addon SET `ID`=14010, `MaxLevel`=0, `AllowableClasses`=8, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14011;
INSERT INTO quest_template_addon SET `ID`=14011, `MaxLevel`=0, `AllowableClasses`=64, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14012;
INSERT INTO quest_template_addon SET `ID`=14012, `MaxLevel`=0, `AllowableClasses`=256, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14013;
INSERT INTO quest_template_addon SET `ID`=14013, `MaxLevel`=0, `AllowableClasses`=1, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14069;
INSERT INTO quest_template_addon SET `ID`=14069, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14138, `NextQuestID`=0, `ExclusiveGroup`=-14075, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14070;
INSERT INTO quest_template_addon SET `ID`=14070, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14071, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14071;
INSERT INTO quest_template_addon SET `ID`=14071, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=28349, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=1, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14075;
INSERT INTO quest_template_addon SET `ID`=14075, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14138, `NextQuestID`=0, `ExclusiveGroup`=-14075, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14109;
INSERT INTO quest_template_addon SET `ID`=14109, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=26712, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14110;
INSERT INTO quest_template_addon SET `ID`=14110, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=26711, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14113;
INSERT INTO quest_template_addon SET `ID`=14113, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14114;
INSERT INTO quest_template_addon SET `ID`=14114, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14115;
INSERT INTO quest_template_addon SET `ID`=14115, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=78607, `PrevQuestID`=0, `NextQuestID`=14116, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14116;
INSERT INTO quest_template_addon SET `ID`=14116, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14115, `NextQuestID`=14120, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14120;
INSERT INTO quest_template_addon SET `ID`=14120, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14116, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14121;
INSERT INTO quest_template_addon SET `ID`=14121, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14120, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14122;
INSERT INTO quest_template_addon SET `ID`=14122, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14120, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14123;
INSERT INTO quest_template_addon SET `ID`=14123, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14120, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14124;
INSERT INTO quest_template_addon SET `ID`=14124, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14120, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=1, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14125;
INSERT INTO quest_template_addon SET `ID`=14125, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14126;
INSERT INTO quest_template_addon SET `ID`=14126, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14125, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=1, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14137;
INSERT INTO quest_template_addon SET `ID`=14137, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14138;
INSERT INTO quest_template_addon SET `ID`=14138, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=1, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14139;
INSERT INTO quest_template_addon SET `ID`=14139, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14153;
INSERT INTO quest_template_addon SET `ID`=14153, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 14158;
INSERT INTO quest_template_addon SET `ID`=14158, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 24488;
INSERT INTO quest_template_addon SET `ID`=24488, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=24567, `NextQuestID`=24502, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 24502;
INSERT INTO quest_template_addon SET `ID`=24502, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=24488, `NextQuestID`=28414, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 24503;
INSERT INTO quest_template_addon SET `ID`=24503, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 24520;
INSERT INTO quest_template_addon SET `ID`=24520, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=28414, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 24521;
INSERT INTO quest_template_addon SET `ID`=24521, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=24488, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 24567;
INSERT INTO quest_template_addon SET `ID`=24567, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14071, `NextQuestID`=24488, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 25473;
INSERT INTO quest_template_addon SET `ID`=25473, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=28349, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=1, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 25902;
INSERT INTO quest_template_addon SET `ID`=25902, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 26711;
INSERT INTO quest_template_addon SET `ID`=26711, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14071, `NextQuestID`=14110, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 26712;
INSERT INTO quest_template_addon SET `ID`=26712, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14071, `NextQuestID`=14109, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 28349;
INSERT INTO quest_template_addon SET `ID`=28349, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=25473, `NextQuestID`=14071, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 28414;
INSERT INTO quest_template_addon SET `ID`=28414, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=24502, `NextQuestID`=24520, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 28606;
INSERT INTO quest_template_addon SET `ID`=28606, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=0, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=0;
DELETE FROM quest_template_addon WHERE ID = 28607;
INSERT INTO quest_template_addon SET `ID`=28607, `MaxLevel`=0, `AllowableClasses`=0, `SourceSpellID`=0, `PrevQuestID`=14071, `NextQuestID`=0, `ExclusiveGroup`=0, `BreadcrumbForQuestId`=0, `RewardMailTemplateID`=0, `RewardMailDelay`=0, `RequiredSkillID`=0, `RequiredSkillPoints`=0, `RequiredMinRepFaction`=0, `RequiredMaxRepFaction`=0, `RequiredMinRepValue`=0, `RequiredMaxRepValue`=0, `ProvidedItemCount`=0, `SpecialFlags`=1;
