-- ==========================================================================
-- I-359  spawn transforms captured with the in-game editor (F-208)
--
-- Generated by `zep world edits emit` on 2026-09-06 21:41. Idempotent: re-running it
-- restores exactly these values.
--
-- `-- was:` records the value the row held when the edit was made. If a row no
-- longer holds that value, something overwrote the edit — check with
-- `zep world edits diff --task I-359` before trusting this file.
-- ==========================================================================
UPDATE `gameobject` SET
  `rotation2` = 0.675574,   -- was: 0.0000
  `rotation3` = -0.737292   -- was: 1.0000
WHERE `guid` = 6000619;

UPDATE `gameobject` SET
  `rotation2` = 0.608757,   -- was: 0.0000
  `rotation3` = -0.793357   -- was: 1.0000
WHERE `guid` = 6000622;

UPDATE `gameobject` SET
  `rotation2` = 0.999848,   -- was: 0.0000
  `rotation3` = 0.0174455   -- was: 1.0000
WHERE `guid` = 6000621;

UPDATE `gameobject` SET
  `rotation2` = 0.91706,   -- was: 0.0000
  `rotation3` = -0.39875   -- was: 1.0000
WHERE `guid` = 6000620;
