-- F-081 Expanded Disenchanting: flag non-vendor white statless
-- armor/weapons as disenchantable. Items STAY white (core patch 0033
-- lowers the disenchant quality gate to 1-4); the +1 stat and the
-- 'Disenchantable.' description are the player-facing signal.
-- Vendor-sold items are excluded (gold->mats faucet).
-- AUTO-GENERATED by `zep world item purge-whites` — do NOT hand-edit.

-- +1 Agility (1 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 3, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84369);

-- +1 Strength (2 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 4, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84488, 84491);

-- +1 Intellect (5 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 5, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84343, 84347, 84389, 84477, 84485);

-- +1 Spirit (2 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 6, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84383, 84418);

-- +1 Stamina (12 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 7, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84341, 84368, 84370, 84388, 84475, 84480, 84481, 84482, 84483, 84486, 84489, 84490);

-- +1 Hit (1 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 31, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84384);

-- +1 Crit (2 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 32, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84386, 84479);

-- +1 Haste (5 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 36, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84342, 84344, 84387, 84478, 84484);

-- +1 Expertise (2 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 37, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84372, 84382);

-- +1 Attack Power (1 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 38, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84476);

-- +1 Armor Pen (3 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 44, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84371, 84385, 84487);

-- +1 Spell Power (2 items)
UPDATE `item_template` SET `Quality` = 1, `stat_type1` = 45, `stat_value1` = 1, `DisenchantID` = 21, `RequiredDisenchantSkill` = 1 WHERE `entry` IN (84345, 84346);

-- Signal description (skips 1 items with stock flavor text)
UPDATE `item_template` SET `description` = 'Disenchantable.' WHERE `entry` IN (84341, 84342, 84343, 84344, 84345, 84346, 84347, 84368, 84369, 84370, 84371, 84372, 84382, 84383, 84384, 84385, 84386, 84387, 84388, 84389, 84475, 84476, 84477, 84478, 84479, 84480, 84481, 84482, 84483, 84484, 84485, 84486, 84487, 84488, 84489, 84490, 84491);
