-- F-028 Low-Level Relic Slot Drops — creature_loot_template wiring (Phase 3)
-- 52 relic entries (59039-59090) bound to dungeon bosses, 10% chance each.
-- Generated by cli/lib/item/relic_loot_generator.py from data/relic_effects.json.
-- Idempotent: DELETE row for (Entry, Item) before INSERT.

-- Edwin VanCleef (entry 639, Deadmines)
DELETE FROM `creature_loot_template` WHERE `Entry` = 639 AND `Item` = 59040;
INSERT INTO `creature_loot_template` SET `Entry` = 639, `Item` = 59040, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Brackish Tide (F-028 druid relic)';

-- Mr. Smite (entry 646, Deadmines)
DELETE FROM `creature_loot_template` WHERE `Entry` = 646 AND `Item` = 59039;
INSERT INTO `creature_loot_template` SET `Entry` = 646, `Item` = 59039, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Dawn''s Grace (F-028 paladin relic)';

-- Targorr the Dread (entry 1696, Stockades)
DELETE FROM `creature_loot_template` WHERE `Entry` = 1696 AND `Item` = 59047;
INSERT INTO `creature_loot_template` SET `Entry` = 1696, `Item` = 59047, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Justice''s Edge (F-028 paladin relic)';

-- Bazil Thredd (entry 1716, Stockades)
DELETE FROM `creature_loot_template` WHERE `Entry` = 1716 AND `Item` = 59048;
INSERT INTO `creature_loot_template` SET `Entry` = 1716, `Item` = 59048, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Inmate''s Carved Totem (F-028 shaman relic)';

-- Darkmaster Gandling (entry 1853, Scholomance)
DELETE FROM `creature_loot_template` WHERE `Entry` = 1853 AND `Item` = 59090;
INSERT INTO `creature_loot_template` SET `Entry` = 1853, `Item` = 59090, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of Scholar''s Renewal (F-028 druid relic)';

-- Archaedas (entry 2748, Uldaman West)
DELETE FROM `creature_loot_template` WHERE `Entry` = 2748 AND `Item` = 59066;
INSERT INTO `creature_loot_template` SET `Entry` = 2748, `Item` = 59066, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Stone Ursine (F-028 druid relic)';

-- Mutanus the Devourer (entry 3654, Wailing Caverns)
DELETE FROM `creature_loot_template` WHERE `Entry` = 3654 AND `Item` = 59042;
INSERT INTO `creature_loot_template` SET `Entry` = 3654, `Item` = 59042, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Tongue-Lasher Totem (F-028 shaman relic)';

-- Lord Cobrahn (entry 3669, Wailing Caverns)
DELETE FROM `creature_loot_template` WHERE `Entry` = 3669 AND `Item` = 59041;
INSERT INTO `creature_loot_template` SET `Entry` = 3669, `Item` = 59041, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Wailing Grove (F-028 druid relic)';

-- Houndmaster Loksey (entry 3974, SM Library)
DELETE FROM `creature_loot_template` WHERE `Entry` = 3974 AND `Item` = 59055;
INSERT INTO `creature_loot_template` SET `Entry` = 3974, `Item` = 59055, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Scholarly Light (F-028 paladin relic)';

-- Herod (entry 3975, SM Armory)
DELETE FROM `creature_loot_template` WHERE `Entry` = 3975 AND `Item` = 59057;
INSERT INTO `creature_loot_template` SET `Entry` = 3975, `Item` = 59057, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Feral Hunt (F-028 druid relic)';
DELETE FROM `creature_loot_template` WHERE `Entry` = 3975 AND `Item` = 59058;
INSERT INTO `creature_loot_template` SET `Entry` = 3975, `Item` = 59058, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Sudden Wrath (F-028 paladin relic)';

-- Scarlet Commander Mograine (entry 3976, SM Cathedral)
DELETE FROM `creature_loot_template` WHERE `Entry` = 3976 AND `Item` = 59059;
INSERT INTO `creature_loot_template` SET `Entry` = 3976, `Item` = 59059, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Radiant Flash (F-028 paladin relic)';

-- High Inquisitor Whitemane (entry 3977, SM Cathedral)
DELETE FROM `creature_loot_template` WHERE `Entry` = 3977 AND `Item` = 59060;
INSERT INTO `creature_loot_template` SET `Entry` = 3977, `Item` = 59060, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of Cleansing Streams (F-028 shaman relic)';

-- Interrogator Vishas (entry 3983, SM Graveyard)
DELETE FROM `creature_loot_template` WHERE `Entry` = 3983 AND `Item` = 59053;
INSERT INTO `creature_loot_template` SET `Entry` = 3983, `Item` = 59053, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Steadfast Devotion (F-028 paladin relic)';

-- Fenrus the Devourer (entry 4274, Shadowfang Keep)
DELETE FROM `creature_loot_template` WHERE `Entry` = 4274 AND `Item` = 59043;
INSERT INTO `creature_loot_template` SET `Entry` = 4274, `Item` = 59043, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of Lunar Embrace (F-028 druid relic)';

-- Archmage Arugal (entry 4275, Shadowfang Keep)
DELETE FROM `creature_loot_template` WHERE `Entry` = 4275 AND `Item` = 59044;
INSERT INTO `creature_loot_template` SET `Entry` = 4275, `Item` = 59044, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Shadow''s End (F-028 paladin relic)';

-- Charlga Razorflank (entry 4421, Razorfen Kraul)
DELETE FROM `creature_loot_template` WHERE `Entry` = 4421 AND `Item` = 59052;
INSERT INTO `creature_loot_template` SET `Entry` = 4421, `Item` = 59052, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Boar-Tusk Totem (F-028 shaman relic)';

-- Bloodmage Thalnos (entry 4543, SM Graveyard)
DELETE FROM `creature_loot_template` WHERE `Entry` = 4543 AND `Item` = 59054;
INSERT INTO `creature_loot_template` SET `Entry` = 4543, `Item` = 59054, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of Restless Grove (F-028 druid relic)';

-- Aku'mai (entry 4829, Blackfathom Deeps)
DELETE FROM `creature_loot_template` WHERE `Entry` = 4829 AND `Item` = 59046;
INSERT INTO `creature_loot_template` SET `Entry` = 4829, `Item` = 59046, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of Tidesong (F-028 druid relic)';

-- Twilight Lord Kelris (entry 4832, Blackfathom Deeps)
DELETE FROM `creature_loot_template` WHERE `Entry` = 4832 AND `Item` = 59045;
INSERT INTO `creature_loot_template` SET `Entry` = 4832, `Item` = 59045, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Stormcaller''s Stone (F-028 shaman relic)';

-- Earthcaller Halmgar (entry 4842, Razorfen Kraul)
DELETE FROM `creature_loot_template` WHERE `Entry` = 4842 AND `Item` = 59051;
INSERT INTO `creature_loot_template` SET `Entry` = 4842, `Item` = 59051, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of Greenleaf (F-028 druid relic)';

-- Shade of Eranikus (entry 5709, Sunken Temple Upper)
DELETE FROM `creature_loot_template` WHERE `Entry` = 5709 AND `Item` = 59074;
INSERT INTO `creature_loot_template` SET `Entry` = 5709, `Item` = 59074, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of Atal''ai''s Bite (F-028 shaman relic)';

-- Jammal'an the Prophet (entry 5710, Sunken Temple Lower)
DELETE FROM `creature_loot_template` WHERE `Entry` = 5710 AND `Item` = 59072;
INSERT INTO `creature_loot_template` SET `Entry` = 5710, `Item` = 59072, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of the Inner Sanctum (F-028 paladin relic)';

-- Crowd Pummeler 9-60 (entry 6229, Gnomeregan)
DELETE FROM `creature_loot_template` WHERE `Entry` = 6229 AND `Item` = 59049;
INSERT INTO `creature_loot_template` SET `Entry` = 6229, `Item` = 59049, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Searing Totem of Embers (F-028 shaman relic)';

-- Arcanist Doan (entry 6487, SM Library)
DELETE FROM `creature_loot_template` WHERE `Entry` = 6487 AND `Item` = 59056;
INSERT INTO `creature_loot_template` SET `Entry` = 6487, `Item` = 59056, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Forbidden Tome of Tempests (F-028 shaman relic)';

-- Revelosh (entry 6910, Uldaman East)
DELETE FROM `creature_loot_template` WHERE `Entry` = 6910 AND `Item` = 59063;
INSERT INTO `creature_loot_template` SET `Entry` = 6910, `Item` = 59063, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of Buried Stars (F-028 druid relic)';

-- Ironaya (entry 7228, Uldaman East)
DELETE FROM `creature_loot_template` WHERE `Entry` = 7228 AND `Item` = 59064;
INSERT INTO `creature_loot_template` SET `Entry` = 7228, `Item` = 59064, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of the Discsmith (F-028 paladin relic)';

-- Chief Ukorz Sandscalp (entry 7267, Zul'Farrak)
DELETE FROM `creature_loot_template` WHERE `Entry` = 7267 AND `Item` = 59068;
INSERT INTO `creature_loot_template` SET `Entry` = 7267, `Item` = 59068, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of the Trollbane (F-028 paladin relic)';

-- Galgann Firehammer (entry 7291, Uldaman West)
DELETE FROM `creature_loot_template` WHERE `Entry` = 7291 AND `Item` = 59065;
INSERT INTO `creature_loot_template` SET `Entry` = 7291, `Item` = 59065, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of the Earth-Forged (F-028 shaman relic)';

-- Tuten'kash (entry 7355, Razorfen Downs)
DELETE FROM `creature_loot_template` WHERE `Entry` = 7355 AND `Item` = 59061;
INSERT INTO `creature_loot_template` SET `Entry` = 7355, `Item` = 59061, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Tuskcrack Totem (F-028 shaman relic)';

-- Amnennar the Coldbringer (entry 7358, Razorfen Downs)
DELETE FROM `creature_loot_template` WHERE `Entry` = 7358 AND `Item` = 59062;
INSERT INTO `creature_loot_template` SET `Entry` = 7358, `Item` = 59062, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Sleeping Wood (F-028 druid relic)';

-- Hydromancer Velratha (entry 7795, Zul'Farrak)
DELETE FROM `creature_loot_template` WHERE `Entry` = 7795 AND `Item` = 59067;
INSERT INTO `creature_loot_template` SET `Entry` = 7795, `Item` = 59067, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of Forking Bolts (F-028 shaman relic)';

-- Mekgineer Thermaplugg (entry 7800, Gnomeregan)
DELETE FROM `creature_loot_template` WHERE `Entry` = 7800 AND `Item` = 59050;
INSERT INTO `creature_loot_template` SET `Entry` = 7800, `Item` = 59050, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Mechanized Faith (F-028 paladin relic)';

-- Avatar of Hakkar (entry 8443, Sunken Temple Upper)
DELETE FROM `creature_loot_template` WHERE `Entry` = 8443 AND `Item` = 59073;
INSERT INTO `creature_loot_template` SET `Entry` = 8443, `Item` = 59073, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Hakkari Swarm (F-028 druid relic)';

-- Atal'alarion (entry 8580, Sunken Temple Lower)
DELETE FROM `creature_loot_template` WHERE `Entry` = 8580 AND `Item` = 59071;
INSERT INTO `creature_loot_template` SET `Entry` = 8580, `Item` = 59071, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of Restoring Waters (F-028 shaman relic)';

-- Emperor Dagran Thaurissan (entry 9019, Blackrock Depths)
DELETE FROM `creature_loot_template` WHERE `Entry` = 9019 AND `Item` = 59076;
INSERT INTO `creature_loot_template` SET `Entry` = 9019, `Item` = 59076, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Molten Devotion (F-028 paladin relic)';

-- Ambassador Flamelash (entry 9156, Blackrock Depths)
DELETE FROM `creature_loot_template` WHERE `Entry` = 9156 AND `Item` = 59075;
INSERT INTO `creature_loot_template` SET `Entry` = 9156, `Item` = 59075, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Deep Vein (F-028 druid relic)';

-- Overlord Wyrmthalak (entry 9568, Lower Blackrock Spire)
DELETE FROM `creature_loot_template` WHERE `Entry` = 9568 AND `Item` = 59078;
INSERT INTO `creature_loot_template` SET `Entry` = 9568, `Item` = 59078, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of Lava Surge (F-028 shaman relic)';

-- General Drakkisath (entry 10363, Upper Blackrock Spire)
DELETE FROM `creature_loot_template` WHERE `Entry` = 10363 AND `Item` = 59080;
INSERT INTO `creature_loot_template` SET `Entry` = 10363, `Item` = 59080, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Beast Lord (F-028 druid relic)';

-- The Beast (entry 10430, Upper Blackrock Spire)
DELETE FROM `creature_loot_template` WHERE `Entry` = 10430 AND `Item` = 59079;
INSERT INTO `creature_loot_template` SET `Entry` = 10430, `Item` = 59079, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of Drakkisath''s Wrath (F-028 shaman relic)';

-- Baron Rivendare (Undead side) (entry 10440, Stratholme)
DELETE FROM `creature_loot_template` WHERE `Entry` = 10440 AND `Item` = 59088;
INSERT INTO `creature_loot_template` SET `Entry` = 10440, `Item` = 59088, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of the Crusader''s Spire (F-028 paladin relic)';

-- Mother Smolderweb (entry 10596, Lower Blackrock Spire)
DELETE FROM `creature_loot_template` WHERE `Entry` = 10596 AND `Item` = 59077;
INSERT INTO `creature_loot_template` SET `Entry` = 10596, `Item` = 59077, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Righteous Hammer (F-028 paladin relic)';

-- Balnazzar (Live side) (entry 10813, Stratholme)
DELETE FROM `creature_loot_template` WHERE `Entry` = 10813 AND `Item` = 59087;
INSERT INTO `creature_loot_template` SET `Entry` = 10813, `Item` = 59087, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of Erupting Fury (F-028 shaman relic)';

-- Prince Tortheldrin (entry 11486, Dire Maul West)
DELETE FROM `creature_loot_template` WHERE `Entry` = 11486 AND `Item` = 59086;
INSERT INTO `creature_loot_template` SET `Entry` = 11486, `Item` = 59086, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Athenaeum Light (F-028 paladin relic)';

-- Tendris Warpwood (entry 11489, Dire Maul West)
DELETE FROM `creature_loot_template` WHERE `Entry` = 11489 AND `Item` = 59085;
INSERT INTO `creature_loot_template` SET `Entry` = 11489, `Item` = 59085, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Eldreth (F-028 druid relic)';

-- Zevrim Thornhoof (entry 11490, Dire Maul East)
DELETE FROM `creature_loot_template` WHERE `Entry` = 11490 AND `Item` = 59081;
INSERT INTO `creature_loot_template` SET `Entry` = 11490, `Item` = 59081, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of Verdant Renewal (F-028 druid relic)';

-- Alzzin the Wildshaper (entry 11492, Dire Maul East)
DELETE FROM `creature_loot_template` WHERE `Entry` = 11492 AND `Item` = 59082;
INSERT INTO `creature_loot_template` SET `Entry` = 11492, `Item` = 59082, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of the Warpwood (F-028 shaman relic)';

-- King Gordok (entry 11501, Dire Maul North)
DELETE FROM `creature_loot_template` WHERE `Entry` = 11501 AND `Item` = 59084;
INSERT INTO `creature_loot_template` SET `Entry` = 11501, `Item` = 59084, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Totem of Tribal Bonds (F-028 shaman relic)';

-- Rattlegore (entry 11622, Scholomance)
DELETE FROM `creature_loot_template` WHERE `Entry` = 11622 AND `Item` = 59089;
INSERT INTO `creature_loot_template` SET `Entry` = 11622, `Item` = 59089, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of the Shielded Avenger (F-028 paladin relic)';

-- Princess Theradras (entry 12201, Maraudon)
DELETE FROM `creature_loot_template` WHERE `Entry` = 12201 AND `Item` = 59070;
INSERT INTO `creature_loot_template` SET `Entry` = 12201, `Item` = 59070, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of Sacred Ground (F-028 paladin relic)';

-- Noxxion (entry 13282, Maraudon)
DELETE FROM `creature_loot_template` WHERE `Entry` = 13282 AND `Item` = 59069;
INSERT INTO `creature_loot_template` SET `Entry` = 13282, `Item` = 59069, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Idol of the Earthmother (F-028 druid relic)';

-- Guard Fengus (entry 14321, Dire Maul North)
DELETE FROM `creature_loot_template` WHERE `Entry` = 14321 AND `Item` = 59083;
INSERT INTO `creature_loot_template` SET `Entry` = 14321, `Item` = 59083, `Reference` = 0, `Chance` = 10.0, `QuestRequired` = 0, `LootMode` = 1, `GroupId` = 0, `MinCount` = 1, `MaxCount` = 1, `Comment` = 'Libram of the Ogre''s Crest (F-028 paladin relic)';

