-- ============================================================
-- AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
-- Produced by `zep goblin gen` (F-011 translation layer).
-- Any manual edit here is overwritten the next time gen runs.
--   * To change this output: edit the gen emitter or a fixture.
--   * For a one-off manual fix: add a separate zz_[I-xxx]_*.sql file
--     (it loads after these rows and overrides the ones it needs).
-- ============================================================

-- F-011 fallback creature models (retroported, minimal 3.3.5a rows)

DELETE FROM creaturemodeldata WHERE id=24;
INSERT INTO creaturemodeldata (id,flags,model_path,size_class,model_scale,blood_id,footprint_texture_id,footprint_texture_length,footprint_texture_width,footprint_particle_scale,foley_material_id,footstep_shake_size,death_thud_shake_size,sound_data,collision_width,collision_height,mount_height,geo_box_min_x,geo_box_min_y,geo_box_min_z,geo_box_max_x,geo_box_max_y,geo_box_max_z,world_effect_scale,attached_effect_scale,missile_collision_radius,missile_collision_push,missile_collision_raise) VALUES (24,0,'CREATURE\\INFERNAL\\INFERNAL.M2',1,1.0,0,0,0,0,0,0,0,0,0,1.0,2.5,0,-1,-1,-1,1,1,2,1.0,1.0,0,0,0);
DELETE FROM creaturemodeldata WHERE id=1731;
INSERT INTO creaturemodeldata (id,flags,model_path,size_class,model_scale,blood_id,footprint_texture_id,footprint_texture_length,footprint_texture_width,footprint_particle_scale,foley_material_id,footstep_shake_size,death_thud_shake_size,sound_data,collision_width,collision_height,mount_height,geo_box_min_x,geo_box_min_y,geo_box_min_z,geo_box_max_x,geo_box_max_y,geo_box_max_z,world_effect_scale,attached_effect_scale,missile_collision_radius,missile_collision_push,missile_collision_raise) VALUES (1731,0,'CREATURE\\INVISIBLESTALKER\\INVISIBLESTALKER.M2',1,1.0,0,0,0,0,0,0,0,0,0,1.0,2.5,0,-1,-1,-1,1,1,2,1.0,1.0,0,0,0);
DELETE FROM creaturemodeldata WHERE id=2293;
INSERT INTO creaturemodeldata (id,flags,model_path,size_class,model_scale,blood_id,footprint_texture_id,footprint_texture_length,footprint_texture_width,footprint_particle_scale,foley_material_id,footstep_shake_size,death_thud_shake_size,sound_data,collision_width,collision_height,mount_height,geo_box_min_x,geo_box_min_y,geo_box_min_z,geo_box_max_x,geo_box_max_y,geo_box_max_z,world_effect_scale,attached_effect_scale,missile_collision_radius,missile_collision_push,missile_collision_raise) VALUES (2293,0,'CREATURE\\RAPTOROUTLAND\\RAPTOR_OUTLAND.M2',1,1.0,0,0,0,0,0,0,0,0,0,1.0,2.5,0,-1,-1,-1,1,1,2,1.0,1.0,0,0,0);
DELETE FROM creaturemodeldata WHERE id=2613;
INSERT INTO creaturemodeldata (id,flags,model_path,size_class,model_scale,blood_id,footprint_texture_id,footprint_texture_length,footprint_texture_width,footprint_particle_scale,foley_material_id,footstep_shake_size,death_thud_shake_size,sound_data,collision_width,collision_height,mount_height,geo_box_min_x,geo_box_min_y,geo_box_min_z,geo_box_max_x,geo_box_max_y,geo_box_max_z,world_effect_scale,attached_effect_scale,missile_collision_radius,missile_collision_push,missile_collision_raise) VALUES (2613,0,'CHARACTER\\FORESTTROLL\\MALE\\FORESTTROLLMALE.M2',1,1.0,0,0,0,0,0,0,0,0,0,1.0,2.5,0,-1,-1,-1,1,1,2,1.0,1.0,0,0,0);
DELETE FROM creaturemodeldata WHERE id=2701;
INSERT INTO creaturemodeldata (id,flags,model_path,size_class,model_scale,blood_id,footprint_texture_id,footprint_texture_length,footprint_texture_width,footprint_particle_scale,foley_material_id,footstep_shake_size,death_thud_shake_size,sound_data,collision_width,collision_height,mount_height,geo_box_min_x,geo_box_min_y,geo_box_min_z,geo_box_max_x,geo_box_max_y,geo_box_max_z,world_effect_scale,attached_effect_scale,missile_collision_radius,missile_collision_push,missile_collision_raise) VALUES (2701,0,'CREATURE\\FLYINGBOMBER\\FLYINGBOMBER.M2',1,1.0,0,0,0,0,0,0,0,0,0,1.0,2.5,0,-1,-1,-1,1,1,2,1.0,1.0,0,0,0);
DELETE FROM creaturemodeldata WHERE id=3183;
INSERT INTO creaturemodeldata (id,flags,model_path,size_class,model_scale,blood_id,footprint_texture_id,footprint_texture_length,footprint_texture_width,footprint_particle_scale,foley_material_id,footstep_shake_size,death_thud_shake_size,sound_data,collision_width,collision_height,mount_height,geo_box_min_x,geo_box_min_y,geo_box_min_z,geo_box_max_x,geo_box_max_y,geo_box_max_z,world_effect_scale,attached_effect_scale,missile_collision_radius,missile_collision_push,missile_collision_raise) VALUES (3183,0,'CREATURE\\YOGGSARON\\YOGGSARONTENTACLETHIN.M2',1,1.0,0,0,0,0,0,0,0,0,0,1.0,2.5,0,-1,-1,-1,1,1,2,1.0,1.0,0,0,0);
DELETE FROM creaturemodeldata WHERE id=3338;
INSERT INTO creaturemodeldata (id,flags,model_path,size_class,model_scale,blood_id,footprint_texture_id,footprint_texture_length,footprint_texture_width,footprint_particle_scale,foley_material_id,footstep_shake_size,death_thud_shake_size,sound_data,collision_width,collision_height,mount_height,geo_box_min_x,geo_box_min_y,geo_box_min_z,geo_box_max_x,geo_box_max_y,geo_box_max_z,world_effect_scale,attached_effect_scale,missile_collision_radius,missile_collision_push,missile_collision_raise) VALUES (3338,0,'CREATURE\\GOBLIN\\GOBLINSHREDDER_LOW.M2',1,1.0,0,0,0,0,0,0,0,0,0,1.0,2.5,0,-1,-1,-1,1,1,2,1.0,1.0,0,0,0);
DELETE FROM creaturemodeldata WHERE id=3543;
INSERT INTO creaturemodeldata (id,flags,model_path,size_class,model_scale,blood_id,footprint_texture_id,footprint_texture_length,footprint_texture_width,footprint_particle_scale,foley_material_id,footstep_shake_size,death_thud_shake_size,sound_data,collision_width,collision_height,mount_height,geo_box_min_x,geo_box_min_y,geo_box_min_z,geo_box_max_x,geo_box_max_y,geo_box_max_z,world_effect_scale,attached_effect_scale,missile_collision_radius,missile_collision_push,missile_collision_raise) VALUES (3543,0,'CREATURE\\YOGGSARON\\CATACLYSM_TENTACLE.M2',1,1.0,0,0,0,0,0,0,0,0,0,1.0,2.5,0,-1,-1,-1,1,1,2,1.0,1.0,0,0,0);
