-- ============================================================
-- AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
-- Produced by the F-011 Goblin Zone extraction pipeline
-- (Zeppelin-Craft/Scripts/Goblin Zone Port/). Any manual edit
-- here is overwritten the next time the pipeline runs.
--   * To change this output: edit the migration/translation script.
--   * For a one-off manual fix: add a separate zz_[I-xxx]_*.sql file
--     (it loads after these rows and overrides the ones it needs).
-- ============================================================

-- F-011 Cata-new quest-item spells ported from Whitemane 4.3.4 (name/desc/effects/school real; cast/range defaulted)

-- 56576 Wild Clucker Eggs
DELETE FROM spell WHERE id=56576;
INSERT INTO spell SET `id`=56576, `attributes`=0, `attributes_ex_1`=0, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=327, `spell_icon_id`=3329, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Wild Clucker Eggs', `spell_desc_enus`='Place in a Raptor Trap.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=28, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=1, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=38195, `effect_misc_value_b_1`=61, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=46, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 66393 Rolling with my Homies: Summon Hot Rod
DELETE FROM spell WHERE id=66393;
INSERT INTO spell SET `id`=66393, `attributes`=268435712, `attributes_ex_1`=1024, `attributes_ex_2`=4, `attributes_ex_3`=0, `attributes_ex_4`=128, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=17398, `spell_icon_id`=1, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Rolling with my Homies: Summon Hot Rod', `spell_desc_enus`='Get in your hot rod!', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=28, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=66392, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=34840, `effect_misc_value_b_1`=827, `effect_radius_index_1`=36, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=73, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=90, `effect_apply_aura_name_2`=0, `effect_amplitude_2`=0, `effect_base_points_2`=1, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=48323, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=1, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0;

-- 66987 Pygmy Helmet
DELETE FROM spell WHERE id=66987;
INSERT INTO spell SET `id`=66987, `attributes`=2835349760, `attributes_ex_1`=3104, `attributes_ex_2`=273170436, `attributes_ex_3`=268632576, `attributes_ex_4`=8388800, `attributes_ex_5`=393224, `attributes_ex_6`=4608, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=17539, `spell_icon_id`=4483, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Pygmy Helmet', `spell_desc_enus`='The pygmies will think that you''re one of them!', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=6, `effect_apply_aura_name_1`=139, `effect_amplitude_1`=0, `effect_base_points_1`=3, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=1157, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=16, `effect_apply_aura_name_2`=0, `effect_amplitude_2`=0, `effect_base_points_2`=0, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=26902, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=1, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0, `effect_3`=6, `effect_apply_aura_name_3`=23, `effect_amplitude_3`=1000, `effect_base_points_3`=0, `effect_die_sides_3`=1, `effect_mechanic_3`=0, `effect_misc_value_a_3`=0, `effect_misc_value_b_3`=0, `effect_radius_index_3`=0, `effect_trigger_spell_3`=0, `effect_implicit_target_a_3`=1, `effect_implicit_target_b_3`=0, `effect_spell_class_mask_a_3`=0, `effect_spell_class_mask_b_3`=0, `effect_spell_class_mask_c_3`=0;

-- 67682 Kablooey Bombs
DELETE FROM spell WHERE id=67682;
INSERT INTO spell SET `id`=67682, `attributes`=0, `attributes_ex_1`=0, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=20.0, `spell_visual_1`=14307, `spell_icon_id`=1696, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Kablooey Bombs', `spell_desc_enus`='Toss the Kablooey Bomb up to $r yards to blow a Kaja''mite Deposit to smithereens.  Then all you have to do is pick up the remaining chunks.  While you''re at it, you can use the Kablooey Bombs to stun those unruly Rebellious Trolls!', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `max_affected_targets`=2, `maximum_target_level`=0, `target_creature_type`=0, `targets`=64, `effect_1`=86, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=8, `effect_misc_value_b_1`=0, `effect_radius_index_1`=8, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=52, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=3, `effect_apply_aura_name_2`=0, `effect_amplitude_2`=0, `effect_base_points_2`=0, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=0, `effect_misc_value_b_2`=0, `effect_radius_index_2`=8, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=16, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0;

-- 67917 Nitro-Potassium Bananas
DELETE FROM spell WHERE id=67917;
INSERT INTO spell SET `id`=67917, `attributes`=16777216, `attributes_ex_1`=1056, `attributes_ex_2`=16448, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=393224, `attributes_ex_6`=4096, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=20.0, `spell_visual_1`=14351, `spell_icon_id`=4029, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Nitro-Potassium Bananas', `spell_desc_enus`='Throw a bunch of Nitro-Potassium Bananas at the targeted Bomb-Throwing Monkey within $r yards. Marvel at goblin ingenuity when the monkey eats the banana!', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=77, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=25, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 68211 Weed Whacker
DELETE FROM spell WHERE id=68211;
INSERT INTO spell SET `id`=68211, `attributes`=0, `attributes_ex_1`=0, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=0, `spell_icon_id`=83, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Weed Whacker', `spell_desc_enus`='Activate to go into Weed Whacker mode.  Mow those plants down!  Use again to turn Weed Whacker mode off.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=3, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 68280 KTC Snapflash
DELETE FROM spell WHERE id=68280;
INSERT INTO spell SET `id`=68280, `attributes`=256, `attributes_ex_1`=1024, `attributes_ex_2`=4, `attributes_ex_3`=268435456, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=0, `spell_icon_id`=3792, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='KTC Snapflash', `spell_desc_enus`='Point your belt-mounted KTC Snapflash at the target and capture a pretty image.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `max_affected_targets`=1, `maximum_target_level`=0, `target_creature_type`=0, `targets`=0, `effect_1`=3, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=22, `effect_implicit_target_b_1`=7, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 69303 Infrared Heat Focals
DELETE FROM spell WHERE id=69303;
INSERT INTO spell SET `id`=69303, `attributes`=2147483904, `attributes_ex_1`=268435456, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=4224, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=14638, `spell_icon_id`=4032, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Infrared Heat Focals', `spell_desc_enus`='See and track the heat signatures of the SI:7 Assassins out in the jungle.  Spot them before they spot you!', `spell_level`=5, `base_level`=5, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=6, `effect_apply_aura_name_1`=19, `effect_amplitude_1`=0, `effect_base_points_1`=1, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=8, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=6, `effect_apply_aura_name_2`=170, `effect_amplitude_2`=0, `effect_base_points_2`=0, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=3, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=1, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0, `effect_3`=6, `effect_apply_aura_name_3`=284, `effect_amplitude_3`=0, `effect_base_points_3`=0, `effect_die_sides_3`=1, `effect_mechanic_3`=0, `effect_misc_value_a_3`=623, `effect_misc_value_b_3`=0, `effect_radius_index_3`=0, `effect_trigger_spell_3`=0, `effect_implicit_target_a_3`=1, `effect_implicit_target_b_3`=0, `effect_spell_class_mask_a_3`=0, `effect_spell_class_mask_b_3`=0, `effect_spell_class_mask_c_3`=0;

-- 70478 Kaja'Cola
DELETE FROM spell WHERE id=70478;
INSERT INTO spell SET `id`=70478, `attributes`=134217984, `attributes_ex_1`=268435456, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=1048640, `attributes_ex_5`=0, `attributes_ex_6`=5120, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=14885, `spell_icon_id`=2902, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Kaja''Cola', `spell_desc_enus`='Kaja''Cola! It gives you IDEAS! (TM)', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `category`=0, `dispel`=0, `mechanic`=0, `prevention_type`=1, `effect_1`=6, `effect_apply_aura_name_1`=4, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 71170 Remote Control Fireworks
DELETE FROM spell WHERE id=71170;
INSERT INTO spell SET `id`=71170, `attributes`=538968064, `attributes_ex_1`=1160, `attributes_ex_2`=335544324, `attributes_ex_3`=197184, `attributes_ex_4`=8390656, `attributes_ex_5`=8388608, `attributes_ex_6`=0, `attributes_ex_7`=58720256, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=18167, `spell_icon_id`=2368, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Remote Control Fireworks', `spell_desc_enus`='Attach the remote control fireworks to the wild clucker.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=3, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=25, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 71914 Irresistible Pool Pony
DELETE FROM spell WHERE id=71914;
INSERT INTO spell SET `id`=71914, `attributes`=671088640, `attributes_ex_1`=3104, `attributes_ex_2`=272646144, `attributes_ex_3`=268632576, `attributes_ex_4`=8392768, `attributes_ex_5`=393224, `attributes_ex_6`=512, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=15198, `spell_icon_id`=1176, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Irresistible Pool Pony', `spell_desc_enus`='Inflate and ride an Irresistible Pool Pony.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=6, `effect_apply_aura_name_1`=82, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=6, `effect_apply_aura_name_2`=58, `effect_amplitude_2`=0, `effect_base_points_2`=100, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=0, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=1, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0;

-- 72652 Body And Soul: Yngwie's Body - Master
DELETE FROM spell WHERE id=72652;
INSERT INTO spell SET `id`=72652, `attributes`=159383936, `attributes_ex_1`=32, `attributes_ex_2`=16385, `attributes_ex_3`=1048576, `attributes_ex_4`=1048768, `attributes_ex_5`=393224, `attributes_ex_6`=4096, `attributes_ex_7`=4, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=0, `spell_icon_id`=1, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Body And Soul: Yngwie''s Body - Master', `spell_desc_enus`='', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=6, `effect_apply_aura_name_1`=226, `effect_amplitude_1`=1000, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 72891 Super Booster Rocket Boots
DELETE FROM spell WHERE id=72891;
INSERT INTO spell SET `id`=72891, `attributes`=262144, `attributes_ex_1`=0, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=0, `spell_icon_id`=1, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Super Booster Rocket Boots', `spell_desc_enus`='Fire up your Super Booster Rocket Boots and start burning down some goblin zombies!', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=77, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 72971 Rockin' Powder Infused Rocket Boots
DELETE FROM spell WHERE id=72971;
INSERT INTO spell SET `id`=72971, `attributes`=0, `attributes_ex_1`=0, `attributes_ex_2`=4, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=65536, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=15397, `spell_icon_id`=1963, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Rockin'' Powder Infused Rocket Boots', `spell_desc_enus`='Jump into the volcano''s caldera and deliver the boots to Hobart Grapplehammer. Good for one trip.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=42, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=2000, `effect_misc_value_b_1`=3000, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=17, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=6, `effect_apply_aura_name_2`=60, `effect_amplitude_2`=0, `effect_base_points_2`=0, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=0, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=1, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0, `effect_3`=90, `effect_apply_aura_name_3`=0, `effect_amplitude_3`=0, `effect_base_points_3`=1, `effect_die_sides_3`=1, `effect_mechanic_3`=0, `effect_misc_value_a_3`=38842, `effect_misc_value_b_3`=0, `effect_radius_index_3`=0, `effect_trigger_spell_3`=0, `effect_implicit_target_a_3`=1, `effect_implicit_target_b_3`=0, `effect_spell_class_mask_a_3`=0, `effect_spell_class_mask_b_3`=0, `effect_spell_class_mask_c_3`=0;

-- 73066 Bootzooka
DELETE FROM spell WHERE id=73066;
INSERT INTO spell SET `id`=73066, `attributes`=0, `attributes_ex_1`=0, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=40.0, `spell_visual_1`=15413, `spell_icon_id`=3207, `active_icon_id`=0, `school_mask`=4, `spell_name_enus`='Bootzooka', `spell_desc_enus`='Target Volcanoth and fire! Does $s1 Fire damage and the range is $r yards. Some splash damage to the cavern and the volcano''s interior may occur. Use at your own risk!', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=0, `category`=0, `dispel`=0, `mechanic`=0, `prevention_type`=0, `category_recovery_time`=0, `recovery_time`=0, `start_recovery_time`=1500, `effect_1`=2, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=524, `effect_die_sides_1`=151, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=6, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 73417 Satchel of Grenades
DELETE FROM spell WHERE id=73417;
INSERT INTO spell SET `id`=73417, `attributes`=0, `attributes_ex_1`=0, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=15.0, `spell_visual_1`=15463, `spell_icon_id`=3140, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Satchel of Grenades', `spell_desc_enus`='Throw at a Land Mine to set it off. They''re not powerful enough to be good for much more.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=0, `category`=0, `dispel`=0, `mechanic`=0, `prevention_type`=0, `max_affected_targets`=0, `maximum_target_level`=0, `target_creature_type`=0, `targets`=64, `effect_1`=32, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=8, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=52, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 73583 Kaja'Cola Zero-One
DELETE FROM spell WHERE id=73583;
INSERT INTO spell SET `id`=73583, `attributes`=0, `attributes_ex_1`=0, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=8.0, `spell_visual_1`=15509, `spell_icon_id`=2902, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Kaja''Cola Zero-One', `spell_desc_enus`='New & Improved Kaja''Cola Zero-One! Half the Calories, Twice the IDEAS! (TM).  Throw at Ace, Izzy, Gobber, Goblin Survivors, or Kezan Citizens to free their minds. Range is $r yards.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=3, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=25, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 73702 Blastshadow's Soulstone
DELETE FROM spell WHERE id=73702;
INSERT INTO spell SET `id`=73702, `attributes`=0, `attributes_ex_1`=0, `attributes_ex_2`=1, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=15.0, `spell_visual_1`=15525, `spell_icon_id`=1, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Blastshadow''s Soulstone', `spell_desc_enus`='Target Blastshadow the Brutemaster''s corpse and throw the soulstone to destroy it and his chance at a soulstone resurrection. Range is $r yards.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=3, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=25, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 73899 Primal Strike
DELETE FROM spell WHERE id=73899;
INSERT INTO spell SET `id`=73899, `attributes`=327680, `attributes_ex_1`=512, `attributes_ex_2`=0, `attributes_ex_3`=1024, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=39, `spell_icon_id`=4615, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Primal Strike', `spell_desc_enus`='An instant weapon strike that causes $m1 additional damage.', `spell_level`=3, `base_level`=3, `max_level`=0, `proc_chance`=101, `equipped_item_class`=2, `damage_class`=2, `category`=1254, `dispel`=0, `mechanic`=0, `prevention_type`=2, `category_recovery_time`=8000, `recovery_time`=0, `start_recovery_time`=1500, `spell_class_set`=11, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=131072, `equipped_item_inventorytype_mask`=0, `equipped_item_subclass_mask`=173555, `effect_1`=58, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=10, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=6, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 74028 Rockin' Powder Infused Rocket Boots
DELETE FROM spell WHERE id=74028;
INSERT INTO spell SET `id`=74028, `attributes`=0, `attributes_ex_1`=0, `attributes_ex_2`=4, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=65536, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=15397, `spell_icon_id`=1963, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Rockin'' Powder Infused Rocket Boots', `spell_desc_enus`='Jump to the Gallywix Docks.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=42, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=1500, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=200, `effect_misc_value_b_1`=200, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=17, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=6, `effect_apply_aura_name_2`=60, `effect_amplitude_2`=0, `effect_base_points_2`=0, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=0, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=1, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0;

-- 78607 ... It Will Come: Ground Rumble Earthquake
DELETE FROM spell WHERE id=78607;
INSERT INTO spell SET `id`=78607, `attributes`=696254848, `attributes_ex_1`=3104, `attributes_ex_2`=273170437, `attributes_ex_3`=269681152, `attributes_ex_4`=8388800, `attributes_ex_5`=393224, `attributes_ex_6`=4608, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=20129, `spell_icon_id`=1, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='... It Will Come: Ground Rumble Earthquake', `spell_desc_enus`='', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=3, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=0, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=22, `effect_implicit_target_b_1`=30, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 78990 Restore Mana
DELETE FROM spell WHERE id=78990;
INSERT INTO spell SET `id`=78990, `attributes`=134217728, `attributes_ex_1`=0, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=147, `spell_icon_id`=5359, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Restore Mana', `spell_desc_enus`='Restores $s1 mana.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=0, `category`=4, `dispel`=0, `mechanic`=0, `prevention_type`=0, `category_recovery_time`=60000, `recovery_time`=0, `start_recovery_time`=0, `spell_class_set`=13, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=0, `effect_1`=30, `effect_apply_aura_name_1`=0, `effect_amplitude_1`=0, `effect_base_points_1`=9249, `effect_die_sides_1`=1501, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 78993 Concentration
DELETE FROM spell WHERE id=78993;
INSERT INTO spell SET `id`=78993, `attributes`=68222976, `attributes_ex_1`=262208, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=3859, `spell_icon_id`=5238, `active_icon_id`=0, `school_mask`=32, `spell_name_enus`='Concentration', `spell_desc_enus`='Puts the imbiber in an elevated state of concentration where they can restore up to ${$M2*10} mana over $d, but they are defenseless until their concentration is broken.', `spell_level`=55, `base_level`=55, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `spell_class_set`=13, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=0, `effect_2`=6, `effect_apply_aura_name_2`=24, `effect_amplitude_2`=1000, `effect_base_points_2`=1799, `effect_die_sides_2`=401, `effect_mechanic_2`=0, `effect_misc_value_a_2`=0, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=1, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0;

-- 79469 Flask of Steelskin
DELETE FROM spell WHERE id=79469;
INSERT INTO spell SET `id`=79469, `attributes`=671088640, `attributes_ex_1`=0, `attributes_ex_2`=1, `attributes_ex_3`=1048576, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=147, `spell_icon_id`=5246, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Flask of Steelskin', `spell_desc_enus`='Increases Stamina by $s1 for $d. Counts as both a Battle and Guardian elixir.  This effect persists through death.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `spell_class_set`=13, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=0, `effect_1`=6, `effect_apply_aura_name_1`=29, `effect_amplitude_1`=0, `effect_base_points_1`=450, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=2, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 79470 Flask of the Draconic Mind
DELETE FROM spell WHERE id=79470;
INSERT INTO spell SET `id`=79470, `attributes`=671088640, `attributes_ex_1`=0, `attributes_ex_2`=1, `attributes_ex_3`=1048576, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=4, `speed`=0.0, `spell_visual_1`=633, `spell_icon_id`=5249, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Flask of the Draconic Mind', `spell_desc_enus`='Increases Intellect by $s1 for $d. Counts as both a Battle and Guardian elixir.  This effect persists through death.', `spell_level`=46, `base_level`=46, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=0, `category`=99, `dispel`=0, `mechanic`=0, `prevention_type`=0, `category_recovery_time`=1000, `recovery_time`=0, `start_recovery_time`=0, `spell_class_set`=13, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=0, `effect_1`=6, `effect_apply_aura_name_1`=29, `effect_amplitude_1`=0, `effect_base_points_1`=300, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=3, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=3, `effect_apply_aura_name_2`=0, `effect_amplitude_2`=0, `effect_base_points_2`=0, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=0, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=0, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0;

-- 79471 Flask of the Winds
DELETE FROM spell WHERE id=79471;
INSERT INTO spell SET `id`=79471, `attributes`=671088640, `attributes_ex_1`=0, `attributes_ex_2`=1, `attributes_ex_3`=1048576, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=4, `speed`=0.0, `spell_visual_1`=147, `spell_icon_id`=5247, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Flask of the Winds', `spell_desc_enus`='Increases Agility by $s1 for $d. Counts as both a Battle and Guardian elixir.  This effect persists through death.', `spell_level`=15, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `spell_class_set`=13, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=0, `effect_1`=6, `effect_apply_aura_name_1`=29, `effect_amplitude_1`=0, `effect_base_points_1`=300, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=1, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=3, `effect_apply_aura_name_2`=0, `effect_amplitude_2`=0, `effect_base_points_2`=0, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=0, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=0, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0;

-- 79472 Flask of Titanic Strength
DELETE FROM spell WHERE id=79472;
INSERT INTO spell SET `id`=79472, `attributes`=671088640, `attributes_ex_1`=0, `attributes_ex_2`=1, `attributes_ex_3`=1048576, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=4, `speed`=0.0, `spell_visual_1`=147, `spell_icon_id`=5248, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Flask of Titanic Strength', `spell_desc_enus`='Increases Strength by $s1 for $d. Counts as both a Battle and Guardian elixir.  This effect persists through death.', `spell_level`=15, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `spell_class_set`=13, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=0, `effect_1`=6, `effect_apply_aura_name_1`=29, `effect_amplitude_1`=0, `effect_base_points_1`=300, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=3, `effect_apply_aura_name_2`=0, `effect_amplitude_2`=0, `effect_base_points_2`=0, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=0, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=0, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0;

-- 79476 Volcanic Power
DELETE FROM spell WHERE id=79476;
INSERT INTO spell SET `id`=79476, `attributes`=0, `attributes_ex_1`=1024, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=633, `spell_icon_id`=5242, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Volcanic Power', `spell_desc_enus`='Increases Intellect by $s1 for $d.', `spell_level`=0, `base_level`=0, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `category`=24, `dispel`=0, `mechanic`=0, `prevention_type`=0, `category_recovery_time`=60000, `recovery_time`=0, `start_recovery_time`=0, `spell_class_set`=13, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=0, `effect_1`=6, `effect_apply_aura_name_1`=29, `effect_amplitude_1`=0, `effect_base_points_1`=1200, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=3, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 79633 Tol'vir Agility
DELETE FROM spell WHERE id=79633;
INSERT INTO spell SET `id`=79633, `attributes`=671088640, `attributes_ex_1`=1024, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=633, `spell_icon_id`=5243, `active_icon_id`=0, `school_mask`=16, `spell_name_enus`='Tol''vir Agility', `spell_desc_enus`='Increases your Agility by $s1 for $d.', `spell_level`=45, `base_level`=45, `max_level`=45, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `category`=99, `dispel`=0, `mechanic`=0, `prevention_type`=0, `category_recovery_time`=1000, `recovery_time`=0, `start_recovery_time`=0, `spell_class_set`=13, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=0, `effect_1`=6, `effect_apply_aura_name_1`=29, `effect_amplitude_1`=0, `effect_base_points_1`=1200, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=1, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 79634 Golem's Strength
DELETE FROM spell WHERE id=79634;
INSERT INTO spell SET `id`=79634, `attributes`=671088640, `attributes_ex_1`=1024, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=633, `spell_icon_id`=5240, `active_icon_id`=0, `school_mask`=16, `spell_name_enus`='Golem''s Strength', `spell_desc_enus`='Increases your Strength by $s1 for $d.', `spell_level`=80, `base_level`=80, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `category`=99, `dispel`=0, `mechanic`=0, `prevention_type`=0, `category_recovery_time`=1000, `recovery_time`=0, `start_recovery_time`=0, `spell_class_set`=13, `spell_class_mask_1`=0, `spell_class_mask_2`=0, `spell_class_mask_3`=0, `effect_1`=6, `effect_apply_aura_name_1`=29, `effect_amplitude_1`=0, `effect_base_points_1`=1200, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0;

-- 87604 Food
DELETE FROM spell WHERE id=87604;
INSERT INTO spell SET `id`=87604, `attributes`=402653440, `attributes_ex_1`=0, `attributes_ex_2`=0, `attributes_ex_3`=0, `attributes_ex_4`=0, `attributes_ex_5`=0, `attributes_ex_6`=0, `attributes_ex_7`=0, `cast_time_index`=1, `duration_index`=0, `range_index`=13, `power_type`=0, `speed`=0.0, `spell_visual_1`=51, `spell_icon_id`=358, `active_icon_id`=0, `school_mask`=1, `spell_name_enus`='Food', `spell_desc_enus`='Restores $o1 health and ${$87959m2/5*30} mana over $d.  Must remain seated while eating.  If you spend at least 10 seconds eating you will become well fed and gain $87545s2 Stamina and $87545s1 in another useful stat for $87545d.', `spell_level`=0, `base_level`=80, `max_level`=0, `proc_chance`=101, `equipped_item_class`=-1, `damage_class`=1, `effect_1`=6, `effect_apply_aura_name_1`=84, `effect_amplitude_1`=0, `effect_base_points_1`=16000, `effect_die_sides_1`=1, `effect_mechanic_1`=0, `effect_misc_value_a_1`=0, `effect_misc_value_b_1`=0, `effect_radius_index_1`=0, `effect_trigger_spell_1`=0, `effect_implicit_target_a_1`=1, `effect_implicit_target_b_1`=0, `effect_spell_class_mask_a_1`=0, `effect_spell_class_mask_b_1`=0, `effect_spell_class_mask_c_1`=0, `effect_2`=6, `effect_apply_aura_name_2`=23, `effect_amplitude_2`=10000, `effect_base_points_2`=1, `effect_die_sides_2`=1, `effect_mechanic_2`=0, `effect_misc_value_a_2`=0, `effect_misc_value_b_2`=0, `effect_radius_index_2`=0, `effect_trigger_spell_2`=0, `effect_implicit_target_a_2`=1, `effect_implicit_target_b_2`=0, `effect_spell_class_mask_a_2`=0, `effect_spell_class_mask_b_2`=0, `effect_spell_class_mask_c_2`=0, `effect_3`=157, `effect_apply_aura_name_3`=0, `effect_amplitude_3`=0, `effect_base_points_3`=1, `effect_die_sides_3`=1, `effect_mechanic_3`=0, `effect_misc_value_a_3`=33403, `effect_misc_value_b_3`=0, `effect_radius_index_3`=0, `effect_trigger_spell_3`=0, `effect_implicit_target_a_3`=1, `effect_implicit_target_b_3`=0, `effect_spell_class_mask_a_3`=0, `effect_spell_class_mask_b_3`=0, `effect_spell_class_mask_c_3`=0;

