-- Heroic Reference Loot Template
   DELETE FROM `reference_loot_template` WHERE (`Entry` = 9100400);

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901320,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Profitable Faceguard';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901321,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Styling Slicer';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901322,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Silent Claw';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901323,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Shawl of Sensing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901324,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Shaped Pauldrons of Disappointing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901325,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Systematic Cowl of Shipping';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901326,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Racial Vestments of Frightening';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901327,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Cord of Chairing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901328,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Kilt of Forming';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901329,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Slippers of Accusing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901330,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Supportive Cuffs of Defending';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901331,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Speedy Handguards';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901332,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Gifting Shroud';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901333,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Romantic Crown';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901334,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Mantle of Guiding';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901335,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Chestguard of Plating';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901336,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Damaging Cinch';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901337,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Trousers of Obeying';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901338,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Treads of Impressing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901339,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Wristwraps of Excusing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901340,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Handwraps of Waring';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901341,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Guise of Tipping';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901342,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Perfect Amice';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901343,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Party Armor of Personalizing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901344,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Touchy Wrap';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901345,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Troubling Pants of Eying';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901346,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Energizing Steps';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901347,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Outlawing Bindings';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901348,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Booking Grips';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901349,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Faceguard of Authoring';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901350,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Motor Mantle of Concerting';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901351,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Armor of Troubling';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901352,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Demonstrative Girdle';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901353,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Thoughtful Kilt';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901354,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Steps of Belting';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901355,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Prize Armguards of Sharpening';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901356,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Enabling Grips';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901357,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Persuasive Handguards of Drinking';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901358,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Specialized Wristguards';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901359,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Imaginative Treads of Receiving';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901360,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Real Greaves';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901361,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Earthing Waistguard';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901362,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Armor of Beautifying';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901363,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Understandable Shoulderplates of Legalizing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901364,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Interviewing Helmet';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901365,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Headguard of Coursing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901366,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Greathelm of Striking';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901367,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Weighting Mantle';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901368,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Suggestible Shoulderplates';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901369,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Bicycling Mantle';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901370,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Spaulders of Coupling';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901371,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Explanatory Cuirass of Using';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901372,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Planing Chestguard';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901373,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Shockable Chestguard of Coupling';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901374,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Arguable Battleplate';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901375,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Banking Girdle';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901376,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Substantial Waistguard';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901377,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Fitted Platebelt';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901378,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Competing Greaves';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901379,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Fearless Breeches of Recognizing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901380,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Achievable Greaves';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901381,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Stompers of Switching';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901382,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Greaves of Staring';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901383,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Fishy Bindings';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901384,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Beginning Bindings of Questioning';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901385,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Bands of Finalizing';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901386,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Grips of Husbanding';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901387,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Gauntlets of Profiting';

   INSERT INTO `reference_loot_template` SET
      `Entry` = 9100400,
      `Item` = 901388,
      `Chance` = 0,
      `GroupId` = 1,
      `Comment` = 'Deceitful Handguards of Collecting';

-- Heroic Item Templates

   DELETE FROM `item_template` WHERE `entry` = 901388;

   INSERT INTO `item_template` SET
      `entry` = 901388,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Deceitful Handguards of Collecting',
      `displayid` = 55836,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 10,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 4,
      `stat_value1` = 7,
      `stat_type2` = 5,
      `stat_value2` = 9,
      `stat_type3` = 31,
      `stat_value3` = 23,
      `stat_type4` = 32,
      `stat_value4` = 14,
      `stat_type5` = 36,
      `stat_value5` = 23,
      `armor` = 471,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901387;

   INSERT INTO `item_template` SET
      `entry` = 901387,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Gauntlets of Profiting',
      `displayid` = 58792,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 10,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 2,
      `stat_type1` = 7,
      `stat_value1` = 25,
      `stat_type2` = 4,
      `stat_value2` = 50,
      `armor` = 659,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901386;

   INSERT INTO `item_template` SET
      `entry` = 901386,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Grips of Husbanding',
      `displayid` = 55839,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 10,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 4,
      `stat_value1` = 8,
      `stat_type2` = 7,
      `stat_value2` = 21,
      `stat_type3` = 32,
      `stat_value3` = 27,
      `stat_type4` = 36,
      `stat_value4` = 19,
      `armor` = 494,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901385;

   INSERT INTO `item_template` SET
      `entry` = 901385,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Bands of Finalizing',
      `displayid` = 18378,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 9,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 2,
      `stat_type1` = 7,
      `stat_value1` = 28,
      `stat_type2` = 36,
      `stat_value2` = 28,
      `armor` = 446,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901384;

   INSERT INTO `item_template` SET
      `entry` = 901384,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Beginning Bindings of Questioning',
      `displayid` = 59240,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 9,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 44,
      `stat_value1` = 16,
      `stat_type2` = 31,
      `stat_value2` = 23,
      `stat_type3` = 32,
      `stat_value3` = 16,
      `armor` = 368,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901383;

   INSERT INTO `item_template` SET
      `entry` = 901383,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Fishy Bindings',
      `displayid` = 46043,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 9,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 4,
      `stat_value1` = 7,
      `stat_type2` = 5,
      `stat_value2` = 17,
      `stat_type3` = 7,
      `stat_value3` = 19,
      `stat_type4` = 32,
      `stat_value4` = 12,
      `armor` = 338,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901382;

   INSERT INTO `item_template` SET
      `entry` = 901382,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Greaves of Staring',
      `displayid` = 64797,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 8,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 4,
      `stat_value1` = 39,
      `stat_type2` = 7,
      `stat_value2` = 26,
      `stat_type3` = 5,
      `stat_value3` = 9,
      `armor` = 629,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 50,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901381;

   INSERT INTO `item_template` SET
      `entry` = 901381,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Stompers of Switching',
      `displayid` = 59150,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 8,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 4,
      `stat_value1` = 16,
      `stat_type2` = 7,
      `stat_value2` = 19,
      `stat_type3` = 5,
      `stat_value3` = 22,
      `stat_type4` = 36,
      `stat_value4` = 19,
      `armor` = 531,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 50,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901380;

   INSERT INTO `item_template` SET
      `entry` = 901380,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Achievable Greaves',
      `displayid` = 61853,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 7,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 4,
      `stat_value1` = 35,
      `stat_type2` = 7,
      `stat_value2` = 43,
      `stat_type3` = 31,
      `stat_value3` = 21,
      `armor` = 768,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 75,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901379;

   INSERT INTO `item_template` SET
      `entry` = 901379,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Fearless Breeches of Recognizing',
      `displayid` = 65266,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 7,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 4,
      `stat_value1` = 53,
      `stat_type2` = 44,
      `stat_value2` = 12,
      `stat_type3` = 32,
      `stat_value3` = 35,
      `armor` = 815,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 75,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901378;

   INSERT INTO `item_template` SET
      `entry` = 901378,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Competing Greaves',
      `displayid` = 55793,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 7,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 7,
      `stat_value1` = 24,
      `stat_type2` = 4,
      `stat_value2` = 38,
      `stat_type3` = 5,
      `stat_value3` = 38,
      `armor` = 753,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 75,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901377;

   INSERT INTO `item_template` SET
      `entry` = 901377,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Fitted Platebelt',
      `displayid` = 58770,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 6,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 4,
      `stat_value1` = 19,
      `stat_type2` = 7,
      `stat_value2` = 29,
      `stat_type3` = 5,
      `stat_value3` = 26,
      `armor` = 483,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901376;

   INSERT INTO `item_template` SET
      `entry` = 901376,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Substantial Waistguard',
      `displayid` = 60347,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 6,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `stat_type1` = 7,
      `stat_value1` = 75,
      `armor` = 759,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901375;

   INSERT INTO `item_template` SET
      `entry` = 901375,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Banking Girdle',
      `displayid` = 62006,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 6,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 4,
      `stat_value1` = 5,
      `stat_type2` = 7,
      `stat_value2` = 24,
      `stat_type3` = 32,
      `stat_value3` = 22,
      `stat_type4` = 44,
      `stat_value4` = 7,
      `stat_type5` = 36,
      `stat_value5` = 17,
      `armor` = 425,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901374;

   INSERT INTO `item_template` SET
      `entry` = 901374,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Arguable Battleplate',
      `displayid` = 64787,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 5,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 2,
      `stat_type1` = 7,
      `stat_value1` = 44,
      `stat_type2` = 4,
      `stat_value2` = 55,
      `armor` = 1001,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 115,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901373;

   INSERT INTO `item_template` SET
      `entry` = 901373,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Shockable Chestguard of Coupling',
      `displayid` = 65271,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 5,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 4,
      `stat_value1` = 29,
      `stat_type2` = 7,
      `stat_value2` = 22,
      `stat_type3` = 32,
      `stat_value3` = 37,
      `stat_type4` = 31,
      `stat_value4` = 11,
      `armor` = 791,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 115,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901372;

   INSERT INTO `item_template` SET
      `entry` = 901372,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Planing Chestguard',
      `displayid` = 59233,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 5,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 5,
      `stat_value1` = 28,
      `stat_type2` = 7,
      `stat_value2` = 28,
      `stat_type3` = 36,
      `stat_value3` = 43,
      `armor` = 860,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 115,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901371;

   INSERT INTO `item_template` SET
      `entry` = 901371,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Explanatory Cuirass of Using',
      `displayid` = 46998,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 5,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 7,
      `stat_value1` = 12,
      `stat_type2` = 5,
      `stat_value2` = 29,
      `stat_type3` = 43,
      `stat_value3` = 23,
      `armor` = 930,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 115,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901370;

   INSERT INTO `item_template` SET
      `entry` = 901370,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Spaulders of Coupling',
      `displayid` = 60866,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 3,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 32,
      `stat_value1` = 29,
      `stat_type2` = 44,
      `stat_value2` = 21,
      `stat_type3` = 31,
      `stat_value3` = 25,
      `armor` = 645,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 60,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901369;

   INSERT INTO `item_template` SET
      `entry` = 901369,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Bicycling Mantle',
      `displayid` = 53891,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 3,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 2,
      `stat_type1` = 7,
      `stat_value1` = 39,
      `stat_type2` = 4,
      `stat_value2` = 35,
      `armor` = 750,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 60,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901368;

   INSERT INTO `item_template` SET
      `entry` = 901368,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Suggestible Shoulderplates',
      `displayid` = 31926,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 3,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 2,
      `stat_type1` = 44,
      `stat_value1` = 44,
      `stat_type2` = 31,
      `stat_value2` = 31,
      `armor` = 764,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 60,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901367;

   INSERT INTO `item_template` SET
      `entry` = 901367,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Weighting Mantle',
      `displayid` = 55208,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 3,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 4,
      `stat_value1` = 30,
      `stat_type2` = 5,
      `stat_value2` = 18,
      `stat_type3` = 32,
      `stat_value3` = 15,
      `stat_type4` = 36,
      `stat_value4` = 12,
      `armor` = 593,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 60,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901366;

   INSERT INTO `item_template` SET
      `entry` = 901366,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Greathelm of Striking',
      `displayid` = 38294,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 1,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 4,
      `stat_value1` = 28,
      `stat_type2` = 5,
      `stat_value2` = 26,
      `stat_type3` = 32,
      `stat_value3` = 11,
      `stat_type4` = 31,
      `stat_value4` = 9,
      `stat_type5` = 43,
      `stat_value5` = 10,
      `armor` = 585,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 65,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901365;

   INSERT INTO `item_template` SET
      `entry` = 901365,
      `class` = 4,
      `subclass` = 4,
      `name` = 'Headguard of Coursing',
      `displayid` = 47594,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 1,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 2,
      `stat_type1` = 7,
      `stat_value1` = 75,
      `stat_type2` = 4,
      `stat_value2` = 25,
      `armor` = 899,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 65,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901364;

   INSERT INTO `item_template` SET
      `entry` = 901364,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Interviewing Helmet',
      `displayid` = 59658,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 1,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 3,
      `stat_value1` = 17,
      `stat_type2` = 5,
      `stat_value2` = 21,
      `stat_type3` = 36,
      `stat_value3` = 21,
      `stat_type4` = 44,
      `stat_value4` = 41,
      `armor` = 357,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 65,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901363;

   INSERT INTO `item_template` SET
      `entry` = 901363,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Understandable Shoulderplates of Legalizing',
      `displayid` = 34056,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 3,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 7,
      `stat_value1` = 20,
      `stat_type2` = 3,
      `stat_value2` = 14,
      `stat_type3` = 38,
      `stat_value3` = 41,
      `stat_type4` = 32,
      `stat_value4` = 20,
      `armor` = 315,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 60,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901362;

   INSERT INTO `item_template` SET
      `entry` = 901362,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Armor of Beautifying',
      `displayid` = 55214,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 5,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 7,
      `stat_value1` = 26,
      `stat_type2` = 5,
      `stat_value2` = 26,
      `stat_type3` = 3,
      `stat_value3` = 15,
      `stat_type4` = 32,
      `stat_value4` = 33,
      `armor` = 429,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 115,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901361;

   INSERT INTO `item_template` SET
      `entry` = 901361,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Earthing Waistguard',
      `displayid` = 60344,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 6,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 7,
      `stat_value1` = 29,
      `stat_type2` = 3,
      `stat_value2` = 37,
      `stat_type3` = 43,
      `stat_value3` = 3,
      `armor` = 285,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901360;

   INSERT INTO `item_template` SET
      `entry` = 901360,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Real Greaves',
      `displayid` = 31968,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 7,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 6,
      `stat_type1` = 3,
      `stat_value1` = 20,
      `stat_type2` = 7,
      `stat_value2` = 23,
      `stat_type3` = 5,
      `stat_value3` = 14,
      `stat_type4` = 31,
      `stat_value4` = 23,
      `stat_type5` = 36,
      `stat_value5` = 11,
      `stat_type6` = 44,
      `stat_value6` = 9,
      `armor` = 324,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 75,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901359;

   INSERT INTO `item_template` SET
      `entry` = 901359,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Imaginative Treads of Receiving',
      `displayid` = 47420,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 8,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 2,
      `stat_type1` = 3,
      `stat_value1` = 62,
      `stat_type2` = 38,
      `stat_value2` = 25,
      `armor` = 443,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 50,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901358;

   INSERT INTO `item_template` SET
      `entry` = 901358,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Specialized Wristguards',
      `displayid` = 40495,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 9,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 5,
      `stat_value1` = 10,
      `stat_type2` = 3,
      `stat_value2` = 18,
      `stat_type3` = 44,
      `stat_value3` = 8,
      `stat_type4` = 36,
      `stat_value4` = 20,
      `armor` = 192,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901357;

   INSERT INTO `item_template` SET
      `entry` = 901357,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Persuasive Handguards of Drinking',
      `displayid` = 61840,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 10,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 5,
      `stat_value1` = 18,
      `stat_type2` = 3,
      `stat_value2` = 12,
      `stat_type3` = 7,
      `stat_value3` = 21,
      `stat_type4` = 44,
      `stat_value4` = 6,
      `stat_type5` = 36,
      `stat_value5` = 18,
      `armor` = 251,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901356;

   INSERT INTO `item_template` SET
      `entry` = 901356,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Enabling Grips',
      `displayid` = 61840,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 10,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 5,
      `stat_value1` = 10,
      `stat_type2` = 32,
      `stat_value2` = 45,
      `stat_type3` = 36,
      `stat_value3` = 20,
      `armor` = 329,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901355;

   INSERT INTO `item_template` SET
      `entry` = 901355,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Prize Armguards of Sharpening',
      `displayid` = 64831,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 9,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 7,
      `stat_value1` = 19,
      `stat_type2` = 6,
      `stat_value2` = 13,
      `stat_type3` = 5,
      `stat_value3` = 24,
      `armor` = 213,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901354;

   INSERT INTO `item_template` SET
      `entry` = 901354,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Steps of Belting',
      `displayid` = 34269,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 8,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 6,
      `stat_value1` = 34,
      `stat_type2` = 7,
      `stat_value2` = 11,
      `stat_type3` = 36,
      `stat_value3` = 30,
      `armor` = 350,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 50,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901353;

   INSERT INTO `item_template` SET
      `entry` = 901353,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Thoughtful Kilt',
      `displayid` = 48492,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 7,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 7,
      `stat_value1` = 19,
      `stat_type2` = 32,
      `stat_value2` = 19,
      `stat_type3` = 45,
      `stat_value3` = 61,
      `stat_type4` = 36,
      `stat_value4` = 31,
      `armor` = 375,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 75,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901352;

   INSERT INTO `item_template` SET
      `entry` = 901352,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Demonstrative Girdle',
      `displayid` = 31925,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 6,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 6,
      `stat_value1` = 6,
      `stat_type2` = 5,
      `stat_value2` = 22,
      `stat_type3` = 36,
      `stat_value3` = 25,
      `stat_type4` = 45,
      `stat_value4` = 12,
      `stat_type5` = 43,
      `stat_value5` = 6,
      `armor` = 236,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901351;

   INSERT INTO `item_template` SET
      `entry` = 901351,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Armor of Troubling',
      `displayid` = 54457,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 5,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 6,
      `stat_type1` = 7,
      `stat_value1` = 12,
      `stat_type2` = 6,
      `stat_value2` = 15,
      `stat_type3` = 5,
      `stat_value3` = 26,
      `stat_type4` = 36,
      `stat_value4` = 23,
      `stat_type5` = 32,
      `stat_value5` = 15,
      `stat_type6` = 45,
      `stat_value6` = 18,
      `armor` = 371,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 115,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901350;

   INSERT INTO `item_template` SET
      `entry` = 901350,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Motor Mantle of Concerting',
      `displayid` = 45882,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 3,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 5,
      `stat_value1` = 15,
      `stat_type2` = 7,
      `stat_value2` = 22,
      `stat_type3` = 6,
      `stat_value3` = 5,
      `stat_type4` = 45,
      `stat_value4` = 20,
      `stat_type5` = 32,
      `stat_value5` = 22,
      `armor` = 308,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 60,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901349;

   INSERT INTO `item_template` SET
      `entry` = 901349,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Faceguard of Authoring',
      `displayid` = 62982,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 1,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 6,
      `stat_value1` = 16,
      `stat_type2` = 32,
      `stat_value2` = 40,
      `stat_type3` = 45,
      `stat_value3` = 56,
      `stat_type4` = 43,
      `stat_value4` = 6,
      `armor` = 357,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 65,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901348;

   INSERT INTO `item_template` SET
      `entry` = 901348,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Booking Grips',
      `displayid` = 45707,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 10,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 7,
      `stat_value1` = 15,
      `stat_type2` = 5,
      `stat_value2` = 34,
      `stat_type3` = 6,
      `stat_value3` = 26,
      `armor` = 134,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901347;

   INSERT INTO `item_template` SET
      `entry` = 901347,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Outlawing Bindings',
      `displayid` = 64373,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 9,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 6,
      `stat_type1` = 7,
      `stat_value1` = 3,
      `stat_type2` = 6,
      `stat_value2` = 13,
      `stat_type3` = 5,
      `stat_value3` = 4,
      `stat_type4` = 32,
      `stat_value4` = 7,
      `stat_type5` = 36,
      `stat_value5` = 15,
      `stat_type6` = 43,
      `stat_value6` = 5,
      `armor` = 74,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901346;

   INSERT INTO `item_template` SET
      `entry` = 901346,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Energizing Steps',
      `displayid` = 60643,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 8,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 7,
      `stat_value1` = 9,
      `stat_type2` = 5,
      `stat_value2` = 18,
      `stat_type3` = 43,
      `stat_value3` = 7,
      `stat_type4` = 45,
      `stat_value4` = 33,
      `stat_type5` = 32,
      `stat_value5` = 13,
      `armor` = 119,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 50,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901345;

   INSERT INTO `item_template` SET
      `entry` = 901345,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Troubling Pants of Eying',
      `displayid` = 59342,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 7,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 5,
      `stat_value1` = 34,
      `stat_type2` = 7,
      `stat_value2` = 31,
      `stat_type3` = 45,
      `stat_value3` = 69,
      `armor` = 185,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 75,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901344;

   INSERT INTO `item_template` SET
      `entry` = 901344,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Touchy Wrap',
      `displayid` = 43542,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 6,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 5,
      `stat_value1` = 19,
      `stat_type2` = 7,
      `stat_value2` = 19,
      `stat_type3` = 6,
      `stat_value3` = 21,
      `stat_type4` = 36,
      `stat_value4` = 15,
      `armor` = 104,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901343;

   INSERT INTO `item_template` SET
      `entry` = 901343,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Party Armor of Personalizing',
      `displayid` = 45057,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 5,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 5,
      `stat_value1` = 35,
      `stat_type2` = 6,
      `stat_value2` = 35,
      `stat_type3` = 36,
      `stat_value3` = 28,
      `armor` = 206,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 115,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901342;

   INSERT INTO `item_template` SET
      `entry` = 901342,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Perfect Amice',
      `displayid` = 60929,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 3,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 6,
      `stat_type1` = 7,
      `stat_value1` = 19,
      `stat_type2` = 5,
      `stat_value2` = 9,
      `stat_type3` = 6,
      `stat_value3` = 15,
      `stat_type4` = 43,
      `stat_value4` = 1,
      `stat_type5` = 32,
      `stat_value5` = 13,
      `stat_type6` = 36,
      `stat_value6` = 15,
      `armor` = 123,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 60,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901341;

   INSERT INTO `item_template` SET
      `entry` = 901341,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Guise of Tipping',
      `displayid` = 53942,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 1,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 6,
      `stat_value1` = 29,
      `stat_type2` = 5,
      `stat_value2` = 12,
      `stat_type3` = 32,
      `stat_value3` = 17,
      `stat_type4` = 45,
      `stat_value4` = 17,
      `stat_type5` = 36,
      `stat_value5` = 33,
      `armor` = 147,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 65,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901340;

   INSERT INTO `item_template` SET
      `entry` = 901340,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Handwraps of Waring',
      `displayid` = 41443,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 10,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 3,
      `stat_value1` = 20,
      `stat_type2` = 7,
      `stat_value2` = 22,
      `stat_type3` = 31,
      `stat_value3` = 11,
      `stat_type4` = 32,
      `stat_value4` = 22,
      `armor` = 119,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901339;

   INSERT INTO `item_template` SET
      `entry` = 901339,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Wristwraps of Excusing',
      `displayid` = 45022,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 9,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 7,
      `stat_value1` = 10,
      `stat_type2` = 3,
      `stat_value2` = 24,
      `stat_type3` = 32,
      `stat_value3` = 22,
      `armor` = 96,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901338;

   INSERT INTO `item_template` SET
      `entry` = 901338,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Treads of Impressing',
      `displayid` = 49057,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 8,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 3,
      `stat_value1` = 12,
      `stat_type2` = 7,
      `stat_value2` = 29,
      `stat_type3` = 36,
      `stat_value3` = 21,
      `stat_type4` = 31,
      `stat_value4` = 12,
      `armor` = 134,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 50,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901337;

   INSERT INTO `item_template` SET
      `entry` = 901337,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Trousers of Obeying',
      `displayid` = 45665,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 7,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 3,
      `stat_value1` = 35,
      `stat_type2` = 7,
      `stat_value2` = 14,
      `stat_type3` = 36,
      `stat_value3` = 50,
      `armor` = 195,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 75,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901336;

   INSERT INTO `item_template` SET
      `entry` = 901336,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Damaging Cinch',
      `displayid` = 48357,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 6,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 3,
      `stat_value1` = 19,
      `stat_type2` = 38,
      `stat_value2` = 22,
      `stat_type3` = 44,
      `stat_value3` = 30,
      `stat_type4` = 36,
      `stat_value4` = 15,
      `armor` = 108,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901335;

   INSERT INTO `item_template` SET
      `entry` = 901335,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Chestguard of Plating',
      `displayid` = 35054,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 5,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 7,
      `stat_value1` = 33,
      `stat_type2` = 3,
      `stat_value2` = 33,
      `stat_type3` = 38,
      `stat_value3` = 66,
      `armor` = 206,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 115,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901334;

   INSERT INTO `item_template` SET
      `entry` = 901334,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Mantle of Guiding',
      `displayid` = 61932,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 3,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 7,
      `stat_value1` = 20,
      `stat_type2` = 3,
      `stat_value2` = 6,
      `stat_type3` = 44,
      `stat_value3` = 14,
      `stat_type4` = 31,
      `stat_value4` = 9,
      `stat_type5` = 36,
      `stat_value5` = 26,
      `armor` = 138,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 60,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901333;

   INSERT INTO `item_template` SET
      `entry` = 901333,
      `class` = 4,
      `subclass` = 2,
      `name` = 'Romantic Crown',
      `displayid` = 65154,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 1,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 3,
      `stat_value1` = 23,
      `stat_type2` = 7,
      `stat_value2` = 36,
      `stat_type3` = 38,
      `stat_value3` = 81,
      `armor` = 171,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 65,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901332;

   INSERT INTO `item_template` SET
      `entry` = 901332,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Gifting Shroud',
      `displayid` = 64640,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 16,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 7,
      `stat_value1` = 12,
      `stat_type2` = 5,
      `stat_value2` = 31,
      `stat_type3` = 6,
      `stat_value3` = 12,
      `armor` = 39,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901331;

   INSERT INTO `item_template` SET
      `entry` = 901331,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Speedy Handguards',
      `displayid` = 62066,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 10,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 6,
      `stat_value1` = 11,
      `stat_type2` = 5,
      `stat_value2` = 14,
      `stat_type3` = 7,
      `stat_value3` = 19,
      `stat_type4` = 45,
      `stat_value4` = 28,
      `stat_type5` = 43,
      `stat_value5` = 7,
      `armor` = 59,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901330;

   INSERT INTO `item_template` SET
      `entry` = 901330,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Supportive Cuffs of Defending',
      `displayid` = 65445,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 9,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 6,
      `stat_value1` = 25,
      `stat_type2` = 5,
      `stat_value2` = 12,
      `stat_type3` = 47,
      `stat_value3` = 9,
      `armor` = 50,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901329;

   INSERT INTO `item_template` SET
      `entry` = 901329,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Slippers of Accusing',
      `displayid` = 46064,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 8,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 5,
      `stat_value1` = 5,
      `stat_type2` = 7,
      `stat_value2` = 20,
      `stat_type3` = 6,
      `stat_value3` = 25,
      `stat_type4` = 45,
      `stat_value4` = 50,
      `armor` = 74,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 50,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901328;

   INSERT INTO `item_template` SET
      `entry` = 901328,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Kilt of Forming',
      `displayid` = 48224,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 7,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 5,
      `stat_value1` = 31,
      `stat_type2` = 7,
      `stat_value2` = 12,
      `stat_type3` = 43,
      `stat_value3` = 15,
      `stat_type4` = 45,
      `stat_value4` = 37,
      `armor` = 92,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 75,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901327;

   INSERT INTO `item_template` SET
      `entry` = 901327,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Cord of Chairing',
      `displayid` = 46115,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 6,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 5,
      `stat_value1` = 23,
      `stat_type2` = 6,
      `stat_value2` = 18,
      `stat_type3` = 7,
      `stat_value3` = 13,
      `stat_type4` = 47,
      `stat_value4` = 4,
      `stat_type5` = 45,
      `stat_value5` = 26,
      `armor` = 54,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 35,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901326;

   INSERT INTO `item_template` SET
      `entry` = 901326,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Racial Vestments of Frightening',
      `displayid` = 47159,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 5,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 7,
      `stat_value1` = 15,
      `stat_type2` = 5,
      `stat_value2` = 22,
      `stat_type3` = 43,
      `stat_value3` = 12,
      `stat_type4` = 47,
      `stat_value4` = 17,
      `armor` = 105,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 115,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901325;

   INSERT INTO `item_template` SET
      `entry` = 901325,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Systematic Cowl of Shipping',
      `displayid` = 45975,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 1,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 5,
      `stat_value1` = 56,
      `stat_type2` = 47,
      `stat_value2` = 16,
      `stat_type3` = 45,
      `stat_value3` = 25,
      `armor` = 102,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 65,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901324;

   INSERT INTO `item_template` SET
      `entry` = 901324,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Shaped Pauldrons of Disappointing',
      `displayid` = 45409,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 3,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 6,
      `stat_value1` = 11,
      `stat_type2` = 5,
      `stat_value2` = 23,
      `stat_type3` = 43,
      `stat_value3` = 7,
      `stat_type4` = 47,
      `stat_value4` = 11,
      `armor` = 75,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 60,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901323;

   INSERT INTO `item_template` SET
      `entry` = 901323,
      `class` = 4,
      `subclass` = 1,
      `name` = 'Shawl of Sensing',
      `displayid` = 48869,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 16,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 4,
      `stat_value1` = 9,
      `stat_type2` = 7,
      `stat_value2` = 34,
      `stat_type3` = 36,
      `stat_value3` = 13,
      `armor` = 41,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901322;

   INSERT INTO `item_template` SET
      `entry` = 901322,
      `class` = 2,
      `subclass` = 7,
      `name` = 'Silent Claw',
      `displayid` = 54471,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 13,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 4,
      `stat_type1` = 7,
      `stat_value1` = 3,
      `stat_type2` = 4,
      `stat_value2` = 17,
      `stat_type3` = 31,
      `stat_value3` = 9,
      `stat_type4` = 32,
      `stat_value4` = 12,
      `dmg_min1` = 40,
      `dmg_max1` = 72,
      `delay` = 1300,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `sheath` = 3,
      `MaxDurability` = 105,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901321;

   INSERT INTO `item_template` SET
      `entry` = 901321,
      `class` = 2,
      `subclass` = 7,
      `name` = 'Styling Slicer',
      `displayid` = 57331,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 13,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 3,
      `stat_type1` = 7,
      `stat_value1` = 14,
      `stat_type2` = 43,
      `stat_value2` = 6,
      `stat_type3` = 32,
      `stat_value3` = 14,
      `dmg_min1` = 61,
      `dmg_max1` = 85,
      `delay` = 1700,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `sheath` = 3,
      `MaxDurability` = 105,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';

   DELETE FROM `item_template` WHERE `entry` = 901320;

   INSERT INTO `item_template` SET
      `entry` = 901320,
      `class` = 4,
      `subclass` = 3,
      `name` = 'Profitable Faceguard',
      `displayid` = 42115,
      `Quality` = 4,
      `Flags` = 8,
      `BuyPrice` = 1,
      `SellPrice` = 1,
      `InventoryType` = 1,
      `ItemLevel` = 66,
      `RequiredLevel` = 60,
      `StatsCount` = 5,
      `stat_type1` = 3,
      `stat_value1` = 26,
      `stat_type2` = 7,
      `stat_value2` = 26,
      `stat_type3` = 43,
      `stat_value3` = 12,
      `stat_type4` = 31,
      `stat_value4` = 9,
      `stat_type5` = 44,
      `stat_value5` = 9,
      `armor` = 333,
      `delay` = 0,
      `RangedModRange` = 1,
      `spellcooldown_1` = 0,
      `spellcategorycooldown_1` = 0,
      `spellcooldown_2` = 0,
      `spellcategorycooldown_2` = 0,
      `spellcooldown_3` = 0,
      `spellcategorycooldown_3` = 0,
      `spellcooldown_4` = 0,
      `spellcategorycooldown_4` = 0,
      `spellcooldown_5` = 0,
      `spellcategorycooldown_5` = 0,
      `bonding` = 1,
      `MaxDurability` = 65,
      `RequiredDisenchantSkill` = 0,
      `DisenchantID` = 65,
      `VerifiedBuild` = '0';
