-- [BASE,F-030] worgoblin: vocaluisounds
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-030]_vocaluisounds.sql with overrides

-- vocaluisounds: 184 inserts, 0 updates, 0 deletes
DELETE FROM `vocaluisounds` WHERE `id` = 862;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (862, 56, 12, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 863;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (863, 0, 12, 19306, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 864;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (864, 63, 12, 19329, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 865;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (865, 1, 9, 19119, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 866;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (866, 0, 23, 18981, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 867;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (867, 1, 23, 19001, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 868;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (868, 2, 23, 18985, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 869;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (869, 3, 23, 18984, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 870;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (870, 4, 23, 18983, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 871;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (871, 5, 23, 18995, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 872;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (872, 6, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 873;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (873, 8, 23, 19009, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 874;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (874, 9, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 875;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (875, 9, 11, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 876;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (876, 10, 23, 19008, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 877;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (877, 11, 23, 18993, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 878;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (878, 12, 23, 19011, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 879;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (879, 13, 23, 18987, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 880;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (880, 14, 23, 18996, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 881;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (881, 15, 23, 19003, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 882;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (882, 16, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 883;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (883, 16, 11, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 884;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (884, 17, 23, 18998, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 885;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (885, 18, 23, 18982, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 886;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (886, 19, 11, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 887;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (887, 20, 23, 18979, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 888;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (888, 21, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 889;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (889, 21, 11, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 890;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (890, 22, 23, 19006, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 891;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (891, 23, 11, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 892;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (892, 24, 11, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 893;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (893, 25, 23, 19005, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 894;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (894, 26, 23, 18980, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 895;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (895, 27, 23, 18980, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 896;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (896, 28, 23, 18980, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 897;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (897, 29, 23, 18981, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 898;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (898, 30, 23, 18997, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 899;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (899, 32, 11, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 900;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (900, 31, 23, 18998, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 901;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (901, 33, 23, 18996, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 902;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (902, 35, 23, 18999, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 903;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (903, 36, 11, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 904;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (904, 38, 23, 18991, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 905;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (905, 39, 23, 19006, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 906;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (906, 40, 23, 19006, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 907;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (907, 41, 23, 18986, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 908;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (908, 42, 23, 18976, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 909;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (909, 43, 23, 18977, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 910;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (910, 45, 23, 18991, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 911;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (911, 44, 23, 19007, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 912;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (912, 46, 23, 19008, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 913;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (913, 47, 23, 19010, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 914;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (914, 48, 23, 18989, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 915;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (915, 49, 23, 19000, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 916;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (916, 50, 23, 18978, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 917;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (917, 51, 23, 18989, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 918;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (918, 52, 23, 18990, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 919;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (919, 55, 23, 18996, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 920;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (920, 59, 23, 18988, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 921;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (921, 63, 23, 19004, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 922;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (922, 64, 23, 19002, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 923;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (923, 66, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 924;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (924, 62, 23, 18992, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 925;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (925, 57, 23, 18999, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 926;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (926, 58, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 927;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (927, 58, 11, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 928;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (928, 7, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 929;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (929, 19, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 930;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (930, 23, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 931;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (931, 24, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 932;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (932, 32, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 933;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (933, 36, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 934;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (934, 54, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 935;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (935, 56, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 936;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (936, 61, 23, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 937;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (937, 2, 9, 19103, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 938;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (938, 3, 9, 19102, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 939;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (939, 4, 9, 19101, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 940;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (940, 5, 9, 19113, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 941;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (941, 6, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 942;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (942, 8, 9, 19127, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 943;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (943, 10, 9, 19126, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 944;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (944, 11, 9, 19111, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 945;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (945, 12, 9, 19129, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 946;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (946, 13, 9, 19105, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 947;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (947, 14, 9, 19114, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 948;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (948, 15, 9, 19121, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 949;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (949, 17, 9, 19116, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 950;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (950, 18, 9, 19100, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 951;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (951, 20, 9, 19097, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 952;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (952, 22, 9, 19124, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 953;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (953, 25, 9, 19123, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 954;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (954, 26, 9, 19098, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 955;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (955, 27, 9, 19098, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 956;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (956, 28, 9, 19098, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 957;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (957, 29, 9, 19099, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 958;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (958, 30, 9, 19115, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 959;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (959, 31, 9, 19116, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 960;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (960, 32, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 961;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (961, 33, 9, 19114, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 962;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (962, 35, 9, 19117, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 963;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (963, 38, 9, 19109, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 964;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (964, 39, 9, 19124, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 965;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (965, 40, 9, 19124, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 966;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (966, 41, 9, 19104, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 967;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (967, 42, 9, 19094, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 968;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (968, 43, 9, 19095, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 969;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (969, 44, 9, 19125, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 970;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (970, 45, 9, 19109, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 971;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (971, 46, 9, 19126, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 972;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (972, 47, 9, 19128, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 973;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (973, 48, 9, 19107, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 974;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (974, 49, 9, 19118, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 975;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (975, 50, 9, 19096, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 976;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (976, 51, 9, 19107, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 977;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (977, 52, 9, 19108, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 978;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (978, 54, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 979;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (979, 55, 9, 19114, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 980;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (980, 56, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 981;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (981, 57, 9, 19126, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 982;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (982, 58, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 983;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (983, 59, 9, 19106, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 984;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (984, 61, 9, 19114, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 985;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (985, 62, 9, 19110, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 986;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (986, 63, 9, 19122, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 987;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (987, 64, 9, 19120, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 988;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (988, 66, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 989;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (989, 1, 12, 19326, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 990;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (990, 2, 12, 19310, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 991;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (991, 3, 12, 19309, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 992;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (992, 4, 12, 19308, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 993;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (993, 5, 12, 19320, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 994;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (994, 6, 12, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 995;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (995, 8, 12, 19334, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 996;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (996, 9, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 997;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (997, 10, 12, 19333, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 998;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (998, 11, 12, 19318, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 999;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (999, 12, 12, 19336, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1000;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1000, 13, 12, 19312, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1001;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1001, 14, 12, 19321, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1002;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1002, 15, 12, 19328, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1003;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1003, 17, 12, 19323, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1004;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1004, 18, 12, 19307, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1005;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1005, 22, 12, 19331, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1006;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1006, 19, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1007;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1007, 21, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1008;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1008, 23, 9, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1009;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1009, 20, 12, 19334, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1010;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1010, 24, 12, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1011;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1011, 25, 12, 19330, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1012;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1012, 26, 12, 19305, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1013;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1013, 27, 12, 19305, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1014;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1014, 28, 12, 19305, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1015;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1015, 29, 12, 19306, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1016;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1016, 30, 12, 19322, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1017;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1017, 31, 12, 19323, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1018;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1018, 32, 12, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1019;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1019, 33, 12, 19321, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1020;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1020, 35, 12, 19324, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1021;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1021, 38, 12, 19316, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1022;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1022, 39, 12, 19331, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1023;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1023, 40, 12, 19331, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1024;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1024, 41, 12, 19311, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1025;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1025, 42, 12, 19301, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1026;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1026, 43, 12, 19302, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1027;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1027, 44, 12, 19332, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1028;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1028, 45, 12, 19316, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1029;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1029, 46, 12, 19333, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1030;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1030, 47, 12, 19335, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1031;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1031, 48, 12, 19314, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1032;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1032, 49, 12, 19325, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1033;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1033, 50, 12, 19303, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1034;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1034, 51, 12, 19314, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1035;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1035, 52, 12, 19315, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1036;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1036, 54, 12, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1037;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1037, 55, 12, 19321, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1038;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1038, 57, 12, 19333, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1039;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1039, 59, 12, 19313, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1040;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1040, 61, 12, 19321, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1041;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1041, 62, 12, 19317, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1042;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1042, 64, 12, 19327, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1066;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1066, 1, 14, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1069;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1069, 36, 12, 0, 0);
DELETE FROM `vocaluisounds` WHERE `id` = 1074;
INSERT INTO `vocaluisounds` (`id`, `vocal_ui_enum`, `race_id`, `normal_sound_id_1`, `pissed_sound_id_1`) VALUES (1074, 0, 13, 0, 0);