"""
Bag Scaling Generator (F-079 Bigger Bags)

Reads bag definitions from bags.csv and generates SQL to update ContainerSlots
in item_template. Scales bag sizes across the game so inventory progression
feels more rewarding.
"""

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple

DATA_DIR = Path(__file__).parent / 'data'
CSV_FILE = DATA_DIR / 'bags.csv'

OUTPUT_FILENAME = "zz_[AUTO,F-079]_update_bag_slots.sql"

SQL_HEADER = """\
-- ===================================================================
-- F-079 Bigger Bags — Container Slot Scaling
-- ===================================================================
-- Increases ContainerSlots for bags throughout the game.
-- Scaling factors range from ~1.25x (small bags) to ~1.67x (starter bags).
-- AUTO-GENERATED by: zep bag generate
-- DO NOT EDIT MANUALLY - Regenerate with: zep bag generate
-- Source data: cli/lib/bag/data/bags.csv
-- ===================================================================

"""


@dataclass
class BagEntry:
    entry: int
    name: str
    source: str
    original_slots: int
    new_slots: int


def load_bags(csv_path: Path = CSV_FILE) -> List[BagEntry]:
    """Load bag definitions from CSV."""
    bags = []
    with open(csv_path, mode='r', newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            entry = int(row['entry'])
            name = row['name']
            source = row.get('source', '')
            original_slots = int(row['slots']) if row.get('slots') else 0
            new_slots = int(row['new_slots']) if row.get('new_slots') else 0
            bags.append(BagEntry(
                entry=entry,
                name=name,
                source=source,
                original_slots=original_slots,
                new_slots=new_slots,
            ))
    return bags


def generate_sql(bags: List[BagEntry]) -> str:
    """Generate the UPDATE SQL from bag entries."""
    lines = [SQL_HEADER]
    lines.append("UPDATE `item_template`")
    lines.append("SET `ContainerSlots` = CASE")

    for bag in bags:
        lines.append(f"    WHEN `entry` = {bag.entry} THEN {bag.new_slots} -- {bag.name}")

    lines.append("")
    lines.append("    ELSE `ContainerSlots`")
    lines.append("END;")
    lines.append("")

    return "\n".join(lines)


def run(output_path: Path, verbose: bool = True) -> Tuple[int, str]:
    """Load bags, generate SQL, write to file.

    Returns (bag_count, sql_content).
    """
    bags = load_bags()

    if verbose:
        # Group by new_slots descending for summary
        by_slots = {}
        for b in bags:
            by_slots.setdefault(b.new_slots, []).append(b)
        for slots in sorted(by_slots.keys(), reverse=True):
            entries = by_slots[slots]
            for b in entries:
                change = f"{b.original_slots} -> {slots}"
                print(f"  {b.name:<40} {change}")

    sql_content = generate_sql(bags)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(sql_content)

    return len(bags), sql_content
