-- [BASE,F-044] zepcraft-legacy: lfgdungeons
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-044]_lfgdungeons.sql with overrides

-- lfgdungeons: 66 inserts, 54 updates, 5 deletes
DELETE FROM `lfgdungeons` WHERE `id` = 258;
DELETE FROM `lfgdungeons` WHERE `id` = 259;
DELETE FROM `lfgdungeons` WHERE `id` = 260;
DELETE FROM `lfgdungeons` WHERE `id` = 261;
DELETE FROM `lfgdungeons` WHERE `id` = 262;
DELETE FROM `lfgdungeons` WHERE `id` = 295;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (295, 'Stormwind Stockade (Heroic)', 16712190, 60, 63, 60, 60, 63, 34, 1, 3, 5, 1, 'STORMWINDSTOCKADES', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 296;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (296, 'Shadowfang Keep (Heroic)', 16712190, 60, 63, 60, 60, 60, 33, 1, 3, 5, -1, 'SHADOWFANGKEEP', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 297;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (297, 'Razorfen Kraul (Heroic)', 16712190, 60, 63, 60, 60, 60, 47, 1, 3, 5, -1, 'RAZORFENKRAUL', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 298;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (298, 'Razorfen Downs (Heroic)', 16712190, 60, 63, 60, 60, 60, 129, 1, 3, 5, -1, 'RAZORFENDOWNS', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 299;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (299, 'Wailing Caverns (Heroic)', 16712190, 60, 63, 60, 60, 60, 43, 1, 3, 5, -1, 'WAILINGCAVERNS', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 300;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (300, 'Ragefire Chasm (Heroic)', 16712190, 60, 63, 60, 60, 60, 389, 1, 3, 5, 0, 'RAGEFIRECHASM', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 301;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (301, 'Gnomeregan (Heroic)', 16712190, 60, 63, 60, 60, 60, 90, 1, 3, 5, -1, 'GNOMEREGAN', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 302;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (302, 'Blackfathom Deeps (Heroic)', 16712190, 60, 63, 60, 60, 60, 48, 1, 3, 5, -1, 'BLACKFATHOMDEEPS', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 303;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (303, 'Scarlet Monastery - Graveyard (Heroic)', 16712190, 60, 63, 60, 60, 60, 189, 1, 3, 5, -1, 'SCARLETMONASTERY', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 304;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (304, 'Uldaman (Heroic)', 16712190, 60, 63, 60, 60, 60, 70, 1, 3, 5, -1, 'ULDAMAN', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 305;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (305, 'Zul\'Farrak (Heroic)', 16712190, 60, 63, 60, 60, 60, 209, 1, 3, 5, -1, 'ZULFARAK', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 306;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (306, 'Maraudon - Orange Crystals (Heroic)', 16712190, 60, 63, 60, 60, 60, 349, 1, 3, 5, -1, 'MARAUDON', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 307;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (307, 'Sunken Temple (Heroic)', 16712190, 60, 63, 60, 60, 60, 109, 1, 3, 5, -1, 'SUNKENTEMPLE', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 308;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (308, 'Blackrock Depths - Prison (Heroic)', 16712190, 60, 63, 60, 60, 60, 230, 1, 3, 5, -1, 'BLACKROCKDEPTHS', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 309;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (309, 'Lower Blackrock Spire (Heroic)', 16712190, 60, 63, 60, 60, 60, 229, 1, 3, 5, -1, 'BLACKROCKSPIRE', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 310;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (310, 'Dire Maul - East (Heroic)', 16712190, 60, 63, 60, 60, 60, 429, 1, 3, 5, -1, 'DIREMAUL', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 311;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (311, 'Dire Maul - West (Heroic)', 16712190, 60, 63, 60, 60, 60, 429, 1, 3, 5, -1, 'DIREMAUL', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 312;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (312, 'Dire Maul - North (Heroic)', 16712190, 60, 63, 60, 60, 60, 429, 1, 3, 5, -1, 'DIREMAUL', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 313;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (313, 'Stratholme - Main Gate (Heroic)', 16712190, 60, 63, 60, 60, 60, 329, 1, 3, 5, -1, 'STRATHOLME', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 314;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (314, 'Upper Blackrock Spire (Heroic)', 16712190, 60, 63, 60, 60, 60, 229, 1, 3, 5, -1, 'BlackrockSpire', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 315;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (315, 'Scarlet Monastery - Armory (Heroic)', 16712190, 60, 63, 60, 60, 60, 189, 1, 3, 5, -1, 'SCARLETMONASTERY', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 316;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (316, 'Scarlet Monastery - Cathedral (Heroic)', 16712190, 60, 63, 60, 60, 60, 189, 1, 3, 5, -1, 'SCARLETMONASTERY', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 317;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (317, 'Scarlet Monastery - Library (Heroic)', 16712190, 60, 63, 60, 60, 60, 189, 1, 3, 5, -1, 'SCARLETMONASTERY', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 318;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (318, 'Maraudon - Purple Crystals (Heroic)', 16712190, 60, 63, 60, 60, 60, 349, 1, 3, 5, -1, 'MARAUDON', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 319;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (319, 'Maraudon - Pristine Waters (Heroic)', 16712190, 60, 63, 60, 60, 60, 349, 1, 3, 5, -1, 'MARAUDON', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 320;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (320, 'Stratholme - Service Entrance (Heroic)', 16712190, 60, 63, 60, 60, 60, 329, 1, 3, 5, -1, 'STRATHOLME', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 321;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (321, 'Blackrock Depths - Upper City (Heroic)', 16712190, 60, 63, 60, 60, 60, 230, 1, 3, 5, -1, 'BLACKROCKDEPTHS', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 322;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (322, 'Scholomance (Heroic)', 16712190, 60, 63, 60, 60, 60, 289, 1, 3, 5, -1, 'SCHOLOMANCE', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 323;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (323, 'Deadmines (Heroic)', 16712190, 60, 63, 60, 60, 60, 36, 1, 3, 5, -1, 'DEADMINES', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 350;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (350, 'Gnomeregan (Mythic)', 16712190, 60, 63, 60, 60, 60, 90, 2, 3, 5, -1, 'GNOMEREGAN', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 351;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (351, 'Deadmines (Mythic)', 16712190, 60, 63, 60, 60, 60, 36, 2, 3, 5, -1, 'DEADMINES', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 352;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (352, 'Stormwind Stockade (Mythic)', 16712190, 60, 63, 60, 60, 63, 34, 2, 3, 5, 1, 'STORMWINDSTOCKADES', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 353;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (353, 'Shadowfang Keep (Mythic)', 16712190, 60, 63, 60, 60, 60, 33, 2, 3, 5, -1, 'SHADOWFANGKEEP', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 354;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (354, 'Razorfen Kraul (Mythic)', 16712190, 60, 63, 60, 60, 60, 47, 2, 3, 5, -1, 'RAZORFENKRAUL', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 355;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (355, 'Razorfen Downs (Mythic)', 16712190, 60, 63, 60, 60, 60, 129, 2, 3, 5, -1, 'RAZORFENDOWNS', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 356;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (356, 'Wailing Caverns (Mythic)', 16712190, 60, 63, 60, 60, 60, 43, 2, 3, 5, -1, 'WAILINGCAVERNS', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 357;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (357, 'Ragefire Chasm (Mythic)', 16712190, 60, 63, 60, 60, 60, 389, 2, 3, 5, 0, 'RAGEFIRECHASM', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 358;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (358, 'Blackfathom Deeps (Mythic)', 16712190, 60, 63, 60, 60, 60, 48, 2, 3, 5, -1, 'BLACKFATHOMDEEPS', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 359;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (359, 'Scarlet Monastery - Graveyard (Mythic)', 16712190, 60, 63, 60, 60, 60, 189, 2, 3, 5, -1, 'SCARLETMONASTERY', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 360;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (360, 'Uldaman (Mythic)', 16712190, 60, 63, 60, 60, 60, 70, 2, 3, 5, -1, 'ULDAMAN', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 361;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (361, 'Zul\'Farrak (Mythic)', 16712190, 60, 63, 60, 60, 60, 209, 2, 3, 5, -1, 'ZULFARAK', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 362;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (362, 'Maraudon - Orange Crystals (Mythic)', 16712190, 60, 63, 60, 60, 60, 349, 2, 3, 5, -1, 'MARAUDON', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 363;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (363, 'Sunken Temple (Mythic)', 16712190, 60, 63, 60, 60, 60, 109, 2, 3, 5, -1, 'SUNKENTEMPLE', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 364;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (364, 'Blackrock Depths - Prison (Mythic)', 16712190, 60, 63, 60, 60, 60, 230, 2, 3, 5, -1, 'BLACKROCKDEPTHS', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 365;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (365, 'Lower Blackrock Spire (Mythic)', 16712190, 60, 63, 60, 60, 60, 229, 2, 3, 5, -1, 'BLACKROCKSPIRE', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 366;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (366, 'Dire Maul - East (Mythic)', 16712190, 60, 63, 60, 60, 60, 429, 2, 3, 5, -1, 'DIREMAUL', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 367;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (367, 'Dire Maul - West (Mythic)', 16712190, 60, 63, 60, 60, 60, 429, 2, 3, 5, -1, 'DIREMAUL', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 368;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (368, 'Dire Maul - North (Mythic)', 16712190, 60, 63, 60, 60, 60, 429, 2, 3, 5, -1, 'DIREMAUL', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 369;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (369, 'Stratholme - Main Gate (Mythic)', 16712190, 60, 63, 60, 60, 60, 329, 2, 3, 5, -1, 'STRATHOLME', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 370;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (370, 'Upper Blackrock Spire (Mythic)', 16712190, 60, 63, 60, 60, 60, 229, 2, 3, 5, -1, 'BlackrockSpire', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 371;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (371, 'Scarlet Monastery - Armory (Mythic)', 16712190, 60, 63, 60, 60, 60, 189, 2, 3, 5, -1, 'SCARLETMONASTERY', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 372;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (372, 'Scarlet Monastery - Cathedral  (Mythic)', 16712190, 60, 63, 60, 60, 60, 189, 2, 3, 5, -1, 'SCARLETMONASTERY', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 373;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (373, 'Scarlet Monastery - Library  (Mythic)', 16712190, 60, 63, 60, 60, 60, 189, 2, 3, 5, -1, 'SCARLETMONASTERY', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 374;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (374, 'Maraudon - Purple Crystals  (Mythic)', 16712190, 60, 63, 60, 60, 60, 349, 2, 3, 5, -1, 'MARAUDON', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 375;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (375, 'Maraudon - Pristine Waters (Mythic)', 16712190, 60, 63, 60, 60, 60, 349, 2, 3, 5, -1, 'MARAUDON', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 376;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (376, 'Stratholme - Service Entrance (Mythic)', 16712190, 60, 63, 60, 60, 60, 329, 2, 3, 5, -1, 'STRATHOLME', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 377;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (377, 'Blackrock Depths - Upper City (Mythic)', 16712190, 60, 63, 60, 60, 60, 230, 2, 3, 5, -1, 'BLACKROCKDEPTHS', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 378;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (378, 'Scholomance (Mythic)', 16712190, 60, 63, 60, 60, 60, 289, 2, 3, 5, -1, 'SCHOLOMANCE', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 400;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (400, 'Random Azeroth Dungeon', 16712190, 15, 63, 60, 15, 63, 0, 0, 3, 6, -1, '', 0, 0, 1, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 401;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (401, 'Random Azeroth Heroic', 16712190, 60, 63, 60, 60, 63, 0, 1, 3, 6, -1, '', 0, 0, 12, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 402;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (402, 'Random Outland Dungeon', 16712190, 61, 70, 65, 61, 70, 0, 0, 3, 6, -1, '', 1, 0, 2, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 403;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (403, 'Random Outland Heroic', 16712190, 70, 73, 70, 70, 73, 0, 1, 3, 6, -1, '', 1, 0, 3, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 404;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (404, 'Random Northrend Dungeon', 16712190, 71, 80, 80, 69, 80, 0, 0, 3, 6, -1, '', 2, 0, 4, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 405;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (405, 'Random Northrend Heroic', 16712190, 80, 83, 80, 80, 83, 0, 1, 3, 6, -1, '', 2, 0, 5, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 406;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (406, 'Random Azeroth Mythic', 16712190, 60, 63, 60, 60, 63, 0, 2, 3, 6, -1, '', 0, 0, 13, '', 16712188);
DELETE FROM `lfgdungeons` WHERE `id` = 451;
INSERT INTO `lfgdungeons` (`id`, `name_enus`, `name_flags`, `min_level`, `max_level`, `target_level`, `target_level_min`, `target_level_max`, `map_id`, `difficulty`, `flags`, `type_id`, `faction`, `texture`, `expansion`, `order_id`, `group_id`, `tooltip_enus`, `tooltip_flags`) VALUES (451, 'Naxxramas', 16712190, 60, 60, 60, 60, 60, 533, 2, 0, 2, -1, 'NAXXRAMAS', 0, 0, 6, '', 16712188);
UPDATE `lfgdungeons` SET `max_level` = 60, `target_level_max` = 60 WHERE `id` = 2;
UPDATE `lfgdungeons` SET `min_level` = 42, `max_level` = 52, `target_level` = 45, `target_level_min` = 43, `target_level_max` = 50 WHERE `id` = 22;
UPDATE `lfgdungeons` SET `max_level` = 60 WHERE `id` = 32;
UPDATE `lfgdungeons` SET `max_level` = 60 WHERE `id` = 34;
UPDATE `lfgdungeons` SET `max_level` = 60 WHERE `id` = 36;
UPDATE `lfgdungeons` SET `max_level` = 60 WHERE `id` = 38;
UPDATE `lfgdungeons` SET `max_level` = 60 WHERE `id` = 40;
UPDATE `lfgdungeons` SET `min_level` = 60, `max_level` = 60, `target_level_max` = 60 WHERE `id` = 42;
UPDATE `lfgdungeons` SET `max_level` = 60, `target_level_max` = 60, `flags` = 3, `type_id` = 1, `group_id` = 1 WHERE `id` = 44;
UPDATE `lfgdungeons` SET `max_level` = 60, `target_level_max` = 60 WHERE `id` = 48;
UPDATE `lfgdungeons` SET `max_level` = 60, `target_level_max` = 60 WHERE `id` = 50;
UPDATE `lfgdungeons` SET `min_level` = 61 WHERE `id` = 136;
UPDATE `lfgdungeons` SET `min_level` = 61 WHERE `id` = 137;
UPDATE `lfgdungeons` SET `min_level` = 61 WHERE `id` = 140;
UPDATE `lfgdungeons` SET `max_level` = 60, `target_level_max` = 60 WHERE `id` = 160;
UPDATE `lfgdungeons` SET `max_level` = 60, `target_level_max` = 60 WHERE `id` = 161;
UPDATE `lfgdungeons` SET `name_enus` = 'Auchenai Crypts (Heroic)' WHERE `id` = 178;
UPDATE `lfgdungeons` SET `name_enus` = 'Mana-Tombs (Heroic)' WHERE `id` = 179;
UPDATE `lfgdungeons` SET `name_enus` = 'Sethekk Halls (Heroic)' WHERE `id` = 180;
UPDATE `lfgdungeons` SET `name_enus` = 'Shadow Labyrinth (Heroic)' WHERE `id` = 181;
UPDATE `lfgdungeons` SET `name_enus` = 'The Black Morass (Heroic)' WHERE `id` = 182;
UPDATE `lfgdungeons` SET `name_enus` = 'Slave Pens (Heroic)' WHERE `id` = 184;
UPDATE `lfgdungeons` SET `name_enus` = 'The Steamvault (Heroic)' WHERE `id` = 185;
UPDATE `lfgdungeons` SET `name_enus` = 'Underbog (Heroic)' WHERE `id` = 186;
UPDATE `lfgdungeons` SET `name_enus` = 'Blood Furnace (Heroic)' WHERE `id` = 187;
UPDATE `lfgdungeons` SET `name_enus` = 'Hellfire Ramparts (Heroic)' WHERE `id` = 188;
UPDATE `lfgdungeons` SET `name_enus` = 'Shattered Halls (Heroic)' WHERE `id` = 189;
UPDATE `lfgdungeons` SET `name_enus` = 'The Arcatraz (Heroic)' WHERE `id` = 190;
UPDATE `lfgdungeons` SET `name_enus` = 'The Botanica (Heroic)' WHERE `id` = 191;
UPDATE `lfgdungeons` SET `name_enus` = 'The Mechanar (Heroic)' WHERE `id` = 192;
UPDATE `lfgdungeons` SET `name_enus` = 'Magisters\' Terrace (Heroic)' WHERE `id` = 201;
UPDATE `lfgdungeons` SET `min_level` = 71 WHERE `id` = 202;
UPDATE `lfgdungeons` SET `min_level` = 71 WHERE `id` = 204;
UPDATE `lfgdungeons` SET `name_enus` = 'Utgarde Pinnacle (Heroic)' WHERE `id` = 205;
UPDATE `lfgdungeons` SET `name_enus` = 'The Oculus (Heroic)' WHERE `id` = 211;
UPDATE `lfgdungeons` SET `name_enus` = 'Halls of Lightning (Heroic)' WHERE `id` = 212;
UPDATE `lfgdungeons` SET `name_enus` = 'Halls of Stone (Heroic)' WHERE `id` = 213;
UPDATE `lfgdungeons` SET `name_enus` = 'Drak\'Tharon Keep (Heroic)' WHERE `id` = 215;
UPDATE `lfgdungeons` SET `name_enus` = 'Gundrak (Heroic)' WHERE `id` = 217;
UPDATE `lfgdungeons` SET `name_enus` = 'Ahn\'kahet: The Old Kingdom (Heroic)' WHERE `id` = 219;
UPDATE `lfgdungeons` SET `name_enus` = 'Violet Hold (Heroic)' WHERE `id` = 221;
UPDATE `lfgdungeons` SET `min_level` = 71 WHERE `id` = 225;
UPDATE `lfgdungeons` SET `name_enus` = 'The Nexus (Heroic)' WHERE `id` = 226;
UPDATE `lfgdungeons` SET `min_level` = 71 WHERE `id` = 228;
UPDATE `lfgdungeons` SET `min_level` = 71 WHERE `id` = 229;
UPDATE `lfgdungeons` SET `min_level` = 71 WHERE `id` = 230;
UPDATE `lfgdungeons` SET `name_enus` = 'Azjol-Nerub (Heroic)' WHERE `id` = 241;
UPDATE `lfgdungeons` SET `name_enus` = 'Utgarde Keep (Heroic)' WHERE `id` = 242;
UPDATE `lfgdungeons` SET `name_enus` = 'The Forge of Souls (Heroic)' WHERE `id` = 252;
UPDATE `lfgdungeons` SET `name_enus` = 'Pit of Saron (Heroic)' WHERE `id` = 254;
UPDATE `lfgdungeons` SET `name_enus` = 'Halls of Reflection (Heroic)' WHERE `id` = 256;
UPDATE `lfgdungeons` SET `max_level` = 60 WHERE `id` = 274;
UPDATE `lfgdungeons` SET `max_level` = 60 WHERE `id` = 276;
UPDATE `lfgdungeons` SET `name_enus` = 'Icecrown Citadel (Heroic)' WHERE `id` = 280;