-- [BASE,F-044] zepcraft-legacy: emotestextsound
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-044]_emotestextsound.sql with overrides

-- emotestextsound: 526 inserts, 0 updates, 0 deletes
DELETE FROM `emotestextsound` WHERE `id` = 600;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (600, 304, 23, 0, 19019);
DELETE FROM `emotestextsound` WHERE `id` = 601;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (601, 323, 23, 0, 19025);
DELETE FROM `emotestextsound` WHERE `id` = 602;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (602, 327, 23, 0, 19024);
DELETE FROM `emotestextsound` WHERE `id` = 603;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (603, 19, 23, 0, 19015);
DELETE FROM `emotestextsound` WHERE `id` = 604;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (604, 66, 23, 0, 19022);
DELETE FROM `emotestextsound` WHERE `id` = 605;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (605, 97, 23, 0, 19029);
DELETE FROM `emotestextsound` WHERE `id` = 606;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (606, 325, 23, 0, 19031);
DELETE FROM `emotestextsound` WHERE `id` = 607;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (607, 453, 23, 0, 19033);
DELETE FROM `emotestextsound` WHERE `id` = 608;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (608, 67, 23, 0, 19023);
DELETE FROM `emotestextsound` WHERE `id` = 609;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (609, 183, 23, 0, 19026);
DELETE FROM `emotestextsound` WHERE `id` = 610;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (610, 264, 23, 0, 19030);
DELETE FROM `emotestextsound` WHERE `id` = 611;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (611, 21, 23, 0, 18972);
DELETE FROM `emotestextsound` WHERE `id` = 612;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (612, 305, 23, 0, 18971);
DELETE FROM `emotestextsound` WHERE `id` = 613;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (613, 329, 23, 0, 19028);
DELETE FROM `emotestextsound` WHERE `id` = 614;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (614, 328, 23, 0, 19013);
DELETE FROM `emotestextsound` WHERE `id` = 616;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (616, 26, 9, 0, 19091);
DELETE FROM `emotestextsound` WHERE `id` = 617;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (617, 307, 9, 0, 19086);
DELETE FROM `emotestextsound` WHERE `id` = 618;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (618, 324, 9, 0, 19132);
DELETE FROM `emotestextsound` WHERE `id` = 619;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (619, 326, 9, 0, 19134);
DELETE FROM `emotestextsound` WHERE `id` = 620;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (620, 55, 9, 0, 19135);
DELETE FROM `emotestextsound` WHERE `id` = 621;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (621, 306, 9, 0, 19130);
DELETE FROM `emotestextsound` WHERE `id` = 622;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (622, 303, 9, 0, 19136);
DELETE FROM `emotestextsound` WHERE `id` = 623;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (623, 304, 9, 0, 19137);
DELETE FROM `emotestextsound` WHERE `id` = 624;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (624, 323, 9, 0, 19142);
DELETE FROM `emotestextsound` WHERE `id` = 625;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (625, 327, 9, 0, 19141);
DELETE FROM `emotestextsound` WHERE `id` = 626;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (626, 19, 9, 0, 19133);
DELETE FROM `emotestextsound` WHERE `id` = 627;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (627, 66, 9, 0, 19139);
DELETE FROM `emotestextsound` WHERE `id` = 628;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (628, 97, 9, 0, 19146);
DELETE FROM `emotestextsound` WHERE `id` = 629;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (629, 325, 9, 0, 19148);
DELETE FROM `emotestextsound` WHERE `id` = 630;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (630, 453, 9, 0, 19152);
DELETE FROM `emotestextsound` WHERE `id` = 631;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (631, 67, 9, 0, 19140);
DELETE FROM `emotestextsound` WHERE `id` = 632;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (632, 183, 9, 0, 19143);
DELETE FROM `emotestextsound` WHERE `id` = 633;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (633, 264, 9, 0, 19147);
DELETE FROM `emotestextsound` WHERE `id` = 634;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (634, 21, 9, 0, 19089);
DELETE FROM `emotestextsound` WHERE `id` = 635;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (635, 305, 9, 0, 19088);
DELETE FROM `emotestextsound` WHERE `id` = 636;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (636, 329, 9, 0, 19145);
DELETE FROM `emotestextsound` WHERE `id` = 637;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (637, 328, 9, 0, 19131);
DELETE FROM `emotestextsound` WHERE `id` = 638;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (638, 26, 9, 1, 19199);
DELETE FROM `emotestextsound` WHERE `id` = 639;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (639, 307, 9, 1, 19197);
DELETE FROM `emotestextsound` WHERE `id` = 640;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (640, 324, 9, 1, 19241);
DELETE FROM `emotestextsound` WHERE `id` = 641;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (641, 326, 9, 1, 19243);
DELETE FROM `emotestextsound` WHERE `id` = 642;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (642, 55, 9, 1, 19244);
DELETE FROM `emotestextsound` WHERE `id` = 643;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (643, 306, 9, 1, 19239);
DELETE FROM `emotestextsound` WHERE `id` = 644;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (644, 303, 9, 1, 19245);
DELETE FROM `emotestextsound` WHERE `id` = 645;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (645, 304, 9, 1, 19246);
DELETE FROM `emotestextsound` WHERE `id` = 646;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (646, 323, 9, 1, 19252);
DELETE FROM `emotestextsound` WHERE `id` = 647;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (647, 327, 9, 1, 19251);
DELETE FROM `emotestextsound` WHERE `id` = 648;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (648, 19, 9, 1, 19242);
DELETE FROM `emotestextsound` WHERE `id` = 649;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (649, 66, 9, 1, 19249);
DELETE FROM `emotestextsound` WHERE `id` = 650;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (650, 97, 9, 1, 19256);
DELETE FROM `emotestextsound` WHERE `id` = 651;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (651, 325, 9, 1, 19258);
DELETE FROM `emotestextsound` WHERE `id` = 652;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (652, 453, 9, 1, 19260);
DELETE FROM `emotestextsound` WHERE `id` = 653;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (653, 67, 9, 1, 19250);
DELETE FROM `emotestextsound` WHERE `id` = 654;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (654, 183, 9, 1, 19253);
DELETE FROM `emotestextsound` WHERE `id` = 655;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (655, 264, 9, 1, 19257);
DELETE FROM `emotestextsound` WHERE `id` = 656;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (656, 21, 9, 1, 19202);
DELETE FROM `emotestextsound` WHERE `id` = 657;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (657, 305, 9, 1, 19198);
DELETE FROM `emotestextsound` WHERE `id` = 658;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (658, 329, 9, 1, 19255);
DELETE FROM `emotestextsound` WHERE `id` = 659;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (659, 328, 9, 1, 19240);
DELETE FROM `emotestextsound` WHERE `id` = 660;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (660, 26, 12, 0, 19299);
DELETE FROM `emotestextsound` WHERE `id` = 661;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (661, 307, 12, 0, 19295);
DELETE FROM `emotestextsound` WHERE `id` = 662;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (662, 324, 12, 0, 19339);
DELETE FROM `emotestextsound` WHERE `id` = 663;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (663, 326, 12, 0, 19341);
DELETE FROM `emotestextsound` WHERE `id` = 664;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (664, 55, 12, 0, 19343);
DELETE FROM `emotestextsound` WHERE `id` = 665;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (665, 306, 12, 0, 19337);
DELETE FROM `emotestextsound` WHERE `id` = 666;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (666, 303, 12, 0, 19344);
DELETE FROM `emotestextsound` WHERE `id` = 667;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (667, 304, 12, 0, 19346);
DELETE FROM `emotestextsound` WHERE `id` = 668;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (668, 323, 12, 0, 19352);
DELETE FROM `emotestextsound` WHERE `id` = 669;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (669, 327, 12, 0, 19351);
DELETE FROM `emotestextsound` WHERE `id` = 670;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (670, 19, 12, 0, 19340);
DELETE FROM `emotestextsound` WHERE `id` = 671;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (671, 66, 12, 0, 19349);
DELETE FROM `emotestextsound` WHERE `id` = 672;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (672, 97, 12, 0, 19356);
DELETE FROM `emotestextsound` WHERE `id` = 673;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (673, 325, 12, 0, 19358);
DELETE FROM `emotestextsound` WHERE `id` = 674;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (674, 453, 12, 0, 19360);
DELETE FROM `emotestextsound` WHERE `id` = 675;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (675, 67, 12, 0, 19350);
DELETE FROM `emotestextsound` WHERE `id` = 676;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (676, 183, 12, 0, 19353);
DELETE FROM `emotestextsound` WHERE `id` = 677;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (677, 21, 12, 0, 19296);
DELETE FROM `emotestextsound` WHERE `id` = 678;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (678, 329, 12, 0, 19355);
DELETE FROM `emotestextsound` WHERE `id` = 679;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (679, 328, 12, 0, 19338);
DELETE FROM `emotestextsound` WHERE `id` = 680;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (680, 26, 12, 1, 19378);
DELETE FROM `emotestextsound` WHERE `id` = 681;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (681, 307, 12, 1, 19366);
DELETE FROM `emotestextsound` WHERE `id` = 682;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (682, 324, 12, 1, 19429);
DELETE FROM `emotestextsound` WHERE `id` = 683;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (683, 326, 12, 1, 19433);
DELETE FROM `emotestextsound` WHERE `id` = 684;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (684, 55, 12, 1, 19434);
DELETE FROM `emotestextsound` WHERE `id` = 685;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (685, 306, 12, 1, 19426);
DELETE FROM `emotestextsound` WHERE `id` = 686;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (686, 303, 12, 1, 19435);
DELETE FROM `emotestextsound` WHERE `id` = 687;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (687, 323, 12, 1, 19440);
DELETE FROM `emotestextsound` WHERE `id` = 688;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (688, 327, 12, 1, 19439);
DELETE FROM `emotestextsound` WHERE `id` = 689;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (689, 19, 12, 1, 19431);
DELETE FROM `emotestextsound` WHERE `id` = 690;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (690, 66, 12, 1, 19437);
DELETE FROM `emotestextsound` WHERE `id` = 691;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (691, 97, 12, 1, 19443);
DELETE FROM `emotestextsound` WHERE `id` = 692;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (692, 325, 12, 1, 19446);
DELETE FROM `emotestextsound` WHERE `id` = 693;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (693, 453, 12, 1, 19450);
DELETE FROM `emotestextsound` WHERE `id` = 694;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (694, 67, 12, 1, 19438);
DELETE FROM `emotestextsound` WHERE `id` = 695;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (695, 305, 12, 1, 19373);
DELETE FROM `emotestextsound` WHERE `id` = 696;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (696, 329, 12, 1, 19441);
DELETE FROM `emotestextsound` WHERE `id` = 697;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (697, 328, 12, 1, 19428);
DELETE FROM `emotestextsound` WHERE `id` = 698;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (698, 304, 12, 1, 19516);
DELETE FROM `emotestextsound` WHERE `id` = 699;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (699, 21, 12, 1, 19517);
DELETE FROM `emotestextsound` WHERE `id` = 700;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (700, 305, 12, 0, 19296);
DELETE FROM `emotestextsound` WHERE `id` = 701;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (701, 102, 23, 0, 19017);
DELETE FROM `emotestextsound` WHERE `id` = 702;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (702, 102, 12, 0, 19343);
DELETE FROM `emotestextsound` WHERE `id` = 703;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (703, 102, 12, 1, 19434);
DELETE FROM `emotestextsound` WHERE `id` = 704;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (704, 102, 9, 1, 19244);
DELETE FROM `emotestextsound` WHERE `id` = 705;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (705, 102, 9, 0, 19135);
DELETE FROM `emotestextsound` WHERE `id` = 706;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (706, 264, 12, 0, 19357);
DELETE FROM `emotestextsound` WHERE `id` = 707;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (707, 264, 12, 1, 19445);
DELETE FROM `emotestextsound` WHERE `id` = 708;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (708, 307, 23, 0, 23329);
DELETE FROM `emotestextsound` WHERE `id` = 709;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (709, 307, 23, 1, 23328);
DELETE FROM `emotestextsound` WHERE `id` = 716;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (716, 75, 12, 0, 21448);
DELETE FROM `emotestextsound` WHERE `id` = 717;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (717, 75, 9, 0, 19144);
DELETE FROM `emotestextsound` WHERE `id` = 718;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (718, 75, 12, 1, 22449);
DELETE FROM `emotestextsound` WHERE `id` = 719;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (719, 75, 9, 1, 19254);
DELETE FROM `emotestextsound` WHERE `id` = 720;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (720, 75, 23, 0, 19027);
DELETE FROM `emotestextsound` WHERE `id` = 721;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (721, 75, 23, 1, 18777);
DELETE FROM `emotestextsound` WHERE `id` = 722;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (722, 75, 3, 1, 25251);
DELETE FROM `emotestextsound` WHERE `id` = 723;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (723, 75, 3, 0, 25252);
DELETE FROM `emotestextsound` WHERE `id` = 724;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (724, 75, 7, 1, 25253);
DELETE FROM `emotestextsound` WHERE `id` = 725;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (725, 75, 7, 0, 25254);
DELETE FROM `emotestextsound` WHERE `id` = 726;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (726, 75, 1, 1, 25255);
DELETE FROM `emotestextsound` WHERE `id` = 727;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (727, 75, 1, 0, 25256);
DELETE FROM `emotestextsound` WHERE `id` = 728;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (728, 75, 4, 1, 25257);
DELETE FROM `emotestextsound` WHERE `id` = 729;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (729, 75, 4, 0, 25258);
DELETE FROM `emotestextsound` WHERE `id` = 730;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (730, 75, 2, 1, 25259);
DELETE FROM `emotestextsound` WHERE `id` = 731;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (731, 75, 2, 0, 25260);
DELETE FROM `emotestextsound` WHERE `id` = 732;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (732, 75, 6, 1, 25261);
DELETE FROM `emotestextsound` WHERE `id` = 733;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (733, 75, 6, 0, 25262);
DELETE FROM `emotestextsound` WHERE `id` = 734;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (734, 75, 8, 1, 25263);
DELETE FROM `emotestextsound` WHERE `id` = 735;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (735, 75, 8, 0, 25264);
DELETE FROM `emotestextsound` WHERE `id` = 736;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (736, 75, 5, 1, 25265);
DELETE FROM `emotestextsound` WHERE `id` = 737;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (737, 75, 5, 0, 25266);
DELETE FROM `emotestextsound` WHERE `id` = 738;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (738, 75, 10, 0, 25268);
DELETE FROM `emotestextsound` WHERE `id` = 739;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (739, 75, 10, 1, 25267);
DELETE FROM `emotestextsound` WHERE `id` = 740;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (740, 75, 11, 0, 25270);
DELETE FROM `emotestextsound` WHERE `id` = 741;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (741, 75, 11, 1, 25269);
DELETE FROM `emotestextsound` WHERE `id` = 742;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (742, 60, 4, 1, 6928);
DELETE FROM `emotestextsound` WHERE `id` = 743;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (743, 60, 4, 0, 6933);
DELETE FROM `emotestextsound` WHERE `id` = 744;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (744, 60, 10, 0, 9652);
DELETE FROM `emotestextsound` WHERE `id` = 745;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (745, 60, 10, 1, 9648);
DELETE FROM `emotestextsound` WHERE `id` = 746;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (746, 60, 11, 0, 9702);
DELETE FROM `emotestextsound` WHERE `id` = 747;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (747, 60, 11, 1, 9677);
DELETE FROM `emotestextsound` WHERE `id` = 748;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (748, 60, 3, 1, 6894);
DELETE FROM `emotestextsound` WHERE `id` = 749;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (749, 60, 3, 0, 6903);
DELETE FROM `emotestextsound` WHERE `id` = 750;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (750, 60, 7, 0, 6913);
DELETE FROM `emotestextsound` WHERE `id` = 751;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (751, 60, 7, 1, 6908);
DELETE FROM `emotestextsound` WHERE `id` = 752;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (752, 60, 1, 1, 6918);
DELETE FROM `emotestextsound` WHERE `id` = 753;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (753, 60, 1, 0, 6923);
DELETE FROM `emotestextsound` WHERE `id` = 754;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (754, 60, 2, 0, 6943);
DELETE FROM `emotestextsound` WHERE `id` = 755;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (755, 60, 2, 1, 6938);
DELETE FROM `emotestextsound` WHERE `id` = 756;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (756, 60, 6, 1, 6948);
DELETE FROM `emotestextsound` WHERE `id` = 757;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (757, 60, 6, 0, 6953);
DELETE FROM `emotestextsound` WHERE `id` = 758;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (758, 60, 8, 1, 6958);
DELETE FROM `emotestextsound` WHERE `id` = 759;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (759, 60, 8, 0, 6963);
DELETE FROM `emotestextsound` WHERE `id` = 760;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (760, 60, 5, 1, 6969);
DELETE FROM `emotestextsound` WHERE `id` = 761;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (761, 60, 5, 0, 6974);
DELETE FROM `emotestextsound` WHERE `id` = 762;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (762, 60, 23, 1, 18770);
DELETE FROM `emotestextsound` WHERE `id` = 763;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (763, 60, 23, 0, 19021);
DELETE FROM `emotestextsound` WHERE `id` = 765;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (765, 60, 12, 1, 23319);
DELETE FROM `emotestextsound` WHERE `id` = 766;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (766, 60, 9, 1, 19248);
DELETE FROM `emotestextsound` WHERE `id` = 767;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (767, 60, 9, 0, 23330);
DELETE FROM `emotestextsound` WHERE `id` = 768;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (768, 31, 10, 1, 9647);
DELETE FROM `emotestextsound` WHERE `id` = 769;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (769, 31, 10, 0, 9651);
DELETE FROM `emotestextsound` WHERE `id` = 770;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (770, 31, 11, 1, 9676);
DELETE FROM `emotestextsound` WHERE `id` = 771;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (771, 31, 11, 0, 9701);
DELETE FROM `emotestextsound` WHERE `id` = 772;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (772, 31, 3, 1, 6895);
DELETE FROM `emotestextsound` WHERE `id` = 773;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (773, 31, 3, 0, 6901);
DELETE FROM `emotestextsound` WHERE `id` = 774;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (774, 31, 7, 1, 6906);
DELETE FROM `emotestextsound` WHERE `id` = 775;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (775, 31, 7, 0, 6911);
DELETE FROM `emotestextsound` WHERE `id` = 776;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (776, 31, 1, 1, 6916);
DELETE FROM `emotestextsound` WHERE `id` = 777;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (777, 31, 1, 0, 6921);
DELETE FROM `emotestextsound` WHERE `id` = 778;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (778, 31, 4, 1, 6926);
DELETE FROM `emotestextsound` WHERE `id` = 779;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (779, 31, 4, 0, 6931);
DELETE FROM `emotestextsound` WHERE `id` = 780;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (780, 31, 2, 1, 6936);
DELETE FROM `emotestextsound` WHERE `id` = 781;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (781, 31, 2, 0, 6941);
DELETE FROM `emotestextsound` WHERE `id` = 782;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (782, 31, 6, 1, 6946);
DELETE FROM `emotestextsound` WHERE `id` = 783;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (783, 31, 6, 0, 6951);
DELETE FROM `emotestextsound` WHERE `id` = 784;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (784, 31, 8, 1, 6956);
DELETE FROM `emotestextsound` WHERE `id` = 785;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (785, 31, 8, 0, 6961);
DELETE FROM `emotestextsound` WHERE `id` = 786;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (786, 31, 5, 1, 6967);
DELETE FROM `emotestextsound` WHERE `id` = 787;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (787, 31, 5, 0, 6972);
DELETE FROM `emotestextsound` WHERE `id` = 788;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (788, 31, 23, 1, 18648);
DELETE FROM `emotestextsound` WHERE `id` = 789;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (789, 31, 23, 0, 18975);
DELETE FROM `emotestextsound` WHERE `id` = 790;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (790, 31, 12, 1, 23321);
DELETE FROM `emotestextsound` WHERE `id` = 791;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (791, 31, 12, 0, 23326);
DELETE FROM `emotestextsound` WHERE `id` = 792;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (792, 31, 9, 1, 19200);
DELETE FROM `emotestextsound` WHERE `id` = 793;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (793, 31, 9, 0, 19092);
DELETE FROM `emotestextsound` WHERE `id` = 794;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (794, 22, 10, 1, 9646);
DELETE FROM `emotestextsound` WHERE `id` = 795;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (795, 22, 10, 0, 9650);
DELETE FROM `emotestextsound` WHERE `id` = 796;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (796, 22, 11, 1, 9675);
DELETE FROM `emotestextsound` WHERE `id` = 797;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (797, 22, 11, 0, 9700);
DELETE FROM `emotestextsound` WHERE `id` = 798;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (798, 22, 3, 1, 6896);
DELETE FROM `emotestextsound` WHERE `id` = 799;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (799, 22, 3, 0, 6899);
DELETE FROM `emotestextsound` WHERE `id` = 800;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (800, 22, 7, 1, 6904);
DELETE FROM `emotestextsound` WHERE `id` = 801;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (801, 22, 7, 0, 6909);
DELETE FROM `emotestextsound` WHERE `id` = 802;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (802, 22, 1, 1, 6914);
DELETE FROM `emotestextsound` WHERE `id` = 803;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (803, 22, 1, 0, 6919);
DELETE FROM `emotestextsound` WHERE `id` = 804;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (804, 22, 4, 1, 6924);
DELETE FROM `emotestextsound` WHERE `id` = 805;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (805, 22, 4, 0, 6929);
DELETE FROM `emotestextsound` WHERE `id` = 806;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (806, 22, 2, 1, 6934);
DELETE FROM `emotestextsound` WHERE `id` = 807;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (807, 22, 2, 0, 6939);
DELETE FROM `emotestextsound` WHERE `id` = 808;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (808, 22, 6, 1, 6944);
DELETE FROM `emotestextsound` WHERE `id` = 809;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (809, 22, 6, 0, 6949);
DELETE FROM `emotestextsound` WHERE `id` = 810;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (810, 22, 8, 1, 6954);
DELETE FROM `emotestextsound` WHERE `id` = 811;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (811, 22, 8, 0, 6959);
DELETE FROM `emotestextsound` WHERE `id` = 812;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (812, 22, 5, 1, 6965);
DELETE FROM `emotestextsound` WHERE `id` = 813;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (813, 22, 5, 0, 6970);
DELETE FROM `emotestextsound` WHERE `id` = 814;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (814, 22, 23, 1, 18645);
DELETE FROM `emotestextsound` WHERE `id` = 815;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (815, 22, 23, 0, 18973);
DELETE FROM `emotestextsound` WHERE `id` = 816;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (816, 22, 12, 1, 23322);
DELETE FROM `emotestextsound` WHERE `id` = 817;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (817, 22, 12, 0, 23327);
DELETE FROM `emotestextsound` WHERE `id` = 818;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (818, 22, 9, 1, 19201);
DELETE FROM `emotestextsound` WHERE `id` = 819;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (819, 22, 9, 0, 19090);
DELETE FROM `emotestextsound` WHERE `id` = 820;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (820, 136, 10, 1, 9646);
DELETE FROM `emotestextsound` WHERE `id` = 821;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (821, 136, 10, 0, 9650);
DELETE FROM `emotestextsound` WHERE `id` = 822;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (822, 136, 11, 1, 9675);
DELETE FROM `emotestextsound` WHERE `id` = 823;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (823, 136, 11, 0, 9700);
DELETE FROM `emotestextsound` WHERE `id` = 824;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (824, 136, 3, 1, 6896);
DELETE FROM `emotestextsound` WHERE `id` = 825;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (825, 136, 3, 0, 6899);
DELETE FROM `emotestextsound` WHERE `id` = 826;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (826, 136, 7, 1, 6904);
DELETE FROM `emotestextsound` WHERE `id` = 827;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (827, 136, 7, 0, 6909);
DELETE FROM `emotestextsound` WHERE `id` = 828;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (828, 136, 1, 1, 6914);
DELETE FROM `emotestextsound` WHERE `id` = 829;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (829, 136, 1, 0, 6919);
DELETE FROM `emotestextsound` WHERE `id` = 830;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (830, 136, 4, 0, 6929);
DELETE FROM `emotestextsound` WHERE `id` = 831;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (831, 136, 2, 1, 6934);
DELETE FROM `emotestextsound` WHERE `id` = 832;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (832, 136, 2, 0, 6939);
DELETE FROM `emotestextsound` WHERE `id` = 833;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (833, 136, 6, 1, 6944);
DELETE FROM `emotestextsound` WHERE `id` = 834;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (834, 136, 6, 0, 6949);
DELETE FROM `emotestextsound` WHERE `id` = 835;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (835, 136, 8, 1, 6954);
DELETE FROM `emotestextsound` WHERE `id` = 836;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (836, 136, 8, 0, 6959);
DELETE FROM `emotestextsound` WHERE `id` = 837;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (837, 136, 5, 1, 6965);
DELETE FROM `emotestextsound` WHERE `id` = 838;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (838, 136, 5, 0, 6970);
DELETE FROM `emotestextsound` WHERE `id` = 839;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES (839, 136, 23, 1, 18645);
