-- [BASE,F-044] zepcraft-legacy: achievement_criteria
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-044]_achievement_criteria.sql with overrides

-- achievement_criteria: 48 inserts, 2 updates, 0 deletes
DELETE FROM `achievement_criteria` WHERE `id` = 13471;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13471, 246, 53, 9, 1, 0, 0, 0, 0, 'Goblin', 16712190, 0, 0, 0, 0, 6);
DELETE FROM `achievement_criteria` WHERE `id` = 13472;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13472, 1005, 53, 12, 1, 0, 0, 0, 0, 'Worgen', 16712190, 0, 0, 0, 0, 6);
DELETE FROM `achievement_criteria` WHERE `id` = 13473;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13473, 2422, 110, 61815, 1, 0, 0, 0, 0, 'Goblin', 16712190, 0, 0, 0, 0, 11);
DELETE FROM `achievement_criteria` WHERE `id` = 13474;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13474, 2422, 110, 61815, 1, 0, 0, 0, 0, 'Worgen', 16712190, 0, 0, 0, 0, 12);
DELETE FROM `achievement_criteria` WHERE `id` = 13475;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13475, 291, 110, 44212, 1, 0, 0, 0, 0, 'Goblin', 16712190, 0, 0, 0, 0, 11);
DELETE FROM `achievement_criteria` WHERE `id` = 13476;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13476, 291, 110, 44212, 1, 0, 0, 0, 0, 'Worgen', 16712190, 0, 0, 0, 0, 12);
DELETE FROM `achievement_criteria` WHERE `id` = 13477;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13477, 1429, 5, 80, 0, 0, 0, 0, 0, 'Level to 80', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13478;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13478, 1430, 5, 80, 0, 0, 0, 0, 0, 'Level to 80', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13500;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13500, 5000, 0, 4275, 1, 0, 0, 0, 0, 'Archmage Arugal', 16712190, 0, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13501;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13501, 5001, 0, 1716, 1, 0, 0, 0, 0, 'Bazil Thredd', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13502;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13502, 5002, 0, 7358, 1, 0, 0, 0, 0, 'Amnennar the Coldbringer', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13503;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13503, 5003, 0, 4421, 1, 0, 0, 0, 0, 'Charlga Razorflank', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13504;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13504, 5004, 0, 5775, 1, 0, 0, 0, 0, 'Verdan the Everliving', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13505;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13505, 5005, 0, 11518, 1, 0, 0, 0, 0, 'Jergosh the Invoker', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13506;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13506, 5006, 0, 639, 1, 0, 0, 0, 0, 'Edwin VanCleef', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13507;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13507, 5007, 0, 7267, 1, 0, 0, 0, 0, 'Chief Ukorz Sandscalp', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13508;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13508, 5008, 0, 7800, 1, 0, 0, 0, 0, 'Mekgineer Thermaplugg', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13509;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13509, 5009, 0, 9019, 1, 0, 0, 0, 0, 'Emperor Dagran Thaurissan', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13510;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13510, 5010, 0, 10363, 1, 0, 0, 0, 0, 'General Drakkisath', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13511;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13511, 5011, 0, 9568, 1, 0, 0, 0, 0, 'Overlord Wyrmthalak', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13512;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13512, 5012, 0, 4829, 1, 0, 0, 0, 0, 'Aku\'mai', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13513;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13513, 5013, 0, 3977, 1, 0, 0, 0, 0, 'High Inquisitor Whitemane', 16712190, 0, 0, 0, 0, 5);
DELETE FROM `achievement_criteria` WHERE `id` = 13514;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13514, 5014, 0, 2748, 1, 0, 0, 0, 0, 'Archaedas', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13515;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13515, 5015, 0, 12201, 1, 0, 0, 0, 0, 'Princess Theradras', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13516;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13516, 5016, 0, 5709, 1, 0, 0, 0, 0, 'Shade of Eranikus', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13517;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13517, 5017, 0, 1853, 1, 0, 0, 0, 0, 'Darkmaster Gandling', 16712190, 0, 0, 0, 0, 2);
DELETE FROM `achievement_criteria` WHERE `id` = 13518;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13518, 5018, 0, 10440, 1, 0, 0, 0, 0, 'Baron Rivendare', 16712190, 0, 0, 0, 0, 2);
DELETE FROM `achievement_criteria` WHERE `id` = 13519;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13519, 5019, 0, 11501, 1, 0, 0, 0, 0, 'King Gordok', 16712190, 0, 0, 0, 0, 3);
DELETE FROM `achievement_criteria` WHERE `id` = 13600;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13600, 5100, 0, 639, 1, 0, 0, 0, 0, 'Edwin VanCleef', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13601;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13601, 5101, 0, 7800, 1, 0, 0, 0, 0, 'Mekgineer Thermaplugg', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13602;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13602, 5102, 0, 4275, 1, 0, 0, 0, 0, 'Archmage Arugal', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13603;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13603, 5103, 0, 11518, 1, 0, 0, 0, 0, 'Jergosh the Invoker', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13604;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13604, 5104, 0, 7358, 1, 0, 0, 0, 0, 'Amnennar the Coldbringer', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13605;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13605, 5105, 0, 4421, 1, 0, 0, 0, 0, 'Charlga Razorflank', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13606;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13606, 5106, 0, 1716, 1, 0, 0, 0, 0, 'Bazil Thredd', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13607;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13607, 5107, 0, 5775, 1, 0, 0, 0, 0, 'Verdan the Everliving', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13608;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13608, 5108, 0, 9019, 1, 0, 0, 0, 0, 'Emperor Dagran Thaurissan', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13609;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13609, 5109, 0, 10363, 1, 0, 0, 0, 0, 'General Drakkisath', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13610;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13610, 5110, 0, 9568, 1, 0, 0, 0, 0, 'Overlord Wyrmthalak', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13611;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13611, 5111, 0, 4829, 1, 0, 0, 0, 0, 'Aku\'mai', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13612;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13612, 5112, 0, 3977, 1, 0, 0, 0, 0, 'High Inquisitor Whitemane', 16712190, 0, 0, 0, 0, 5);
DELETE FROM `achievement_criteria` WHERE `id` = 13613;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13613, 5113, 0, 7267, 1, 0, 0, 0, 0, 'Chief Ukorz Sandscalp', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13614;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13614, 5114, 0, 2748, 1, 0, 0, 0, 0, 'Archaedas', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13615;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13615, 5115, 0, 12201, 1, 0, 0, 0, 0, 'Princess Theradras', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13616;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13616, 5116, 0, 5709, 1, 0, 0, 0, 0, 'Shade of Eranikus', 16712190, 2, 0, 0, 0, 1);
DELETE FROM `achievement_criteria` WHERE `id` = 13617;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13617, 5117, 0, 1853, 1, 0, 0, 0, 0, 'Darkmaster Gandling', 16712190, 0, 0, 0, 0, 2);
DELETE FROM `achievement_criteria` WHERE `id` = 13618;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13618, 5118, 0, 10440, 1, 0, 0, 0, 0, 'Baron Rivendare', 16712190, 0, 0, 0, 0, 2);
DELETE FROM `achievement_criteria` WHERE `id` = 13619;
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13619, 5119, 0, 11501, 1, 0, 0, 0, 0, 'King Gordok', 16712190, 0, 0, 0, 0, 3);
UPDATE `achievement_criteria` SET `req_asset_id` = 11518, `desc_enus` = 'Jergosh the Invoker' WHERE `id` = 525;
UPDATE `achievement_criteria` SET `req_asset_id` = 5775, `desc_enus` = 'Verdan the Everliving' WHERE `id` = 526;