-- [BASE,F-044] zepcraft-legacy: loadingscreens
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-044]_loadingscreens.sql with overrides

-- loadingscreens: 13 inserts, 87 updates, 0 deletes
DELETE FROM `loadingscreens` WHERE `id` = 5;
INSERT INTO `loadingscreens` (`id`, `name`, `file_name`, `has_wide_screen`) VALUES (5, 'InstanceEmeraldDream', 'Interface\\Glues\\LoadingScreens\\LoadScreenEmeraldDream.blp', 1);
DELETE FROM `loadingscreens` WHERE `id` = 6;
INSERT INTO `loadingscreens` (`id`, `name`, `file_name`, `has_wide_screen`) VALUES (6, 'InstanceDevelopmentLand', 'Interface\\Glues\\LoadingScreens\\LoadScreenDevelopmentLand.blp', 1);
DELETE FROM `loadingscreens` WHERE `id` = 7;
INSERT INTO `loadingscreens` (`id`, `name`, `file_name`, `has_wide_screen`) VALUES (7, 'InstanceAzsharaCrater', 'Interface\\Glues\\LoadingScreens\\LoadScreenAzsharaCrater.blp', 1);
DELETE FROM `loadingscreens` WHERE `id` = 255;
INSERT INTO `loadingscreens` (`id`, `name`, `file_name`, `has_wide_screen`) VALUES (255, 'InstanceCoTHyjal', 'Interface\\Glues\\LoadingScreens\\LoadScreenHyjal.blp', 1);
DELETE FROM `loadingscreens` WHERE `id` = 257;
INSERT INTO `loadingscreens` (`id`, `name`, `file_name`, `has_wide_screen`) VALUES (257, 'InstanceCoTOpening', 'Interface\\Glues\\LoadingScreens\\LoadScreenOpening.blp', 1);
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 21;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 23;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 25;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 42;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 61;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 81;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 82;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 101;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 102;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 103;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 104;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 122;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 141;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 142;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 143;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 144;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 145;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 146;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 161;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 181;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 182;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 183;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 184;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 185;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 186;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 187;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 188;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 189;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 190;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 191;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 192;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 193;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 194;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 195;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 196;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 197;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 199;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 200;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 201;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 202;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 203;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 204;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 205;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 206;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 207;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 208;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 209;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 210;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 212;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 213;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 214;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 215;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 217;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 218;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 219;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 220;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 221;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 222;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 223;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 224;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 225;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 226;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 227;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 228;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 229;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 230;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 231;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 232;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 233;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 234;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 235;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 236;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 237;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 238;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 239;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 240;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 242;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 243;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 244;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 245;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 246;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 247;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 249;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 250;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 252;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 253;
UPDATE `loadingscreens` SET `has_wide_screen` = 1 WHERE `id` = 254;