-- Auto-generated by terrain fix (I-170)
-- Zone: Un'Goro Crater, Type: gameobject, Count: 113
-- Moves off-mesh spawns to nearest walkable navmesh point

-- Blue Power Crystal (guid 17360, entry 164778) — moved 5.2 yds
UPDATE `gameobject` SET `position_x` = -6924.533700, `position_y` = -2479.200000, `position_z` = -178.645100 WHERE `guid` = 17360;
-- .go xyz -6924.5 -2479.2 -178.6 1
-- .gobject add temp 164778

-- Un'Goro Flat Rock (guid 17500, entry 169217) — moved 3.5 yds
UPDATE `gameobject` SET `position_x` = -7197.649900, `position_y` = -2423.590100, `position_z` = -216.483700 WHERE `guid` = 17500;
-- .go xyz -7197.6 -2423.6 -216.5 1
-- .gobject add temp 169217

-- Fire Plume Ridge Hot Spot (guid 17501, entry 148503) — moved 6.5 yds
UPDATE `gameobject` SET `position_x` = -7146.666500, `position_y` = -1465.100000, `position_z` = -238.862000 WHERE `guid` = 17501;
-- .go xyz -7146.7 -1465.1 -238.9 1
-- .gobject add temp 148503

-- Fire Plume Ridge Hot Spot (guid 17503, entry 148503) — moved 3.1 yds
UPDATE `gameobject` SET `position_x` = -7165.948700, `position_y` = -1148.354100, `position_z` = -263.923800 WHERE `guid` = 17503;
-- .go xyz -7165.9 -1148.4 -263.9 1
-- .gobject add temp 148503

-- Blue Power Crystal (guid 17510, entry 164658) — moved 5.8 yds
UPDATE `gameobject` SET `position_x` = -7200.990200, `position_y` = -234.666700, `position_z` = -217.221300 WHERE `guid` = 17510;
-- .go xyz -7201.0 -234.7 -217.2 1
-- .gobject add temp 164658

-- Blue Power Crystal (guid 17514, entry 164658) — moved 3.2 yds
UPDATE `gameobject` SET `position_x` = -7530.666500, `position_y` = -605.401000, `position_z` = -264.578200 WHERE `guid` = 17514;
-- .go xyz -7530.7 -605.4 -264.6 1
-- .gobject add temp 164658

-- Green Power Crystal (guid 17529, entry 164659) — moved 3.8 yds
UPDATE `gameobject` SET `position_x` = -7023.782700, `position_y` = -351.801800, `position_z` = -252.390800 WHERE `guid` = 17529;
-- .go xyz -7023.8 -351.8 -252.4 1
-- .gobject add temp 164659

-- Green Power Crystal (guid 17533, entry 164659) — moved 5.2 yds
UPDATE `gameobject` SET `position_x` = -6924.533700, `position_y` = -2479.200000, `position_z` = -178.645100 WHERE `guid` = 17533;
-- .go xyz -6924.5 -2479.2 -178.6 1
-- .gobject add temp 164659

-- Green Power Crystal (guid 17537, entry 164659) — moved 10.6 yds
UPDATE `gameobject` SET `position_x` = -6666.933600, `position_y` = -2324.533200, `position_z` = -172.778500 WHERE `guid` = 17537;
-- .go xyz -6666.9 -2324.5 -172.8 1
-- .gobject add temp 164659

-- Green Power Crystal (guid 17540, entry 164659) — moved 8.1 yds
UPDATE `gameobject` SET `position_x` = -7604.000000, `position_y` = -858.933300, `position_z` = -264.793500 WHERE `guid` = 17540;
-- .go xyz -7604.0 -858.9 -264.8 1
-- .gobject add temp 164659

-- Green Power Crystal (guid 17545, entry 164659) — moved 8.9 yds
UPDATE `gameobject` SET `position_x` = -8085.333000, `position_y` = -1045.333300, `position_z` = -251.993500 WHERE `guid` = 17545;
-- .go xyz -8085.3 -1045.3 -252.0 1
-- .gobject add temp 164659

-- Red Power Crystal (guid 17553, entry 164660) — moved 5.2 yds
UPDATE `gameobject` SET `position_x` = -6921.790500, `position_y` = -196.879000, `position_z` = -179.941200 WHERE `guid` = 17553;
-- .go xyz -6921.8 -196.9 -179.9 1
-- .gobject add temp 164660

-- Yellow Power Crystal (guid 17568, entry 164661) — moved 5.5 yds
UPDATE `gameobject` SET `position_x` = -7701.333000, `position_y` = -482.514000, `position_z` = -260.944500 WHERE `guid` = 17568;
-- .go xyz -7701.3 -482.5 -260.9 1
-- .gobject add temp 164661

-- Yellow Power Crystal (guid 17569, entry 164661) — moved 4.1 yds
UPDATE `gameobject` SET `position_x` = -7971.040000, `position_y` = -618.900000, `position_z` = -235.852000 WHERE `guid` = 17569;
-- .go xyz -7971.0 -618.9 -235.9 1
-- .gobject add temp 164661

-- Yellow Power Crystal (guid 17570, entry 164661) — moved 5.2 yds
UPDATE `gameobject` SET `position_x` = -6485.333500, `position_y` = -2138.649900, `position_z` = -241.177700 WHERE `guid` = 17570;
-- .go xyz -6485.3 -2138.6 -241.2 1
-- .gobject add temp 164661

-- Yellow Power Crystal (guid 17573, entry 164661) — moved 8.0 yds
UPDATE `gameobject` SET `position_x` = -6337.866700, `position_y` = -1729.333300, `position_z` = -238.963600 WHERE `guid` = 17573;
-- .go xyz -6337.9 -1729.3 -239.0 1
-- .gobject add temp 164661

-- Yellow Power Crystal (guid 17575, entry 164661) — moved 3.6 yds
UPDATE `gameobject` SET `position_x` = -7420.759800, `position_y` = -341.333300, `position_z` = -227.236400 WHERE `guid` = 17575;
-- .go xyz -7420.8 -341.3 -227.2 1
-- .gobject add temp 164661

-- Yellow Power Crystal (guid 17581, entry 164661) — moved 3.1 yds
UPDATE `gameobject` SET `position_x` = -7197.432600, `position_y` = -2444.175800, `position_z` = -216.373600 WHERE `guid` = 17581;
-- .go xyz -7197.4 -2444.2 -216.4 1
-- .gobject add temp 164661

-- Western Crystal Pylon (guid 17599, entry 164956) — moved 9.6 yds
UPDATE `gameobject` SET `position_x` = -7418.983400, `position_y` = -354.086100, `position_z` = -229.788000 WHERE `guid` = 17599;
-- .go xyz -7419.0 -354.1 -229.8 1
-- .gobject add temp 164956

-- Eastern Crystal Pylon (guid 17600, entry 164957) — moved 3.7 yds
UPDATE `gameobject` SET `position_x` = -7199.529800, `position_y` = -2325.333300, `position_z` = -226.745900 WHERE `guid` = 17600;
-- .go xyz -7199.5 -2325.3 -226.7 1
-- .gobject add temp 164957

-- Blue Power Crystal (guid 17675, entry 164778) — moved 6.8 yds
UPDATE `gameobject` SET `position_x` = -6677.333500, `position_y` = -2261.333300, `position_z` = -209.045200 WHERE `guid` = 17675;
-- .go xyz -6677.3 -2261.3 -209.0 1
-- .gobject add temp 164778

-- Blue Power Crystal (guid 17681, entry 164778) — moved 10.6 yds
UPDATE `gameobject` SET `position_x` = -7928.933100, `position_y` = -1869.151200, `position_z` = -269.393800 WHERE `guid` = 17681;
-- .go xyz -7928.9 -1869.2 -269.4 1
-- .gobject add temp 164778

-- Blue Power Crystal (guid 17685, entry 164778) — moved 3.7 yds
UPDATE `gameobject` SET `position_x` = -6165.333000, `position_y` = -1527.100000, `position_z` = -217.269100 WHERE `guid` = 17685;
-- .go xyz -6165.3 -1527.1 -217.3 1
-- .gobject add temp 164778

-- Green Power Crystal (guid 17694, entry 164779) — moved -1.0 yds
UPDATE `gameobject` SET `position_x` = -7241.200200, `position_y` = -539.467000, `position_z` = -294.776000 WHERE `guid` = 17694;
-- .go xyz -7241.2 -539.5 -294.8 1
-- .gobject add temp 164779

-- Green Power Crystal (guid 17697, entry 164779) — moved -1.0 yds
UPDATE `gameobject` SET `position_x` = -7030.640100, `position_y` = -2450.490000, `position_z` = -213.570000 WHERE `guid` = 17697;
-- .go xyz -7030.6 -2450.5 -213.6 1
-- .gobject add temp 164779

-- Red Power Crystal (guid 17705, entry 164780) — moved 7.3 yds
UPDATE `gameobject` SET `position_x` = -7466.666500, `position_y` = -2486.389900, `position_z` = -178.779600 WHERE `guid` = 17705;
-- .go xyz -7466.7 -2486.4 -178.8 1
-- .gobject add temp 164780

-- Yellow Power Crystal (guid 17714, entry 164781) — moved -1.0 yds
UPDATE `gameobject` SET `position_x` = -7213.210000, `position_y` = -460.006000, `position_z` = -288.822000 WHERE `guid` = 17714;
-- .go xyz -7213.2 -460.0 -288.8 1
-- .gobject add temp 164781

-- Yellow Power Crystal (guid 17732, entry 164781) — moved 3.7 yds
UPDATE `gameobject` SET `position_x` = -6535.799800, `position_y` = -2133.333300, `position_z` = -268.354000 WHERE `guid` = 17732;
-- .go xyz -6535.8 -2133.3 -268.4 1
-- .gobject add temp 164781

-- A Small Pack (guid 17927, entry 161504) — moved 7.5 yds
UPDATE `gameobject` SET `position_x` = -7668.092800, `position_y` = -1796.579600, `position_z` = -272.837900 WHERE `guid` = 17927;
-- .go xyz -7668.1 -1796.6 -272.8 1
-- .gobject add temp 161504

-- Un'Goro Dirt Pile (guid 17942, entry 157936) — moved 4.4 yds
UPDATE `gameobject` SET `position_x` = -7082.666500, `position_y` = -1419.230000, `position_z` = -233.848300 WHERE `guid` = 17942;
-- .go xyz -7082.7 -1419.2 -233.8 1
-- .gobject add temp 157936

-- Whipweed (guid 18001, entry 180216) — moved -1.0 yds
UPDATE `gameobject` SET `position_x` = -7288.950200, `position_y` = -697.008000, `position_z` = -305.384000 WHERE `guid` = 18001;
-- .go xyz -7289.0 -697.0 -305.4 1
-- .gobject add temp 180216

-- Whipweed (guid 18002, entry 180216) — moved -1.0 yds
UPDATE `gameobject` SET `position_x` = -7203.279800, `position_y` = -674.291000, `position_z` = -281.129000 WHERE `guid` = 18002;
-- .go xyz -7203.3 -674.3 -281.1 1
-- .gobject add temp 180216

-- Whipweed (guid 18003, entry 180216) — moved -1.0 yds
UPDATE `gameobject` SET `position_x` = -7362.930200, `position_y` = -703.902000, `position_z` = -306.889000 WHERE `guid` = 18003;
-- .go xyz -7362.9 -703.9 -306.9 1
-- .gobject add temp 180216

-- Standing, Post - MFF (guid 50484, entry 187653) — moved 8.4 yds
UPDATE `gameobject` SET `position_x` = -6298.470200, `position_y` = -1152.770600, `position_z` = -253.862200 WHERE `guid` = 50484;
-- .go xyz -6298.5 -1152.8 -253.9 1
-- .gobject add temp 187653

-- Standing, Post - MFF (guid 50499, entry 187653) — moved 5.0 yds
UPDATE `gameobject` SET `position_x` = -6250.666500, `position_y` = -1130.666700, `position_z` = -234.869100 WHERE `guid` = 50499;
-- .go xyz -6250.7 -1130.7 -234.9 1
-- .gobject add temp 187653

-- Standing, Post - MFF (guid 50516, entry 187653) — moved 4.8 yds
UPDATE `gameobject` SET `position_x` = -6107.564900, `position_y` = -1133.336900, `position_z` = -185.093600 WHERE `guid` = 50516;
-- .go xyz -6107.6 -1133.3 -185.1 1
-- .gobject add temp 187653

-- Hanging, Square, Medium - MFF (guid 52955, entry 181390) — moved 4.3 yds
UPDATE `gameobject` SET `position_x` = -6169.520000, `position_y` = -1111.200100, `position_z` = -211.571300 WHERE `guid` = 52955;
-- .go xyz -6169.5 -1111.2 -211.6 1
-- .gobject add temp 181390

-- Hanging, Streamer - MFF (guid 53522, entry 181392) — moved 5.0 yds
UPDATE `gameobject` SET `position_x` = -6165.259800, `position_y` = -1118.030000, `position_z` = -212.509900 WHERE `guid` = 53522;
-- .go xyz -6165.3 -1118.0 -212.5 1
-- .gobject add temp 181392

-- Un'Goro Flat Rock (guid 99845, entry 172619) — moved 3.5 yds
UPDATE `gameobject` SET `position_x` = -7197.649900, `position_y` = -2423.590100, `position_z` = -216.483700 WHERE `guid` = 99845;
-- .go xyz -7197.6 -2423.6 -216.5 1
-- .gobject add temp 172619

-- Golden Sansam (guid 216570, entry 176583) — moved 3.7 yds
UPDATE `gameobject` SET `position_x` = -7914.666500, `position_y` = -2016.050000, `position_z` = -271.687700 WHERE `guid` = 216570;
-- .go xyz -7914.7 -2016.0 -271.7 1
-- .gobject add temp 176583

-- Golden Sansam (guid 216593, entry 176583) — moved 6.7 yds
UPDATE `gameobject` SET `position_x` = -7457.977500, `position_y` = -275.160100, `position_z` = -207.827600 WHERE `guid` = 216593;
-- .go xyz -7458.0 -275.2 -207.8 1
-- .gobject add temp 176583

-- Dreamfoil (guid 216598, entry 176584) — moved 4.4 yds
UPDATE `gameobject` SET `position_x` = -6954.666500, `position_y` = -1015.220000, `position_z` = -271.243500 WHERE `guid` = 216598;
-- .go xyz -6954.7 -1015.2 -271.2 1
-- .gobject add temp 176584

-- Dreamfoil (guid 216629, entry 176584) — moved 3.9 yds
UPDATE `gameobject` SET `position_x` = -8157.049800, `position_y` = -1333.050000, `position_z` = -221.871700 WHERE `guid` = 216629;
-- .go xyz -8157.0 -1333.0 -221.9 1
-- .gobject add temp 176584

-- Mountain Silversage (guid 216633, entry 176586) — moved 7.2 yds
UPDATE `gameobject` SET `position_x` = -6214.529800, `position_y` = -1342.510000, `position_z` = -208.710400 WHERE `guid` = 216633;
-- .go xyz -6214.5 -1342.5 -208.7 1
-- .gobject add temp 176586

-- Mountain Silversage (guid 216640, entry 176586) — moved 4.2 yds
UPDATE `gameobject` SET `position_x` = -7317.333000, `position_y` = -1444.580000, `position_z` = -241.101600 WHERE `guid` = 216640;
-- .go xyz -7317.3 -1444.6 -241.1 1
-- .gobject add temp 176586

-- Mountain Silversage (guid 216641, entry 176586) — moved 15.7 yds
UPDATE `gameobject` SET `position_x` = -7445.259800, `position_y` = -2325.333300, `position_z` = -210.709400 WHERE `guid` = 216641;
-- .go xyz -7445.3 -2325.3 -210.7 1
-- .gobject add temp 176586

-- Mountain Silversage (guid 216642, entry 176586) — moved 4.2 yds
UPDATE `gameobject` SET `position_x` = -8130.884300, `position_y` = -1603.926500, `position_z` = -220.415400 WHERE `guid` = 216642;
-- .go xyz -8130.9 -1603.9 -220.4 1
-- .gobject add temp 176586

-- Mountain Silversage (guid 216649, entry 176586) — moved 11.6 yds
UPDATE `gameobject` SET `position_x` = -6914.933600, `position_y` = -360.800000, `position_z` = -241.754700 WHERE `guid` = 216649;
-- .go xyz -6914.9 -360.8 -241.8 1
-- .gobject add temp 176586

-- Mountain Silversage (guid 216650, entry 176586) — moved 4.4 yds
UPDATE `gameobject` SET `position_x` = -6925.497100, `position_y` = -218.209200, `position_z` = -187.975300 WHERE `guid` = 216650;
-- .go xyz -6925.5 -218.2 -188.0 1
-- .gobject add temp 176586

-- Mountain Silversage (guid 216654, entry 176586) — moved 13.0 yds
UPDATE `gameobject` SET `position_x` = -6960.870100, `position_y` = -2325.333300, `position_z` = -211.316000 WHERE `guid` = 216654;
-- .go xyz -6960.9 -2325.3 -211.3 1
-- .gobject add temp 176586

-- Mountain Silversage (guid 216663, entry 176586) — moved 12.8 yds
UPDATE `gameobject` SET `position_x` = -7482.057600, `position_y` = -361.105300, `position_z` = -242.699200 WHERE `guid` = 216663;
-- .go xyz -7482.1 -361.1 -242.7 1
-- .gobject add temp 176586

-- Mountain Silversage (guid 216664, entry 176586) — moved 6.4 yds
UPDATE `gameobject` SET `position_x` = -7488.000000, `position_y` = -289.015000, `position_z` = -197.903000 WHERE `guid` = 216664;
-- .go xyz -7488.0 -289.0 -197.9 1
-- .gobject add temp 176586

-- Small Thorium Vein (guid 216666, entry 324) — moved 3.4 yds
UPDATE `gameobject` SET `position_x` = -8123.500000, `position_y` = -1126.580000, `position_z` = -219.904500 WHERE `guid` = 216666;
-- .go xyz -8123.5 -1126.6 -219.9 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216677, entry 324) — moved 4.9 yds
UPDATE `gameobject` SET `position_x` = -8038.453600, `position_y` = -925.836900, `position_z` = -264.417600 WHERE `guid` = 216677;
-- .go xyz -8038.5 -925.8 -264.4 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216683, entry 324) — moved 8.8 yds
UPDATE `gameobject` SET `position_x` = -7924.799800, `position_y` = -1895.466600, `position_z` = -269.021100 WHERE `guid` = 216683;
-- .go xyz -7924.8 -1895.5 -269.0 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216696, entry 324) — moved 8.8 yds
UPDATE `gameobject` SET `position_x` = -7554.399900, `position_y` = -2233.066400, `position_z` = -269.287800 WHERE `guid` = 216696;
-- .go xyz -7554.4 -2233.1 -269.3 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216701, entry 324) — moved 5.8 yds
UPDATE `gameobject` SET `position_x` = -7401.379900, `position_y` = -341.333300, `position_z` = -217.754700 WHERE `guid` = 216701;
-- .go xyz -7401.4 -341.3 -217.8 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216702, entry 324) — moved 3.5 yds
UPDATE `gameobject` SET `position_x` = -7379.993700, `position_y` = -2302.310800, `position_z` = -253.723600 WHERE `guid` = 216702;
-- .go xyz -7380.0 -2302.3 -253.7 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216712, entry 324) — moved 8.3 yds
UPDATE `gameobject` SET `position_x` = -7040.000000, `position_y` = -2303.999800, `position_z` = -264.859200 WHERE `guid` = 216712;
-- .go xyz -7040.0 -2304.0 -264.9 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216713, entry 324) — moved 5.2 yds
UPDATE `gameobject` SET `position_x` = -6996.520000, `position_y` = -2322.010000, `position_z` = -218.036800 WHERE `guid` = 216713;
-- .go xyz -6996.5 -2322.0 -218.0 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216715, entry 324) — moved 9.2 yds
UPDATE `gameobject` SET `position_x` = -6962.288600, `position_y` = -335.505900, `position_z` = -216.403600 WHERE `guid` = 216715;
-- .go xyz -6962.3 -335.5 -216.4 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216724, entry 324) — moved 11.6 yds
UPDATE `gameobject` SET `position_x` = -6705.297400, `position_y` = -2198.273900, `position_z` = -257.784200 WHERE `guid` = 216724;
-- .go xyz -6705.3 -2198.3 -257.8 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216726, entry 324) — moved 7.6 yds
UPDATE `gameobject` SET `position_x` = -6690.667000, `position_y` = -426.666700, `position_z` = -249.754700 WHERE `guid` = 216726;
-- .go xyz -6690.7 -426.7 -249.8 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216727, entry 324) — moved 13.0 yds
UPDATE `gameobject` SET `position_x` = -6547.780300, `position_y` = -2105.820100, `position_z` = -261.572100 WHERE `guid` = 216727;
-- .go xyz -6547.8 -2105.8 -261.6 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216732, entry 324) — moved 10.6 yds
UPDATE `gameobject` SET `position_x` = -6468.924800, `position_y` = -1868.059000, `position_z` = -267.931900 WHERE `guid` = 216732;
-- .go xyz -6468.9 -1868.1 -267.9 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216742, entry 324) — moved 10.0 yds
UPDATE `gameobject` SET `position_x` = -6296.840300, `position_y` = -1610.165600, `position_z` = -246.013300 WHERE `guid` = 216742;
-- .go xyz -6296.8 -1610.2 -246.0 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216743, entry 324) — moved 10.7 yds
UPDATE `gameobject` SET `position_x` = -6295.466800, `position_y` = -1521.066700, `position_z` = -242.602400 WHERE `guid` = 216743;
-- .go xyz -6295.5 -1521.1 -242.6 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216745, entry 324) — moved 13.4 yds
UPDATE `gameobject` SET `position_x` = -6293.333000, `position_y` = -1314.250000, `position_z` = -263.959800 WHERE `guid` = 216745;
-- .go xyz -6293.3 -1314.2 -264.0 1
-- .gobject add temp 324

-- Rich Thorium Vein (guid 216748, entry 175404) — moved 3.4 yds
UPDATE `gameobject` SET `position_x` = -8123.500000, `position_y` = -1126.580000, `position_z` = -219.904500 WHERE `guid` = 216748;
-- .go xyz -8123.5 -1126.6 -219.9 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216759, entry 175404) — moved 4.9 yds
UPDATE `gameobject` SET `position_x` = -8038.453600, `position_y` = -925.836900, `position_z` = -264.417600 WHERE `guid` = 216759;
-- .go xyz -8038.5 -925.8 -264.4 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216765, entry 175404) — moved 8.8 yds
UPDATE `gameobject` SET `position_x` = -7924.799800, `position_y` = -1895.466600, `position_z` = -269.021100 WHERE `guid` = 216765;
-- .go xyz -7924.8 -1895.5 -269.0 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216778, entry 175404) — moved 8.8 yds
UPDATE `gameobject` SET `position_x` = -7554.399900, `position_y` = -2233.066400, `position_z` = -269.287800 WHERE `guid` = 216778;
-- .go xyz -7554.4 -2233.1 -269.3 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216783, entry 175404) — moved 5.8 yds
UPDATE `gameobject` SET `position_x` = -7401.379900, `position_y` = -341.333300, `position_z` = -217.754700 WHERE `guid` = 216783;
-- .go xyz -7401.4 -341.3 -217.8 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216784, entry 175404) — moved 3.5 yds
UPDATE `gameobject` SET `position_x` = -7379.993700, `position_y` = -2302.310800, `position_z` = -253.723600 WHERE `guid` = 216784;
-- .go xyz -7380.0 -2302.3 -253.7 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216794, entry 175404) — moved 8.3 yds
UPDATE `gameobject` SET `position_x` = -7040.000000, `position_y` = -2303.999800, `position_z` = -264.859200 WHERE `guid` = 216794;
-- .go xyz -7040.0 -2304.0 -264.9 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216795, entry 175404) — moved 5.2 yds
UPDATE `gameobject` SET `position_x` = -6996.520000, `position_y` = -2322.010000, `position_z` = -218.036800 WHERE `guid` = 216795;
-- .go xyz -6996.5 -2322.0 -218.0 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216797, entry 175404) — moved 9.2 yds
UPDATE `gameobject` SET `position_x` = -6962.288600, `position_y` = -335.505900, `position_z` = -216.403600 WHERE `guid` = 216797;
-- .go xyz -6962.3 -335.5 -216.4 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216806, entry 175404) — moved 11.6 yds
UPDATE `gameobject` SET `position_x` = -6705.297400, `position_y` = -2198.273900, `position_z` = -257.784200 WHERE `guid` = 216806;
-- .go xyz -6705.3 -2198.3 -257.8 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216808, entry 175404) — moved 7.6 yds
UPDATE `gameobject` SET `position_x` = -6690.667000, `position_y` = -426.666700, `position_z` = -249.754700 WHERE `guid` = 216808;
-- .go xyz -6690.7 -426.7 -249.8 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216809, entry 175404) — moved 13.0 yds
UPDATE `gameobject` SET `position_x` = -6547.780300, `position_y` = -2105.820100, `position_z` = -261.572100 WHERE `guid` = 216809;
-- .go xyz -6547.8 -2105.8 -261.6 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216814, entry 175404) — moved 10.6 yds
UPDATE `gameobject` SET `position_x` = -6468.924800, `position_y` = -1868.059000, `position_z` = -267.931900 WHERE `guid` = 216814;
-- .go xyz -6468.9 -1868.1 -267.9 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216824, entry 175404) — moved 10.0 yds
UPDATE `gameobject` SET `position_x` = -6296.840300, `position_y` = -1610.165600, `position_z` = -246.013300 WHERE `guid` = 216824;
-- .go xyz -6296.8 -1610.2 -246.0 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216825, entry 175404) — moved 10.7 yds
UPDATE `gameobject` SET `position_x` = -6295.466800, `position_y` = -1521.066700, `position_z` = -242.602400 WHERE `guid` = 216825;
-- .go xyz -6295.5 -1521.1 -242.6 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216827, entry 175404) — moved 13.4 yds
UPDATE `gameobject` SET `position_x` = -6293.333000, `position_y` = -1314.250000, `position_z` = -263.959800 WHERE `guid` = 216827;
-- .go xyz -6293.3 -1314.2 -264.0 1
-- .gobject add temp 175404

-- Small Thorium Vein (guid 216829, entry 324) — moved 4.1 yds
UPDATE `gameobject` SET `position_x` = -8248.836900, `position_y` = -1524.282200, `position_z` = -215.931200 WHERE `guid` = 216829;
-- .go xyz -8248.8 -1524.3 -215.9 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216830, entry 324) — moved 7.1 yds
UPDATE `gameobject` SET `position_x` = -8191.199700, `position_y` = -1341.333400, `position_z` = -215.993500 WHERE `guid` = 216830;
-- .go xyz -8191.2 -1341.3 -216.0 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216835, entry 324) — moved 4.6 yds
UPDATE `gameobject` SET `position_x` = -7842.133300, `position_y` = -1333.600000, `position_z` = -262.926800 WHERE `guid` = 216835;
-- .go xyz -7842.1 -1333.6 -262.9 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216836, entry 324) — moved 5.7 yds
UPDATE `gameobject` SET `position_x` = -7706.103000, `position_y` = -2184.870100, `position_z` = -254.615100 WHERE `guid` = 216836;
-- .go xyz -7706.1 -2184.9 -254.6 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216837, entry 324) — moved 9.2 yds
UPDATE `gameobject` SET `position_x` = -7605.507300, `position_y` = -1808.721700, `position_z` = -265.366000 WHERE `guid` = 216837;
-- .go xyz -7605.5 -1808.7 -265.4 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216841, entry 324) — moved 6.7 yds
UPDATE `gameobject` SET `position_x` = -7470.133300, `position_y` = -2483.466600, `position_z` = -178.354400 WHERE `guid` = 216841;
-- .go xyz -7470.1 -2483.5 -178.4 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216847, entry 324) — moved 8.6 yds
UPDATE `gameobject` SET `position_x` = -6784.000000, `position_y` = -1799.590000, `position_z` = -262.863100 WHERE `guid` = 216847;
-- .go xyz -6784.0 -1799.6 -262.9 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216850, entry 324) — moved 4.0 yds
UPDATE `gameobject` SET `position_x` = -6406.400400, `position_y` = -2019.999900, `position_z` = -261.422000 WHERE `guid` = 216850;
-- .go xyz -6406.4 -2020.0 -261.4 1
-- .gobject add temp 324

-- Small Thorium Vein (guid 216861, entry 324) — moved 7.0 yds
UPDATE `gameobject` SET `position_x` = -6295.589800, `position_y` = -1320.533300, `position_z` = -260.065100 WHERE `guid` = 216861;
-- .go xyz -6295.6 -1320.5 -260.1 1
-- .gobject add temp 324

-- Truesilver Deposit (guid 216865, entry 2047) — moved 4.1 yds
UPDATE `gameobject` SET `position_x` = -8248.836900, `position_y` = -1524.282200, `position_z` = -215.931200 WHERE `guid` = 216865;
-- .go xyz -8248.8 -1524.3 -215.9 1
-- .gobject add temp 2047

-- Truesilver Deposit (guid 216866, entry 2047) — moved 7.1 yds
UPDATE `gameobject` SET `position_x` = -8191.199700, `position_y` = -1341.333400, `position_z` = -215.993500 WHERE `guid` = 216866;
-- .go xyz -8191.2 -1341.3 -216.0 1
-- .gobject add temp 2047

-- Truesilver Deposit (guid 216871, entry 2047) — moved 4.6 yds
UPDATE `gameobject` SET `position_x` = -7842.133300, `position_y` = -1333.600000, `position_z` = -262.926800 WHERE `guid` = 216871;
-- .go xyz -7842.1 -1333.6 -262.9 1
-- .gobject add temp 2047

-- Truesilver Deposit (guid 216872, entry 2047) — moved 5.7 yds
UPDATE `gameobject` SET `position_x` = -7706.103000, `position_y` = -2184.870100, `position_z` = -254.615100 WHERE `guid` = 216872;
-- .go xyz -7706.1 -2184.9 -254.6 1
-- .gobject add temp 2047

-- Truesilver Deposit (guid 216873, entry 2047) — moved 9.2 yds
UPDATE `gameobject` SET `position_x` = -7605.507300, `position_y` = -1808.721700, `position_z` = -265.366000 WHERE `guid` = 216873;
-- .go xyz -7605.5 -1808.7 -265.4 1
-- .gobject add temp 2047

-- Truesilver Deposit (guid 216877, entry 2047) — moved 6.7 yds
UPDATE `gameobject` SET `position_x` = -7470.133300, `position_y` = -2483.466600, `position_z` = -178.354400 WHERE `guid` = 216877;
-- .go xyz -7470.1 -2483.5 -178.4 1
-- .gobject add temp 2047

-- Truesilver Deposit (guid 216883, entry 2047) — moved 8.6 yds
UPDATE `gameobject` SET `position_x` = -6784.000000, `position_y` = -1799.590000, `position_z` = -262.863100 WHERE `guid` = 216883;
-- .go xyz -6784.0 -1799.6 -262.9 1
-- .gobject add temp 2047

-- Truesilver Deposit (guid 216886, entry 2047) — moved 4.0 yds
UPDATE `gameobject` SET `position_x` = -6406.400400, `position_y` = -2019.999900, `position_z` = -261.422000 WHERE `guid` = 216886;
-- .go xyz -6406.4 -2020.0 -261.4 1
-- .gobject add temp 2047

-- Truesilver Deposit (guid 216897, entry 2047) — moved 7.0 yds
UPDATE `gameobject` SET `position_x` = -6295.589800, `position_y` = -1320.533300, `position_z` = -260.065100 WHERE `guid` = 216897;
-- .go xyz -6295.6 -1320.5 -260.1 1
-- .gobject add temp 2047

-- Mithril Deposit (guid 216904, entry 2040) — moved 5.4 yds
UPDATE `gameobject` SET `position_x` = -7390.910200, `position_y` = -2389.333300, `position_z` = -213.723100 WHERE `guid` = 216904;
-- .go xyz -7390.9 -2389.3 -213.7 1
-- .gobject add temp 2040

-- Gold Vein (guid 216914, entry 1734) — moved 5.4 yds
UPDATE `gameobject` SET `position_x` = -7390.910200, `position_y` = -2389.333300, `position_z` = -213.723100 WHERE `guid` = 216914;
-- .go xyz -7390.9 -2389.3 -213.7 1
-- .gobject add temp 1734

-- Truesilver Deposit (guid 216924, entry 2047) — moved 5.4 yds
UPDATE `gameobject` SET `position_x` = -7390.910200, `position_y` = -2389.333300, `position_z` = -213.723100 WHERE `guid` = 216924;
-- .go xyz -7390.9 -2389.3 -213.7 1
-- .gobject add temp 2047

-- Ooze Covered Thorium Vein (guid 216934, entry 123848) — moved 3.2 yds
UPDATE `gameobject` SET `position_x` = -8028.912100, `position_y` = -1134.415600, `position_z` = -315.833300 WHERE `guid` = 216934;
-- .go xyz -8028.9 -1134.4 -315.8 1
-- .gobject add temp 123848

-- Ooze Covered Thorium Vein (guid 216936, entry 123848) — moved 3.7 yds
UPDATE `gameobject` SET `position_x` = -8009.333000, `position_y` = -1190.933300, `position_z` = -321.593400 WHERE `guid` = 216936;
-- .go xyz -8009.3 -1190.9 -321.6 1
-- .gobject add temp 123848

-- Ooze Covered Truesilver Deposit (guid 216944, entry 123309) — moved 3.2 yds
UPDATE `gameobject` SET `position_x` = -8028.912100, `position_y` = -1134.415600, `position_z` = -315.833300 WHERE `guid` = 216944;
-- .go xyz -8028.9 -1134.4 -315.8 1
-- .gobject add temp 123309

-- Ooze Covered Truesilver Deposit (guid 216946, entry 123309) — moved 3.7 yds
UPDATE `gameobject` SET `position_x` = -8009.333000, `position_y` = -1190.933300, `position_z` = -321.593400 WHERE `guid` = 216946;
-- .go xyz -8009.3 -1190.9 -321.6 1
-- .gobject add temp 123309

-- Rich Thorium Vein (guid 216958, entry 175404) — moved 5.2 yds
UPDATE `gameobject` SET `position_x` = -7114.251000, `position_y` = -1468.603900, `position_z` = -244.195300 WHERE `guid` = 216958;
-- .go xyz -7114.3 -1468.6 -244.2 1
-- .gobject add temp 175404

-- Rich Thorium Vein (guid 216960, entry 175404) — moved 3.6 yds
UPDATE `gameobject` SET `position_x` = -7013.390100, `position_y` = -234.666700, `position_z` = -216.382700 WHERE `guid` = 216960;
-- .go xyz -7013.4 -234.7 -216.4 1
-- .gobject add temp 175404

-- Truesilver Deposit (guid 216969, entry 2047) — moved 5.2 yds
UPDATE `gameobject` SET `position_x` = -7114.251000, `position_y` = -1468.603900, `position_z` = -244.195300 WHERE `guid` = 216969;
-- .go xyz -7114.3 -1468.6 -244.2 1
-- .gobject add temp 2047

-- Truesilver Deposit (guid 216971, entry 2047) — moved 3.6 yds
UPDATE `gameobject` SET `position_x` = -7013.390100, `position_y` = -234.666700, `position_z` = -216.382700 WHERE `guid` = 216971;
-- .go xyz -7013.4 -234.7 -216.4 1
-- .gobject add temp 2047

