-- worgoblin: animationdata
-- Generated by dbc-mgr import-module

-- animationdata: 1 inserts, 0 updates, 0 deletes
INSERT INTO `animationdata` (`id`, `name`, `wep_flags`, `body_flags`, `flags`, `fallback_anim_id`, `behavior_id`, `behavior_tier`) VALUES (646, 'MountSelfStart', 16, 256, 3, 0, 646, 0);