-- worgoblin: charhairtextures
-- Generated by dbc-mgr import-module

-- charhairtextures: 6 inserts, 0 updates, 0 deletes
INSERT INTO `charhairtextures` (`id`, `race`, `gender`, `unk_1`, `unk_2`, `unk_3`, `unk_4`, `unk_5`) VALUES (102, 9, 0, 0, 255, 0, 1, 1);
INSERT INTO `charhairtextures` (`id`, `race`, `gender`, `unk_1`, `unk_2`, `unk_3`, `unk_4`, `unk_5`) VALUES (103, 9, 1, 0, 255, 0, 1, 1);
INSERT INTO `charhairtextures` (`id`, `race`, `gender`, `unk_1`, `unk_2`, `unk_3`, `unk_4`, `unk_5`) VALUES (104, 20, 0, 0, 255, 0, 1, 1);
INSERT INTO `charhairtextures` (`id`, `race`, `gender`, `unk_1`, `unk_2`, `unk_3`, `unk_4`, `unk_5`) VALUES (106, 20, 1, 0, 255, 0, 1, 1);
INSERT INTO `charhairtextures` (`id`, `race`, `gender`, `unk_1`, `unk_2`, `unk_3`, `unk_4`, `unk_5`) VALUES (107, 21, 0, 0, 255, 0, 1, 1);
INSERT INTO `charhairtextures` (`id`, `race`, `gender`, `unk_1`, `unk_2`, `unk_3`, `unk_4`, `unk_5`) VALUES (108, 21, 1, 0, 255, 0, 1, 1);