-- worgoblin: chrraces
-- Generated by dbc-mgr import-module

-- chrraces: 0 inserts, 2 updates, 0 deletes
UPDATE `chrraces` SET `flags` = 4, `faction_id` = 2, `exploration_sound_id` = 4141, `base_language` = 1, `cinematic_sequence_id` = 141, `alliance` = 1, `facial_hair_customization_1` = 'PIERCINGS', `facial_hair_customization_2` = 'PIERCINGS' WHERE `id` = 9;
UPDATE `chrraces` SET `flags` = 6, `exploration_sound_id` = 4143, `male_display_id` = 29422, `female_display_id` = 29423, `client_prefix` = 'Wo', `client_filestring` = 'Worgen', `cinematic_sequence_id` = 61, `alliance` = 0, `name_neutral_enus` = 'Worgen', `facial_hair_customization_1` = 'FEATURES', `facial_hair_customization_2` = 'EARS' WHERE `id` = 12;