-- worgoblin: spellicon
-- Generated by dbc-mgr import-module

-- spellicon: 10 inserts, 0 updates, 0 deletes
INSERT INTO `spellicon` (`id`, `name`) VALUES (4331, 'Interface\\Icons\\ability_racial_bestdealsanywhere');
INSERT INTO `spellicon` (`id`, `name`) VALUES (133032, 'Interface\\Icons\\inv_gizmo_rocketlauncher');
INSERT INTO `spellicon` (`id`, `name`) VALUES (366937, 'Interface\\Icons\\ability_racial_darkflight');
INSERT INTO `spellicon` (`id`, `name`) VALUES (369214, 'Interface\\Icons\\ability_racial_timeismoney');
INSERT INTO `spellicon` (`id`, `name`) VALUES (370211, 'Interface\\Icons\\ability_racial_packhobgoblin');
INSERT INTO `spellicon` (`id`, `name`) VALUES (370670, 'Interface\\Icons\\ability_racial_betterlivingthroughchemistry');
INSERT INTO `spellicon` (`id`, `name`) VALUES (370769, 'Interface\\Icons\\ability_racial_rocketjump');
INSERT INTO `spellicon` (`id`, `name`) VALUES (463874, 'Interface\\Icons\\achievement_goblinhead');
INSERT INTO `spellicon` (`id`, `name`) VALUES (463876, 'Interface\\Icons\\achievement_worganhead');
INSERT INTO `spellicon` (`id`, `name`) VALUES (514641, 'Interface\\Icons\\ability_racial_runningwild');