-- [BASE,F-044] zep-legacy: skilllineability
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-044]_skilllineability.sql with overrides

-- skilllineability: 244 inserts, 27 updates, 0 deletes
DELETE FROM `skilllineability` WHERE `id` = 31439;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31439, 50, 36613, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31441;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31441, 900, 56992, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31442;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31442, 900, 61199, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31443;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31443, 900, 17253, 0, 0, 0, 0, 1, 17255, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31444;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31444, 900, 58598, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31445;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31445, 900, 17255, 0, 0, 0, 0, 1, 17256, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31446;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31446, 900, 17256, 0, 0, 0, 0, 1, 17257, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31447;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31447, 900, 17257, 0, 0, 0, 0, 1, 17258, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31448;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31448, 900, 17258, 0, 0, 0, 0, 1, 17259, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31449;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31449, 900, 17259, 0, 0, 0, 0, 1, 17260, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31450;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31450, 900, 17260, 0, 0, 0, 0, 1, 17261, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31451;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31451, 900, 17261, 0, 0, 0, 0, 1, 27050, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31452;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31452, 900, 27050, 0, 0, 0, 0, 1, 52473, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31453;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31453, 900, 52473, 0, 0, 0, 0, 1, 52474, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31454;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31454, 900, 52474, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31455;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31455, 212, 6580, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31456;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31456, 270, 22683, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31457;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31457, 900, 50433, 0, 0, 0, 0, 1, 52395, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31458;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31458, 900, 52395, 0, 0, 0, 0, 1, 52396, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31459;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31459, 900, 52396, 0, 0, 0, 0, 1, 52397, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31460;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31460, 900, 52397, 0, 0, 0, 0, 1, 52398, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31461;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31461, 900, 52398, 0, 0, 0, 0, 1, 52399, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31462;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31462, 900, 52399, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31463;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31463, 900, 24394, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31464;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31464, 900, 19577, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31465;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31465, 900, 1742, 0, 0, 0, 0, 1, 1753, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31466;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31466, 900, 2649, 0, 0, 0, 0, 1, 14916, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31467;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31467, 900, 14916, 0, 0, 0, 0, 1, 14917, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31468;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31468, 900, 14917, 0, 0, 0, 0, 1, 14918, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31469;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31469, 900, 14918, 0, 0, 0, 0, 1, 14919, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31470;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31470, 900, 14919, 0, 0, 0, 0, 1, 14920, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31471;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31471, 900, 14920, 0, 0, 0, 0, 1, 14921, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31472;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31472, 900, 14921, 0, 0, 0, 0, 1, 27047, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31473;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31473, 900, 27047, 0, 0, 0, 0, 1, 61676, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31474;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31474, 900, 34666, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31475;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31475, 900, 34667, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31476;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31476, 900, 34675, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31477;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31477, 900, 20782, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31478;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31478, 900, 8875, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31479;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31479, 900, 19580, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31480;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31480, 900, 19581, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31481;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31481, 900, 19582, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31482;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31482, 900, 19589, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31483;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31483, 900, 19591, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31484;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31484, 900, 20784, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31485;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31485, 900, 34902, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31486;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31486, 900, 34903, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31487;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31487, 900, 34904, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31488;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31488, 900, 53175, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31489;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31489, 900, 53176, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31490;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31490, 900, 53178, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31491;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31491, 900, 53179, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31492;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31492, 900, 53180, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31493;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31493, 900, 53181, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31494;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31494, 900, 53182, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31495;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31495, 900, 53183, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31496;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31496, 900, 53184, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31497;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31497, 900, 53186, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31498;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31498, 900, 53187, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31499;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31499, 900, 53203, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31500;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31500, 900, 53204, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31501;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31501, 900, 53205, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31502;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31502, 900, 53397, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31503;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31503, 900, 53401, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31504;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31504, 900, 53409, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31505;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31505, 900, 53411, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31506;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31506, 900, 53426, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31507;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31507, 900, 53427, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31508;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31508, 900, 53429, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31509;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31509, 900, 53430, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31510;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31510, 900, 19596, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31511;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31511, 900, 53434, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31512;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31512, 900, 53450, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31513;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31513, 900, 53451, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31514;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31514, 900, 52858, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31515;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31515, 900, 53476, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31516;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31516, 900, 53477, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31517;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31517, 900, 53478, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31518;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31518, 900, 53480, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31519;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31519, 900, 53481, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31520;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31520, 900, 53482, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31521;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31521, 900, 53490, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31522;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31522, 900, 52234, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31523;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31523, 900, 53497, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31524;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31524, 900, 53508, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31525;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31525, 900, 53511, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31526;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31526, 900, 53512, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31527;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31527, 900, 53514, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31528;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31528, 900, 53516, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31529;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31529, 900, 53517, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31530;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31530, 900, 54044, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31531;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31531, 900, 53483, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31532;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31532, 900, 53485, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31533;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31533, 900, 53554, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31534;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31534, 900, 53555, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31535;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31535, 900, 55566, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31536;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31536, 900, 55709, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31537;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31537, 900, 61017, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31538;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31538, 900, 61676, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31539;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31539, 900, 61680, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31540;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31540, 900, 61681, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31541;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31541, 900, 61682, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31542;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31542, 900, 61683, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31543;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31543, 900, 61689, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31544;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31544, 900, 61690, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31545;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31545, 900, 61686, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31546;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31546, 900, 61687, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31547;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31547, 900, 61688, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31548;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31548, 900, 62758, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31549;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31549, 900, 62759, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31550;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31550, 900, 62760, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31551;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31551, 900, 62762, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31552;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31552, 900, 62764, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31553;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31553, 900, 62765, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31554;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31554, 900, 63900, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31555;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31555, 900, 65220, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31556;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31556, 900, 75446, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31557;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31557, 900, 75447, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31558;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31558, 900, 75593, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31559;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31559, 900, 22683, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);

DELETE FROM `skilllineability` WHERE `id` = 31561;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31561, 755, 91085, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31562;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31562, 755, 91076, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31563;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31563, 202, 91081, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31565;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31565, 164, 91074, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31569;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31569, 202, 80810, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31570;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31570, 165, 80819, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31571;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31571, 165, 80816, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31572;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31572, 165, 80817, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31573;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31573, 165, 69388, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31574;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31574, 165, 69386, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31575;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31575, 165, 80818, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31576;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31576, 333, 72559, 0, 0, 0, 0, 1, 0, 0, 330, 310, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31580;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31580, 773, 91009, 0, 0, 0, 0, 1, 0, 0, 160, 150, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31581;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31581, 773, 91010, 0, 0, 0, 0, 1, 0, 0, 160, 150, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31582;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31582, 773, 91012, 0, 0, 0, 0, 1, 0, 0, 160, 150, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31583;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31583, 773, 91013, 0, 0, 0, 0, 1, 0, 0, 160, 150, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31584;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31584, 773, 91014, 0, 0, 0, 0, 1, 0, 0, 160, 150, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31585;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31585, 773, 91015, 0, 0, 0, 0, 1, 0, 0, 160, 150, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31586;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31586, 773, 91016, 0, 0, 0, 0, 1, 0, 0, 160, 150, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31587;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31587, 773, 91017, 0, 0, 0, 0, 1, 0, 0, 160, 150, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31588;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31588, 773, 91080, 0, 0, 0, 0, 1, 0, 0, 325, 315, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31589;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31589, 333, 91117, 0, 0, 0, 0, 1, 0, 0, 265, 250, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 32000;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (32000, 237, 91058, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 32001;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (32001, 237, 91059, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 32002;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (32002, 237, 91060, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 32003;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (32003, 237, 91061, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 32004;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (32004, 237, 91062, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 32005;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (32005, 237, 91063, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 32006;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (32006, 237, 91064, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 32007;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (32007, 237, 91065, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 32008;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (32008, 237, 91066, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);

DELETE FROM `skilllineability` WHERE `id` = 99986;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (99986, 773, 91139, 0, 0, 0, 0, 1, 0, 0, 275, 265, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 99991;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (99991, 237, 91057, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 99992;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (99992, 237, 91056, 0, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 99995;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (99995, 163, 91119, 0, 4, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 99996;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (99996, 792, 8690, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 99997;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (99997, 792, 42766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
-- Reagent Banker SLA (99998, spell 75136 on Perks tab 792) removed - obsolete with
-- Reagent Banker (F-070). DELETE retained so the orphan row clears on apply; spell
-- 75136 itself reverts to stock "Ethereal Portal" on a reset-based dbc rebuild -t spell
-- (original_dbc baseline is already clean).
DELETE FROM `skilllineability` WHERE `id` = 99998;

DELETE FROM `skilllineability` WHERE `id` = 100000;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (100000, 613, 103246, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 100001;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (100001, 184, 103247, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 100002;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (100002, 574, 103248, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
UPDATE `skilllineability` SET `min_skill_value` = 0 WHERE `id` = 610;
UPDATE `skilllineability` SET `required_classes` = 195 WHERE `id` = 5006;
UPDATE `skilllineability` SET `required_classes` = 0 WHERE `id` = 8439;
UPDATE `skilllineability` SET `skill_line` = 593, `required_classes` = 256 WHERE `id` = 11180;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 12042;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 12043;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 12096;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 12097;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 12397;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 13256;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 13456;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 13575;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 13659;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 13809;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 14939;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 15955;
UPDATE `skilllineability` SET `skill_line` = 792, `required_classes` = 0 WHERE `id` = 16529;
UPDATE `skilllineability` SET `skill_line` = 792 WHERE `id` = 16578;
UPDATE `skilllineability` SET `skill_line` = 270 WHERE `id` = 17454;
UPDATE `skilllineability` SET `skill_line` = 270 WHERE `id` = 17811;
UPDATE `skilllineability` SET `skill_line` = 270 WHERE `id` = 17812;
UPDATE `skilllineability` SET `skill_line` = 270 WHERE `id` = 17813;
UPDATE `skilllineability` SET `skill_line` = 270 WHERE `id` = 17814;
UPDATE `skilllineability` SET `skill_line` = 270 WHERE `id` = 17815;
UPDATE `skilllineability` SET `skill_grey_level` = 315, `skill_yellow_level` = 265 WHERE `id` = 20659;