-- [BASE,F-137] hd-models-textures: characterfacialhairstyles
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-137]_characterfacialhairstyles.sql with overrides

-- characterfacialhairstyles: 1 inserts, 1 updates, 0 deletes
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 0, 6);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 1, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 2, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 3, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 4, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 5, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 6, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 7, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 8, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 9, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 10, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 11, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 12, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 13, 6);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 14, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 15, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 16, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 17, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 18, 6);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 19, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 20, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 21, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 22, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 23, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 0, 24, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 0, 6);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 1, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 2, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 3, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 4, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 5, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 6, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 7, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 8, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 9, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 10, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 11, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 12, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 13, 6);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 14, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 15, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 16, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 17, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 18, 6);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 19, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 20, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 21, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 22, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 23, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`) VALUES (9, 1, 24, 6);
UPDATE `characterfacialhairstyles` SET `geoset_1` = 2 WHERE `race_id` = 5;