-- [BASE,F-137] hd-models-textures: charhairgeosets
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-137]_charhairgeosets.sql with overrides

-- charhairgeosets: 31 inserts, 4 updates, 0 deletes
DELETE FROM `charhairgeosets` WHERE `id` = 454;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (454, 9, 0, 2, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 455;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (455, 9, 0, 3, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 456;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (456, 9, 0, 4, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 461;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (461, 9, 1, 2, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 462;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (462, 9, 1, 3, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 463;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (463, 9, 1, 4, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 464;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (464, 9, 1, 5, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 465;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (465, 9, 1, 6, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 466;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (466, 9, 1, 7, 9, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 467;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (467, 9, 1, 8, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 468;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (468, 9, 1, 9, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 469;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (469, 9, 1, 10, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 470;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (470, 9, 1, 11, 13, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 471;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (471, 9, 1, 12, 14, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 472;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (472, 9, 1, 13, 15, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 473;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (473, 9, 1, 14, 16, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 474;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (474, 9, 1, 15, 17, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 475;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (475, 9, 1, 16, 18, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 476;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (476, 9, 0, 5, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 477;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (477, 9, 0, 6, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 478;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (478, 9, 0, 7, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 479;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (479, 9, 0, 9, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 481;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (481, 9, 0, 10, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 482;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (482, 9, 0, 8, 9, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 484;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (484, 9, 0, 11, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 486;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (486, 9, 0, 12, 13, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 487;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (487, 9, 0, 13, 14, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 488;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (488, 9, 0, 14, 15, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 490;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (490, 9, 0, 15, 16, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 492;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (492, 9, 0, 16, 17, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 493;
INSERT INTO `charhairgeosets` (`id`, `race_id`, `gender`, `variation_id`, `geoset_id`, `showscalp`) VALUES (493, 9, 0, 17, 18, 0);
UPDATE `charhairgeosets` SET `geoset_id` = 19 WHERE `id` = 241;
UPDATE `charhairgeosets` SET `variation_id` = 1, `showscalp` = 0 WHERE `id` = 242;
UPDATE `charhairgeosets` SET `gender` = 1, `geoset_id` = 2 WHERE `id` = 243;
UPDATE `charhairgeosets` SET `gender` = 1, `variation_id` = 1, `geoset_id` = 3, `showscalp` = 0 WHERE `id` = 244;