-- [BASE,F-136] open-azeroth: lightfloatband
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-136]_lightfloatband.sql with overrides

-- lightfloatband: 462 inserts, 0 updates, 0 deletes
DELETE FROM `lightfloatband` WHERE `id` = 4987;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (4987, 2);
DELETE FROM `lightfloatband` WHERE `id` = 4988;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (4988, 2);
DELETE FROM `lightfloatband` WHERE `id` = 4989;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (4989, 6);
DELETE FROM `lightfloatband` WHERE `id` = 4990;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (4990, 6);
DELETE FROM `lightfloatband` WHERE `id` = 4991;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (4991, 6);
DELETE FROM `lightfloatband` WHERE `id` = 4992;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (4992, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5065;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5065, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5066;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5066, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5067;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5067, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5068;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5068, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5069;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5069, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5070;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5070, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5089;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5089, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5090;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5090, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5091;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5091, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5092;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5092, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5093;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5093, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5094;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5094, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5113;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5113, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5114;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5114, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5115;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5115, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5116;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5116, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5117;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5117, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5118;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5118, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5155;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5155, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5156;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5156, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5157;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5157, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5158;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5158, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5159;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5159, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5160;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5160, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5161;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5161, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5162;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5162, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5163;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5163, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5164;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5164, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5165;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5165, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5166;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5166, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5167;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5167, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5168;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5168, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5169;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5169, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5170;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5170, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5171;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5171, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5172;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5172, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5179;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5179, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5180;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5180, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5181;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5181, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5182;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5182, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5183;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5183, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5184;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5184, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5197;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5197, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5198;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5198, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5199;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5199, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5200;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5200, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5201;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5201, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5202;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5202, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5227;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5227, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5228;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5228, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5229;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5229, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5230;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5230, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5231;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5231, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5232;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5232, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5257;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5257, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5258;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5258, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5259;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5259, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5260;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5260, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5261;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5261, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5262;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5262, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5263;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5263, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5264;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5264, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5265;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5265, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5266;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5266, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5267;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5267, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5268;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5268, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5287;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5287, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5288;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5288, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5289;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5289, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5290;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5290, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5291;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5291, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5292;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5292, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5293;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5293, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5294;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5294, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5295;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5295, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5296;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5296, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5297;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5297, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5298;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5298, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5317;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5317, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5318;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5318, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5319;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5319, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5320;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5320, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5321;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5321, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5322;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5322, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5323;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5323, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5324;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5324, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5325;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5325, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5326;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5326, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5327;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5327, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5328;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5328, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5329;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5329, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5330;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5330, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5331;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5331, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5332;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5332, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5333;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5333, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5334;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5334, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5341;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5341, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5342;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5342, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5343;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5343, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5344;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5344, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5345;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5345, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5346;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5346, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5347;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5347, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5348;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5348, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5349;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5349, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5350;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5350, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5351;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5351, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5352;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5352, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5353;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5353, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5354;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5354, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5355;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5355, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5356;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5356, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5357;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5357, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5358;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5358, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5389;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5389, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5390;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5390, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5391;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5391, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5392;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5392, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5393;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5393, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5394;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5394, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5395;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5395, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5396;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5396, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5397;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5397, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5398;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5398, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5399;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5399, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5400;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5400, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5413;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5413, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5414;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5414, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5415;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5415, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5416;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5416, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5417;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5417, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5418;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5418, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5431;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5431, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5432;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5432, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5433;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5433, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5434;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5434, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5435;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5435, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5436;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5436, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5462;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5462, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5463;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5463, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5464;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5464, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5465;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5465, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5466;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5466, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5467;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5467, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5479;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5479, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5480;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5480, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5481;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5481, 3);
DELETE FROM `lightfloatband` WHERE `id` = 5482;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5482, 3);
DELETE FROM `lightfloatband` WHERE `id` = 5483;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5483, 3);
DELETE FROM `lightfloatband` WHERE `id` = 5484;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5484, 3);
DELETE FROM `lightfloatband` WHERE `id` = 5491;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5491, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5492;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5492, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5493;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5493, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5494;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5494, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5495;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5495, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5496;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5496, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5503;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5503, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5504;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5504, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5505;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5505, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5506;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5506, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5507;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5507, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5508;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5508, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5509;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5509, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5510;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5510, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5511;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5511, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5512;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5512, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5513;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5513, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5514;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5514, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5515;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5515, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5516;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5516, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5517;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5517, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5518;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5518, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5519;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5519, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5520;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5520, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5635;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5635, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5636;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5636, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5637;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5637, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5638;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5638, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5639;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5639, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5640;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5640, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5641;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5641, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5642;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5642, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5643;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5643, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5644;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5644, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5645;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5645, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5646;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5646, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5647;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5647, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5648;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5648, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5649;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5649, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5650;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5650, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5651;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5651, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5652;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5652, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5659;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5659, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5660;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5660, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5661;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5661, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5662;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5662, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5663;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5663, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5664;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5664, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5665;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5665, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5666;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5666, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5667;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5667, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5668;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5668, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5669;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5669, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5670;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5670, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5671;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5671, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5672;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5672, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5673;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5673, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5674;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5674, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5675;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5675, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5676;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5676, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5677;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5677, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5678;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5678, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5679;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5679, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5680;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5680, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5681;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5681, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5682;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5682, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5689;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5689, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5690;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5690, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5691;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5691, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5692;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5692, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5693;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5693, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5694;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5694, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5695;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5695, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5696;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5696, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5697;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5697, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5698;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5698, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5699;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5699, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5700;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5700, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5713;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5713, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5714;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5714, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5715;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5715, 3);
DELETE FROM `lightfloatband` WHERE `id` = 5716;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5716, 3);
DELETE FROM `lightfloatband` WHERE `id` = 5717;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5717, 3);
DELETE FROM `lightfloatband` WHERE `id` = 5718;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5718, 3);
DELETE FROM `lightfloatband` WHERE `id` = 5719;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5719, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5720;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5720, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5721;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5721, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5722;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5722, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5723;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5723, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5724;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5724, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5725;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5725, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5726;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5726, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5727;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5727, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5728;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5728, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5729;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5729, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5730;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5730, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5737;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5737, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5738;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5738, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5739;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5739, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5740;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5740, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5741;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5741, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5742;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5742, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5803;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5803, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5804;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5804, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5805;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5805, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5806;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5806, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5807;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5807, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5808;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5808, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5809;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5809, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5810;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5810, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5811;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5811, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5812;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5812, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5813;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5813, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5814;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5814, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5815;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5815, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5816;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5816, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5817;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5817, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5818;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5818, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5819;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5819, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5820;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5820, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5845;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5845, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5846;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5846, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5847;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5847, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5848;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5848, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5849;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5849, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5850;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5850, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5851;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5851, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5852;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5852, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5853;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5853, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5854;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5854, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5855;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5855, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5856;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5856, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5857;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5857, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5858;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5858, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5859;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5859, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5860;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5860, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5861;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5861, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5862;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5862, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5863;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5863, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5864;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5864, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5865;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5865, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5866;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5866, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5867;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5867, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5868;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5868, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5893;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5893, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5894;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5894, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5895;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5895, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5896;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5896, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5897;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5897, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5898;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5898, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5917;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5917, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5918;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5918, 6);
DELETE FROM `lightfloatband` WHERE `id` = 5919;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5919, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5920;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5920, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5921;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5921, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5922;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5922, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5929;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5929, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5930;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5930, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5931;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5931, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5932;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5932, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5933;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5933, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5934;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5934, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5935;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5935, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5936;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5936, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5937;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5937, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5938;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5938, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5939;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5939, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5940;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5940, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5941;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5941, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5942;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5942, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5943;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5943, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5944;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5944, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5945;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5945, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5946;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5946, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5947;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5947, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5948;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5948, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5949;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5949, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5950;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5950, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5951;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5951, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5952;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5952, 1);
DELETE FROM `lightfloatband` WHERE `id` = 5959;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5959, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5960;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5960, 2);
DELETE FROM `lightfloatband` WHERE `id` = 5961;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5961, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5962;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5962, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5963;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5963, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5964;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5964, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5971;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5971, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5972;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5972, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5973;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5973, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5974;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5974, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5975;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5975, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5976;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5976, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5977;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5977, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5978;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5978, 7);
DELETE FROM `lightfloatband` WHERE `id` = 5979;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5979, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5980;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5980, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5981;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5981, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5982;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5982, 4);
DELETE FROM `lightfloatband` WHERE `id` = 5989;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5989, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5990;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5990, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5991;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5991, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5992;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5992, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5993;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5993, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5994;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5994, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5995;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5995, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5996;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5996, 9);
DELETE FROM `lightfloatband` WHERE `id` = 5997;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5997, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5998;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5998, 5);
DELETE FROM `lightfloatband` WHERE `id` = 5999;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (5999, 5);
DELETE FROM `lightfloatband` WHERE `id` = 6000;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6000, 5);
DELETE FROM `lightfloatband` WHERE `id` = 6007;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6007, 9);
DELETE FROM `lightfloatband` WHERE `id` = 6008;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6008, 9);
DELETE FROM `lightfloatband` WHERE `id` = 6009;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6009, 5);
DELETE FROM `lightfloatband` WHERE `id` = 6010;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6010, 5);
DELETE FROM `lightfloatband` WHERE `id` = 6011;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6011, 5);
DELETE FROM `lightfloatband` WHERE `id` = 6012;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6012, 5);
DELETE FROM `lightfloatband` WHERE `id` = 6025;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6025, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6026;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6026, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6027;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6027, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6028;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6028, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6029;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6029, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6030;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6030, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6031;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6031, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6032;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6032, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6033;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6033, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6034;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6034, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6035;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6035, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6036;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6036, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6037;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6037, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6038;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6038, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6039;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6039, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6040;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6040, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6041;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6041, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6042;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6042, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6049;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6049, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6050;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6050, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6051;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6051, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6052;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6052, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6053;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6053, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6054;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6054, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6055;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6055, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6056;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6056, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6057;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6057, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6058;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6058, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6059;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6059, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6060;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6060, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6061;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6061, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6062;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6062, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6063;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6063, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6064;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6064, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6065;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6065, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6066;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6066, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6079;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6079, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6080;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6080, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6081;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6081, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6082;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6082, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6083;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6083, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6084;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6084, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6085;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6085, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6086;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6086, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6087;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6087, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6088;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6088, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6089;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6089, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6090;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6090, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6091;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6091, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6092;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6092, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6093;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6093, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6094;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6094, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6095;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6095, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6096;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6096, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6121;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6121, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6122;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6122, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6123;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6123, 4);
DELETE FROM `lightfloatband` WHERE `id` = 6124;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6124, 4);
DELETE FROM `lightfloatband` WHERE `id` = 6125;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6125, 4);
DELETE FROM `lightfloatband` WHERE `id` = 6126;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6126, 4);
DELETE FROM `lightfloatband` WHERE `id` = 6163;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6163, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6164;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6164, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6165;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6165, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6166;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6166, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6167;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6167, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6168;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6168, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6175;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6175, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6176;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6176, 6);
DELETE FROM `lightfloatband` WHERE `id` = 6177;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6177, 4);
DELETE FROM `lightfloatband` WHERE `id` = 6178;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6178, 4);
DELETE FROM `lightfloatband` WHERE `id` = 6179;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6179, 4);
DELETE FROM `lightfloatband` WHERE `id` = 6180;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6180, 4);
DELETE FROM `lightfloatband` WHERE `id` = 6221;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6221, 5);
DELETE FROM `lightfloatband` WHERE `id` = 6222;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6222, 5);
DELETE FROM `lightfloatband` WHERE `id` = 6223;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6223, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6224;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6224, 2);
DELETE FROM `lightfloatband` WHERE `id` = 6225;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6225, 1);
DELETE FROM `lightfloatband` WHERE `id` = 6226;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (6226, 1);
DELETE FROM `lightfloatband` WHERE `id` = 15091;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (15091, 12);
DELETE FROM `lightfloatband` WHERE `id` = 15092;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (15092, 12);
DELETE FROM `lightfloatband` WHERE `id` = 15093;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (15093, 12);
DELETE FROM `lightfloatband` WHERE `id` = 15094;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (15094, 12);
DELETE FROM `lightfloatband` WHERE `id` = 15095;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (15095, 12);
DELETE FROM `lightfloatband` WHERE `id` = 15096;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (15096, 12);
DELETE FROM `lightfloatband` WHERE `id` = 22345;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (22345, 6);
DELETE FROM `lightfloatband` WHERE `id` = 22346;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (22346, 6);
DELETE FROM `lightfloatband` WHERE `id` = 22347;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (22347, 6);
DELETE FROM `lightfloatband` WHERE `id` = 22348;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (22348, 6);
DELETE FROM `lightfloatband` WHERE `id` = 22349;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (22349, 6);
DELETE FROM `lightfloatband` WHERE `id` = 22350;
INSERT INTO `lightfloatband` (`id`, `num_entries`) VALUES (22350, 6);