-- [BASE,F-136] open-azeroth: groundeffectdoodad
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-136]_groundeffectdoodad.sql with overrides

-- groundeffectdoodad: 141 inserts, 4 updates, 0 deletes
DELETE FROM `groundeffectdoodad` WHERE `id` = 709;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (709, 7578, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 710;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (710, 7592, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 711;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (711, 7607, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 712;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (712, 7622, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 713;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (713, 7635, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 714;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (714, 7648, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 715;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (715, 7661, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 716;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (716, 7674, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 717;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (717, 7689, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 718;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (718, 7704, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 719;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (719, 7719, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 720;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (720, 7734, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 721;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (721, 7748, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 732;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (732, 7763, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 733;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (733, 7776, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 734;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (734, 7789, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 735;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (735, 7802, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 736;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (736, 7815, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 737;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (737, 7828, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 738;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (738, 7841, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 739;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (739, 7854, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 740;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (740, 7867, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 741;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (741, 7880, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 742;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (742, 7894, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 743;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (743, 7908, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 744;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (744, 7921, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 745;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (745, 7934, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 746;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (746, 7947, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 747;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (747, 7960, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 748;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (748, 7973, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 749;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (749, 7985, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 750;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (750, 7997, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 751;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (751, 8009, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 752;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (752, 8021, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 753;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (753, 8033, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 754;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (754, 8045, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 755;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (755, 8057, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 756;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (756, 8071, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 757;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (757, 8085, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 758;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (758, 8099, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 759;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (759, 8111, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 766;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (766, 8123, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 767;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (767, 8136, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 771;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (771, 8149, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 772;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (772, 8162, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 773;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (773, 8175, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 774;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (774, 8188, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 775;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (775, 8201, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 776;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (776, 8214, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 777;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (777, 8227, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 778;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (778, 8240, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 779;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (779, 8253, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 780;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (780, 8265, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 781;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (781, 8277, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 782;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (782, 8289, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 783;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (783, 8301, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 784;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (784, 8313, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 785;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (785, 8326, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 786;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (786, 8339, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 787;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (787, 8351, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 788;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (788, 8364, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 789;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (789, 8377, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 790;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (790, 8390, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 791;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (791, 8403, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 792;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (792, 8416, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 793;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (793, 8429, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 794;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (794, 8442, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 799;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (799, 8503, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 800;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (800, 8516, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 801;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (801, 8529, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 802;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (802, 8542, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 803;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (803, 8555, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 804;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (804, 8568, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 805;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (805, 8581, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 806;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (806, 8594, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 807;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (807, 8607, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 808;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (808, 8620, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 809;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (809, 8633, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 810;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (810, 8646, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 811;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (811, 8660, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 812;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (812, 8674, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 813;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (813, 8688, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 814;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (814, 8701, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 815;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (815, 8714, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 816;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (816, 8727, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 817;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (817, 8740, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 818;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (818, 8753, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 819;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (819, 8766, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 820;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (820, 8818, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 821;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (821, 8831, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 822;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (822, 8844, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 823;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (823, 8857, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 824;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (824, 8870, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 825;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (825, 8883, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 826;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (826, 8896, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 827;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (827, 8909, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 828;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (828, 8921, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 829;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (829, 8933, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 833;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (833, 8958, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 835;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (835, 8971, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 836;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (836, 8985, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 842;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (842, 8999, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 843;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (843, 9011, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 844;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (844, 9023, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 903;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (903, 9038, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1309;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1309, 9156, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1358;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1358, 9172, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1562;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1562, 9187, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1620;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1620, 9201, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1676;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1676, 9217, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1717;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1717, 9237, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1718;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1718, 9251, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1719;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1719, 9265, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1722;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1722, 9279, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1726;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1726, 9051, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1727;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1727, 9065, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1728;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1728, 9079, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1729;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1729, 9093, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1759;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1759, 9293, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1836;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1836, 9307, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1840;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1840, 9322, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 1868;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (1868, 9338, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2026;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2026, 9107, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2027;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2027, 9123, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2069;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2069, 9355, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2071;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2071, 9370, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2072;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2072, 9139, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2074;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2074, 9385, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2090;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2090, 9403, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2091;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2091, 9420, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2095;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2095, 9437, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2096;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2096, 9455, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2098;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2098, 9475, '');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2099;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2099, 9491, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2103;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2103, 9506, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 2104;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (2104, 9527, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 3892;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (3892, 9548, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 3963;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (3963, 9568, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 3964;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (3964, 9586, 'ElwFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 3965;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (3965, 9604, 'wFlo01.mdl');
DELETE FROM `groundeffectdoodad` WHERE `id` = 8230;
INSERT INTO `groundeffectdoodad` (`id`, `internal_id`, `model_path`) VALUES (8230, 8945, '');
UPDATE `groundeffectdoodad` SET `internal_id` = 8455 WHERE `id` = 795;
UPDATE `groundeffectdoodad` SET `internal_id` = 8467 WHERE `id` = 796;
UPDATE `groundeffectdoodad` SET `internal_id` = 8479 WHERE `id` = 797;
UPDATE `groundeffectdoodad` SET `internal_id` = 8491 WHERE `id` = 798;