-- [BASE,F-136] open-azeroth: groundeffecttexture
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-136]_groundeffecttexture.sql with overrides

-- groundeffecttexture: 173 inserts, 7 updates, 0 deletes
DELETE FROM `groundeffecttexture` WHERE `id` = 18070;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18070, 711, 7, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18083;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18083, 709, 5, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18084;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18084, 718, 4, 8, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 18085;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18085, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18093;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18093, 710, 6, 24, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 18118;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18118, 716, 7, 24, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 18119;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18119, 719, 2, 2, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 18231;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18231, 711, 7, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18236;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18236, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18242;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18242, 709, 5, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18254;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18254, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18313;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18313, 19, 1, 1, 7);
DELETE FROM `groundeffecttexture` WHERE `id` = 18316;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18316, 19, 1, 1, 7);
DELETE FROM `groundeffecttexture` WHERE `id` = 18318;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18318, 714, 10, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18319;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18319, 713, 10, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18430;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18430, 711, 7, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18458;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18458, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18459;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18459, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18460;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18460, 711, 7, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18462;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18462, 711, 7, 24, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 18466;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18466, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18470;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18470, 710, 6, 24, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 18775;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18775, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18781;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18781, 710, 6, 24, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 18788;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18788, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18790;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18790, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18795;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18795, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18799;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18799, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18981;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18981, 716, 8, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 18983;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (18983, 719, 24, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19061;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19061, 718, 1, 8, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 19106;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19106, 717, 1, 2, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19162;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19162, 716, 7, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19164;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19164, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19166;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19166, 719, 2, 2, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19167;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19167, 709, 5, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19169;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19169, 717, 4, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19182;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19182, 709, 5, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19184;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19184, 711, 7, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19194;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19194, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19196;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19196, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19202;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19202, 716, 7, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19203;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19203, 717, 4, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19207;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19207, 716, 3, 4, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19208;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19208, 719, 1, 1, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19209;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19209, 719, 2, 2, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19294;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19294, 738, 1, 0, 8);
DELETE FROM `groundeffecttexture` WHERE `id` = 19295;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19295, 735, 1, 0, 8);
DELETE FROM `groundeffecttexture` WHERE `id` = 19653;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19653, 805, 2, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19654;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19654, 805, 2, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19676;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19676, 711, 1, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19712;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19712, 752, 8, 16, 9);
DELETE FROM `groundeffecttexture` WHERE `id` = 19761;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19761, 750, 4, 1, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 19776;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19776, 750, 1, 1, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 19777;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19777, 758, 4, 4, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 19794;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19794, 711, 7, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19795;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19795, 709, 5, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19798;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19798, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19827;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19827, 711, 7, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19828;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19828, 709, 5, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19831;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19831, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 19863;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19863, 743, 4, 6, 12);
DELETE FROM `groundeffecttexture` WHERE `id` = 19865;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (19865, 734, 1, 10, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 64601;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (64601, 738, 1, 0, 8);
DELETE FROM `groundeffecttexture` WHERE `id` = 69264;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (69264, 805, 1, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 69491;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (69491, 709, 1, 0, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 69525;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (69525, 709, 1, 1, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 69792;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (69792, 186, 1, 5, 8);
DELETE FROM `groundeffecttexture` WHERE `id` = 70369;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (70369, 714, 10, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 70371;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (70371, 713, 10, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 70406;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (70406, 777, 1, 3, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 70408;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (70408, 778, 1, 3, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 71829;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (71829, 714, 10, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 71830;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (71830, 713, 10, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 72126;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (72126, 142, 1, 6, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 72183;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (72183, 783, 1, 10, 7);
DELETE FROM `groundeffecttexture` WHERE `id` = 72186;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (72186, 780, 2, 4, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 72330;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (72330, 780, 12, 4, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 72998;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (72998, 782, 2, 10, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 73624;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73624, 835, 1, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 73637;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73637, 0, 1, 7, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 73638;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73638, 0, 1, 2, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 73639;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73639, 0, 1, 7, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 73640;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73640, 0, 1, 7, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 73811;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73811, 810, 1, 1, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 73812;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73812, 818, 1, 1, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 73815;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73815, 700, 1, 3, 2);
DELETE FROM `groundeffecttexture` WHERE `id` = 73816;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73816, 793, 1, 2, 2);
DELETE FROM `groundeffecttexture` WHERE `id` = 73818;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (73818, 792, 1, 2, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 74117;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (74117, 754, 1, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 74263;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (74263, 784, 5, 10, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 74540;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (74540, 821, 1, 1, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 74541;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (74541, 821, 1, 1, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 74548;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (74548, 813, 1, 2, 8);
DELETE FROM `groundeffecttexture` WHERE `id` = 74822;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (74822, 823, 1, 2, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 75149;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (75149, 715, 1, 0, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 75150;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (75150, 712, 5, 0, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 75179;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (75179, 721, 8, 8, 12);
DELETE FROM `groundeffecttexture` WHERE `id` = 75901;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (75901, 710, 1, 5, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 75902;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (75902, 711, 8, 8, 9);
DELETE FROM `groundeffecttexture` WHERE `id` = 75903;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (75903, 711, 8, 8, 9);
DELETE FROM `groundeffecttexture` WHERE `id` = 75929;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (75929, 712, 5, 3, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 76587;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (76587, 710, 6, 24, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 77144;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (77144, 816, 2, 10, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 77149;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (77149, 816, 2, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 77285;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (77285, 711, 2, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 77359;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (77359, 716, 8, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 77493;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (77493, 721, 12, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 77520;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (77520, 713, 10, 1, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 77565;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (77565, 721, 1, 10, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 77720;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (77720, 719, 1, 1, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 77721;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (77721, 709, 1, 4, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 78627;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (78627, 0, 1, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 78628;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (78628, 711, 1, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 78827;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (78827, 836, 6, 12, 8);
DELETE FROM `groundeffecttexture` WHERE `id` = 78975;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (78975, 716, 1, 5, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 79496;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79496, 709, 5, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79498;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79498, 711, 7, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79504;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79504, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79506;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79506, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79512;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79512, 716, 7, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79513;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79513, 717, 4, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79514;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79514, 719, 2, 2, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79595;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79595, 717, 1, 2, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79601;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79601, 716, 3, 4, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79602;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79602, 719, 1, 1, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79738;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79738, 716, 8, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79740;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79740, 719, 24, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79747;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79747, 718, 1, 8, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 79834;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79834, 716, 7, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79836;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79836, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79838;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79838, 719, 2, 2, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79839;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79839, 709, 5, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 79841;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (79841, 717, 4, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 80175;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80175, 835, 1, 8, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 80180;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80180, 810, 1, 1, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 80188;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80188, 836, 6, 12, 8);
DELETE FROM `groundeffecttexture` WHERE `id` = 80516;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80516, 710, 1, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 80519;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80519, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 80535;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80535, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 80539;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80539, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 80543;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80543, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 80645;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80645, 710, 6, 24, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 80654;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (80654, 458, 1, 3, 8);
DELETE FROM `groundeffecttexture` WHERE `id` = 81298;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (81298, 716, 1, 5, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 81358;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (81358, 836, 4, 8, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 81360;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (81360, 810, 2, 2, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 81362;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (81362, 713, 4, 4, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 81553;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (81553, 716, 1, 5, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 82244;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (82244, 716, 1, 5, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 82251;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (82251, 711, 1, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 82272;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (82272, 711, 1, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 82275;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (82275, 721, 1, 8, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 82282;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (82282, 711, 1, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 82287;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (82287, 716, 1, 5, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 85712;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (85712, 716, 4, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 85714;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (85714, 718, 4, 12, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 85718;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (85718, 750, 3, 1, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 149976;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (149976, 0, 1, 8, 2);
DELETE FROM `groundeffecttexture` WHERE `id` = 158239;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158239, 1726, 3, 8, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 158392;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158392, 0, 1, 0, 2);
DELETE FROM `groundeffecttexture` WHERE `id` = 158532;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158532, 2072, 8, 20, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 158902;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158902, 0, 1, 8, 2);
DELETE FROM `groundeffecttexture` WHERE `id` = 158916;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158916, 1868, 30, 10, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 158918;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158918, 2095, 43, 11, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 158919;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158919, 1309, 43, 5, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 158920;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158920, 2074, 10, 9, 5);
DELETE FROM `groundeffecttexture` WHERE `id` = 158922;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158922, 2090, 33, 8, 2);
DELETE FROM `groundeffecttexture` WHERE `id` = 158923;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158923, 1716, 15, 4, 0);
DELETE FROM `groundeffecttexture` WHERE `id` = 158924;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158924, 3963, 19, 8, 2);
DELETE FROM `groundeffecttexture` WHERE `id` = 158925;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158925, 2104, 21, 1, 2);
DELETE FROM `groundeffecttexture` WHERE `id` = 158926;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (158926, 2099, 15, 5, 1);
DELETE FROM `groundeffecttexture` WHERE `id` = 159380;
INSERT INTO `groundeffecttexture` (`id`, `doodad_id_1`, `doodad_weight_1`, `density`, `terrain_type_id`) VALUES (159380, 3965, 52, 3, 0);
UPDATE `groundeffecttexture` SET `doodad_id_1` = 138, `density` = 6 WHERE `id` = 5274;
UPDATE `groundeffecttexture` SET `doodad_id_1` = 137, `density` = 8, `terrain_type_id` = 6 WHERE `id` = 7818;
UPDATE `groundeffecttexture` SET `doodad_id_1` = 4, `density` = 5, `terrain_type_id` = 8 WHERE `id` = 7828;
UPDATE `groundeffecttexture` SET `doodad_id_1` = 186, `density` = 8, `terrain_type_id` = 6 WHERE `id` = 8058;
UPDATE `groundeffecttexture` SET `doodad_id_1` = 189, `density` = 8, `terrain_type_id` = 6 WHERE `id` = 8061;
UPDATE `groundeffecttexture` SET `doodad_id_1` = 189, `density` = 8, `terrain_type_id` = 5 WHERE `id` = 8097;
UPDATE `groundeffecttexture` SET `doodad_id_1` = 709, `density` = 2 WHERE `id` = 44329;