-- [BASE,F-049] hd-everything: characterfacialhairstyles
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-049]_characterfacialhairstyles.sql with overrides

-- characterfacialhairstyles: 50 inserts, 0 updates, 0 deletes
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 1);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 5;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 6;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 6);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 7;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 7);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 8;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 8);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 9);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 10;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 10);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 11;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 11);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 12;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 12);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 13;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 13);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 14;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 14);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 15;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 15);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 16;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 16);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 17;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 17);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 18;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 18);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 19;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 19);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 20;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 20);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 21;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 21);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 22;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 22);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 23;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 23);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 0 AND `variation_id` = 24;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 0, 24);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 1);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 3);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 4);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 5;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 5);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 6;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 6);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 7;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 7);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 8;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 8);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 9);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 10;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 10);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 11;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 11);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 12;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 12);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 13;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 13);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 14;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 14);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 15;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 15);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 16;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 16);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 17;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 17);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 18;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 18);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 19;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 19);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 20;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 20);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 21;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 21);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 22;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 22);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 23;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 23);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 9 AND `gender` = 1 AND `variation_id` = 24;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`) VALUES (9, 1, 24);