DELETE FROM `skinning_loot_template` WHERE (`Entry` = 299);
INSERT INTO `skinning_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(299, 2934, 0, 100, 0, 1, 0, 1, 3, '');

DELETE FROM `creature_template` WHERE (`entry` = 299);
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `scale`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES
(299, 0, 0, 0, 0, 0, 447, 0, 0, 0, 'Young Wolf', '', NULL, 0, 1, 1, 0, 32, 0, 1, 0.857143, 1, 1, 10, 1, 0, 0, 1, 2000, 2000, 1, 1, 1, 0, 2048, 0, 1, 0, 0, 0, 0, 1, 1, 299, 0, 299, 13059, 0, 0, 0, '', 1, 1, 1, 1, 1, 1, 0, 100, 1, 0, 0, 2, '', 12340);

DELETE FROM `creature_template` WHERE (`entry` = 69);
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `scale`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES
(69, 0, 0, 0, 0, 0, 604, 0, 0, 0, 'Timber Wolf', NULL, NULL, 0, 2, 2, 0, 32, 0, 1, 0.857143, 1, 1, 10, 1, 0, 0, 1, 2000, 2000, 1, 1, 1, 0, 2048, 0, 1, 0, 0, 0, 0, 1, 1, 69, 0, 299, 13060, 0, 0, 0, '', 1, 1, 1, 1, 1, 1, 0, 100, 1, 0, 0, 2, '', 12340);
