"""
Dungeon Daily Quest Creator (F-018)

Reads quest definitions from CSV and generates SQL for daily dungeon quests
including quest templates, pool assignments, loot tables, POIs, and NPC links.
"""

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

DATA_DIR = Path(__file__).parent / 'data'
QUESTS_CSV = DATA_DIR / 'Dungeon Daily Quests.csv'
TELEPORTS_CSV = DATA_DIR / 'Dungeon Daily Teleports.csv'

OUTPUT_FILENAME = "zz_[AUTO,F-018]_daily_dungeon_quests.sql"

SQL_HEADER = """\
-- ===================================================================
-- F-018 Daily Dungeon Quests
-- ===================================================================
-- AUTO-GENERATED by: zep world dungeon quests
-- DO NOT EDIT MANUALLY - Regenerate with: zep world dungeon quests
-- Source data: cli/lib/dungeon/data/Dungeon Daily Quests.csv
-- ===================================================================

"""

DIFFICULTY_SCALES = {
    "Vanilla Normal": 1,
    "Outland Normal": 1.5,
    "Heroic": 2,
    "Mythic": 4,
}

DIFFICULTY_REWARDS = {
    "Vanilla Normal":  (58200, 1, 58302, 3),   # Badge of Heroism x1, Azerite Shard x3
    "Vanilla Heroic":  (58200, 2, 58302, 4),
    "Vanilla Mythic":  (58200, 3, 58302, 5),
    "Outland Normal":  (29434, 1, 58302, 3),   # Badge of Justice x1, Azerite Shard x3
}


@dataclass
class FactionConfig:
    npc_id: int
    npc_name: str
    city: str
    rep1: int
    rep2: int
    rep3: int
    reward_text: str
    flag: int
    poi_map_id: int
    poi_world_map_area_id: int
    poi_x: int
    poi_y: int


FACTION_CONFIGS: Dict[str, FactionConfig] = {
    "Horde": FactionConfig(
        npc_id=14392, npc_name="Overlord Runthak", city="Orgrimmar",
        rep1=67, rep2=0, rep3=0,
        reward_text="Your deeds bring honour to the Horde.",
        flag=4104, poi_map_id=1, poi_world_map_area_id=321, poi_x=1568, poi_y=-4406,
    ),
    "Alliance": FactionConfig(
        npc_id=29093, npc_name="Travis Coomingham", city="Stormwind",
        rep1=469, rep2=0, rep3=0,
        reward_text="Thanks for thwartin'' them Horde plans, Zuglord Runthak''ll be seethin'' knowing we beat ''em to the punch.",
        flag=4104, poi_map_id=0, poi_world_map_area_id=301, poi_x=-8807, poi_y=638,
    ),
    "Thrallmar / Honor Hold": FactionConfig(
        npc_id=24370, npc_name="Nether-Stalker Mah''duun", city="Shattrath",
        rep1=933, rep2=946, rep3=947,
        reward_text="My buyer will be most pleased.",
        flag=4232, poi_map_id=530, poi_world_map_area_id=481, poi_x=-1797, poi_y=5149,
    ),
    "Cenarion Expedition": FactionConfig(
        npc_id=24370, npc_name="Nether-Stalker Mah''duun", city="Shattrath",
        rep1=933, rep2=942, rep3=0,
        reward_text="My buyer will be most pleased.",
        flag=4232, poi_map_id=530, poi_world_map_area_id=481, poi_x=-1797, poi_y=5149,
    ),
    "Consortium": FactionConfig(
        npc_id=24370, npc_name="Nether-Stalker Mah''duun", city="Shattrath",
        rep1=933, rep2=0, rep3=0,
        reward_text="My buyer will be most pleased.",
        flag=4232, poi_map_id=530, poi_world_map_area_id=481, poi_x=-1797, poi_y=5149,
    ),
    "Sha'tar": FactionConfig(
        npc_id=24370, npc_name="Nether-Stalker Mah''duun", city="Shattrath",
        rep1=933, rep2=935, rep3=0,
        reward_text="My buyer will be most pleased.",
        flag=4232, poi_map_id=530, poi_world_map_area_id=481, poi_x=-1797, poi_y=5149,
    ),
    "Keepers of Time": FactionConfig(
        npc_id=24370, npc_name="Nether-Stalker Mah''duun", city="Shattrath",
        rep1=933, rep2=989, rep3=0,
        reward_text="My buyer will be most pleased.",
        flag=4232, poi_map_id=530, poi_world_map_area_id=481, poi_x=-1797, poi_y=5149,
    ),
    "Lower City": FactionConfig(
        npc_id=24370, npc_name="Nether-Stalker Mah''duun", city="Shattrath",
        rep1=933, rep2=1011, rep3=0,
        reward_text="My buyer will be most pleased.",
        flag=4232, poi_map_id=530, poi_world_map_area_id=481, poi_x=-1797, poi_y=5149,
    ),
    "Shattered Sun Offensive": FactionConfig(
        npc_id=24370, npc_name="Nether-Stalker Mah''duun", city="Shattrath",
        rep1=933, rep2=1077, rep3=0,
        reward_text="My buyer will be most pleased.",
        flag=4232, poi_map_id=530, poi_world_map_area_id=481, poi_x=-1797, poi_y=5149,
    ),
}


@dataclass
class DungeonQuest:
    quest_id: int
    dungeon: str
    faction: str
    item_id: int
    item_name: str
    item_display_id: int
    quest_desc: str
    sort_id: int
    boss_name: str
    boss_id: int
    boss_idx: int
    boss_level: int
    pool_id: int
    pool_min: int
    pool_max: int
    difficulty: str


def get_dungeon_orb(dungeon_name: str, teleports_csv: Path = TELEPORTS_CSV) -> Optional[int]:
    """Look up teleport orb ID for a dungeon from the teleports CSV."""
    with open(teleports_csv, mode='r', newline='', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            if row[0] == dungeon_name:
                return int(row[1])
    return None


def load_quests(csv_path: Path = QUESTS_CSV) -> List[DungeonQuest]:
    """Load quest definitions from CSV."""
    quests = []
    with open(csv_path, mode='r', newline='', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)  # Skip header
        for row in reader:
            if not row[4]:  # Skip if no item name
                continue
            quests.append(DungeonQuest(
                quest_id=int(row[0]),
                dungeon=row[1],
                faction=row[2],
                item_id=int(row[3]),
                item_name=row[4],
                item_display_id=int(row[5]),
                quest_desc=row[6],
                sort_id=int(row[7]),
                boss_name=row[8],
                boss_id=int(row[9]),
                boss_idx=int(row[10]),
                boss_level=int(row[11]) if row[11].isdigit() else 0,
                pool_id=int(row[12]),
                pool_min=int(row[13]),
                pool_max=int(row[14]),
                difficulty=row[15],
            ))
    return quests


def generate_sql(quests: List[DungeonQuest], teleports_csv: Path = TELEPORTS_CSV) -> str:
    """Generate SQL for all daily dungeon quests."""
    lines = [SQL_HEADER]
    processed_bosses = set()

    for q in quests:
        fc = FACTION_CONFIGS.get(q.faction)
        if fc is None:
            continue

        teleport_orb_id = get_dungeon_orb(q.dungeon, teleports_csv)
        if teleport_orb_id is None:
            teleport_orb_id = 0

        # Calculate money reward
        scale = DIFFICULTY_SCALES.get(q.difficulty, 1)
        money = int(q.boss_level * q.boss_level * 30 * scale)

        # Get item rewards for difficulty
        reward_1, rewardamount_1, reward_2, rewardamount_2 = DIFFICULTY_REWARDS.get(
            q.difficulty, (58200, 1, 58302, 3)
        )

        # Pool quest
        lines.append("")
        lines.append("-- *******************************************************")
        lines.append("")
        lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.faction} - Pool Quest")
        lines.append(f"DELETE FROM `pool_quest` WHERE (`entry` = {q.quest_id});")
        lines.append(f"INSERT INTO `pool_quest`")
        lines.append(f"SET `entry` = {q.quest_id},")
        lines.append(f"    `pool_entry` = {q.pool_id},")
        lines.append(f"    `description` = '{q.boss_name}';")
        lines.append("")

        # Quest template
        lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.faction} - Quest Template")
        lines.append(f"DELETE FROM `quest_template` WHERE (`ID` = {q.quest_id});")
        lines.append(f"INSERT INTO `quest_template`")
        lines.append(f"SET `ID` = {q.quest_id},")
        lines.append(f"    `QuestType` = 2,")
        lines.append(f"    `QuestLevel` = {q.boss_level},")
        lines.append(f"    `MinLevel` = {q.pool_min},")
        lines.append(f"    `QuestSortID` = {q.sort_id},")
        lines.append(f"    `QuestInfoID` = 81,")
        lines.append(f"    `RewardXPDifficulty` = 7,")
        lines.append(f"    `RewardMoney` = {money},")
        lines.append(f"    `StartItem` = {teleport_orb_id},")
        lines.append(f"    `Flags` = {fc.flag},")
        lines.append(f"    `RewardItem1` = {reward_1},")
        lines.append(f"    `RewardAmount1` = {rewardamount_1},")
        lines.append(f"    `RewardItem2` = {reward_2},")
        lines.append(f"    `RewardAmount2` = {rewardamount_2},")
        lines.append(f"    `RewardFactionID1` = {fc.rep1},")
        lines.append(f"    `RewardFactionValue1` = 6,")
        lines.append(f"    `RewardFactionID2` = {fc.rep2},")
        lines.append(f"    `RewardFactionValue2` = 6,")
        lines.append(f"    `RewardFactionID3` = {fc.rep3},")
        lines.append(f"    `RewardFactionValue3` = 6,")
        lines.append(f"    `LogTitle` = 'Wanted: {q.item_name}',")
        lines.append(f"    `LogDescription` = 'Retrieve the {q.item_name} from {q.boss_name} in {q.dungeon}.',")
        lines.append(f"    `QuestDescription` = '{q.quest_desc}',")
        lines.append(f"    `AreaDescription` = '',")
        lines.append(f"    `QuestCompletionLog` = 'Return the {q.item_name} to {fc.npc_name} in {fc.city}.',")
        lines.append(f"    `RequiredItemId1` = {q.item_id},")
        lines.append(f"    `RequiredItemCount1` = 1,")
        lines.append(f"    `VerifiedBuild` = 12340;")
        lines.append("")

        # Quest template addon
        lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.faction} - Quest Template Addon")
        lines.append(f"DELETE FROM `quest_template_addon` WHERE (`ID` = {q.quest_id});")
        lines.append(f"INSERT INTO `quest_template_addon`")
        lines.append(f"SET `ID` = {q.quest_id},")
        lines.append(f"    `ProvidedItemCount` = 1,")
        lines.append(f"    `MaxLevel` = {q.pool_max},")
        lines.append(f"    `SpecialFlags` = 1;")
        lines.append("")

        # Quest offer reward
        lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.faction} - Quest Offer Reward")
        lines.append(f"DELETE FROM `quest_offer_reward` WHERE (`ID` = {q.quest_id});")
        lines.append(f"INSERT INTO `quest_offer_reward`")
        lines.append(f"SET `ID` = {q.quest_id},")
        lines.append(f"    `Emote1` = 1,")
        lines.append(f"    `RewardText` = '{fc.reward_text}';")
        lines.append("")

        # Quest request items
        lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.faction} - Quest Request Items")
        lines.append(f"DELETE FROM `quest_request_items` WHERE (`ID` = {q.quest_id});")
        lines.append(f"INSERT INTO `quest_request_items`")
        lines.append(f"SET `ID` = {q.quest_id},")
        lines.append(f"    `EmoteOnComplete` = 1,")
        lines.append(f"    `EmoteOnIncomplete` = 1,")
        lines.append(f"    `CompletionText` = 'The {q.item_name} please.';")
        lines.append("")

        # Creature quest starter
        lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.faction} - Creature Quest Starter")
        lines.append(f"DELETE FROM `creature_queststarter` WHERE (`quest` = {q.quest_id});")
        lines.append(f"INSERT INTO `creature_queststarter`")
        lines.append(f"SET`quest` = {q.quest_id},")
        lines.append(f"    `id` = {fc.npc_id};")
        lines.append("")

        # Creature quest ender
        lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.faction} - Creature Quest Ender")
        lines.append(f"DELETE FROM `creature_questender` WHERE (`quest` = {q.quest_id});")
        lines.append(f"INSERT INTO `creature_questender`")
        lines.append(f"    SET `quest` = {q.quest_id},")
        lines.append(f"    `id` = {fc.npc_id};")
        lines.append("")

        # Quest POI
        lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.faction} - Quest POI (Turn-in)")
        lines.append(f"DELETE FROM `quest_poi` WHERE (`QuestID` = {q.quest_id});")
        lines.append(f"INSERT INTO `quest_poi` (`QuestID`, `id`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `VerifiedBuild`)")
        lines.append(f"VALUES ({q.quest_id}, 0, -1, {fc.poi_map_id}, {fc.poi_world_map_area_id}, 0, 0, 1, 0);")
        lines.append("")
        lines.append(f"DELETE FROM `quest_poi_points` WHERE (`QuestID` = {q.quest_id});")
        lines.append(f"INSERT INTO `quest_poi_points` (`QuestID`, `Idx1`, `Idx2`, `X`, `Y`, `VerifiedBuild`)")
        lines.append(f"VALUES ({q.quest_id}, 0, 0, {fc.poi_x}, {fc.poi_y}, 0);")
        lines.append("")

        # Boss-specific entries (only once per boss)
        boss_key = str(q.boss_id)
        if boss_key not in processed_bosses:
            processed_bosses.add(boss_key)

            # Item template
            lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.item_name} - Item template")
            lines.append(f"DELETE FROM `item_template` WHERE (`entry` = {q.item_id});")
            lines.append(f"INSERT INTO `item_template`")
            lines.append(f"SET `entry` = {q.item_id},")
            lines.append(f"    `class` = 12,")
            lines.append(f"    `subclass` = 0,")
            lines.append(f"    `name` = '{q.item_name}',")
            lines.append(f"    `flags` = '2048',")
            lines.append(f"    `displayid` = {q.item_display_id},")
            lines.append(f"    `Quality` = 1,")
            lines.append(f"    `bonding` = 4;")
            lines.append("")

            # Creature quest item
            lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.item_name} - Quest Item")
            lines.append(f"DELETE FROM `creature_questitem` WHERE (`CreatureEntry` = {q.boss_id}) AND (`ItemId` = {q.item_id});")
            lines.append(f"INSERT INTO `creature_questitem`")
            lines.append(f"SET `CreatureEntry` = {q.boss_id},")
            lines.append(f"    `Idx` = {q.boss_idx},")
            lines.append(f"    `ItemId` = {q.item_id};")
            lines.append("")

            # Creature loot template
            lines.append(f"-- {q.dungeon} - {q.boss_name} - {q.item_name} - Loot Template")
            lines.append(f"DELETE FROM `creature_loot_template` WHERE (`Entry` = {q.boss_id}) AND (`Item` IN ({q.item_id}));")
            lines.append(f"INSERT INTO `creature_loot_template`")
            lines.append(f"SET `Entry` = {q.boss_id},")
            lines.append(f"    `Item` = {q.item_id},")
            lines.append(f"    `Chance` = 100,")
            lines.append(f"    `QuestRequired` = 1,")
            lines.append(f"    `LootMode` = 1,")
            lines.append(f"    `GroupId` = 0,")
            lines.append(f"    `MinCount` = 1,")
            lines.append(f"    `MaxCount` = 1,")
            lines.append(f"    `Comment` = '{q.item_name}';")
            lines.append("")

        lines.append("")

    return "\n".join(lines)


def run(output_path: Path, verbose: bool = True) -> Tuple[int, int]:
    """Load quests, generate SQL, write to file.

    Returns (quest_count, 0).
    """
    quests = load_quests()

    if verbose:
        for q in quests:
            print(f"  {q.dungeon:<35} {q.faction:<25} {q.boss_name}")

    sql_content = generate_sql(quests)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(sql_content)

    return len(quests), 0
