"""
Dungeon Daily Teleport Creator (F-018)

Reads dungeon definitions from CSV and generates SQL for teleport orb items
and spell_target_position entries.
"""

import csv
import random
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

DATA_DIR = Path(__file__).parent / 'data'
CSV_FILE = DATA_DIR / 'Dungeon Daily Teleports.csv'

OUTPUT_FILENAME = "zz_[AUTO,F-018]_daily_dungeon_teleports.sql"

ORB_ICONS = [141021, 141022, 141023, 141024, 141025, 141026]

SQL_HEADER = """\
-- ===================================================================
-- F-018 Daily Dungeon Teleports — Orb Items & Spell Positions
-- ===================================================================
-- AUTO-GENERATED by: zep world dungeon teleports
-- DO NOT EDIT MANUALLY - Regenerate with: zep world dungeon teleports
-- Source data: cli/lib/dungeon/data/Dungeon Daily Teleports.csv
-- ===================================================================

"""


@dataclass
class DungeonTeleport:
    dungeon: str
    orb_id: int
    orb_spell: int
    map_id: int
    x: float
    y: float
    z: float
    orientation: float


def load_dungeons(csv_path: Path = CSV_FILE) -> List[DungeonTeleport]:
    """Load dungeon teleport definitions from CSV."""
    dungeons = []
    with open(csv_path, mode='r', newline='', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)  # Skip header
        for row in reader:
            if not row[3]:  # Skip if no map
                continue
            dungeons.append(DungeonTeleport(
                dungeon=row[0],
                orb_id=int(row[1]),
                orb_spell=int(row[2]),
                map_id=int(row[3]),
                x=float(row[4]),
                y=float(row[5]),
                z=float(row[6]),
                orientation=float(row[7]),
            ))
    return dungeons


def generate_sql(dungeons: List[DungeonTeleport]) -> str:
    """Generate SQL for all dungeon teleport orbs and spell positions."""
    lines = [SQL_HEADER]

    for d in dungeons:
        display_id = random.choice(ORB_ICONS)

        # Spell target position
        lines.append(f"-- {d.dungeon} - Teleport Location")
        lines.append(f"DELETE FROM `spell_target_position` WHERE (`ID` = {d.orb_spell});")
        lines.append(f"INSERT INTO `spell_target_position`")
        lines.append(f"SET `ID` = {d.orb_spell},")
        lines.append(f"    `EffectIndex` = '0',")
        lines.append(f"    `MapID` = {d.map_id},")
        lines.append(f"    `PositionX` = {d.x},")
        lines.append(f"    `PositionY` = {d.y},")
        lines.append(f"    `PositionZ` = {d.z},")
        lines.append(f"    `Orientation` = {d.orientation},")
        lines.append(f"    `VerifiedBuild` = '0';")
        lines.append("")

        # Teleport orb item
        lines.append(f"-- {d.dungeon} - Teleport Orb")
        lines.append(f"DELETE FROM `item_template` WHERE (`entry` = {d.orb_id});")
        lines.append(f"INSERT INTO `item_template`")
        lines.append(f"SET `entry` = {d.orb_id},")
        lines.append(f"    `name` = 'Orb of Teleport {d.dungeon}',")
        lines.append(f"    `class` = 12,")
        lines.append(f"    `displayid` = '{display_id}',")
        lines.append(f"    `Quality` = '1',")
        lines.append(f"    `bonding` = '4',")
        lines.append(f"    `spellid_1` = {d.orb_spell},")
        lines.append(f"    `spellcharges_1` = '-1';")
        lines.append("")
        lines.append("")

    return "\n".join(lines)


def run(
    output_path: Path,
    seed: Optional[int] = None,
    verbose: bool = True
) -> Tuple[int, int]:
    """Load dungeons, generate SQL, write to file.

    Returns (dungeon_count, 0).
    """
    if seed is not None:
        random.seed(seed)

    dungeons = load_dungeons()

    if verbose:
        for d in dungeons:
            print(f"  {d.dungeon:<35} orb={d.orb_id}  spell={d.orb_spell}  map={d.map_id}")

    sql_content = generate_sql(dungeons)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(sql_content)

    return len(dungeons), 0
