"""
City Teleport Creator (F-017)

Reads city definitions from CSV and generates SQL for inscription-based
teleport scrolls, technique recipes, vendor entries, and teleport positions.
"""

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple

DATA_DIR = Path(__file__).parent / 'data'
CSV_FILE = DATA_DIR / 'City Teleports.csv'

OUTPUT_FILENAME = "zz_[AUTO,F-017]_city_teleports.sql"

SQL_HEADER = """\
-- ===================================================================
-- F-017 City Teleports — Inscription Scrolls & Techniques
-- ===================================================================
-- AUTO-GENERATED by: zep world teleport generate
-- DO NOT EDIT MANUALLY - Regenerate with: zep world teleport generate
-- Source data: cli/lib/teleport/data/City Teleports.csv
-- ===================================================================

"""


@dataclass
class CityTeleport:
    city: str
    scroll_id: int
    scroll_spell: int
    scroll_display: int
    technique_id: int
    technique_spell: int
    inscription_level: int
    vendor_ids: List[int]
    vendor_names: List[str]
    map_id: int
    pos_x: float
    pos_y: float
    pos_z: float
    orientation: float


def load_cities(csv_path: Path = CSV_FILE) -> List[CityTeleport]:
    """Load city teleport definitions from CSV."""
    cities = []
    with open(csv_path, mode='r', newline='', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)  # Skip header
        for row in reader:
            if not row[0]:
                continue
            cities.append(CityTeleport(
                city=row[0],
                scroll_id=int(row[1]),
                scroll_spell=int(row[2]),
                scroll_display=int(row[3]),
                technique_id=int(row[4]),
                technique_spell=int(row[5]),
                inscription_level=int(row[6]),
                vendor_ids=[int(v) for v in row[7].split(';')],
                vendor_names=[n.strip() for n in row[8].split(';')],
                map_id=int(row[9]),
                pos_x=float(row[10]),
                pos_y=float(row[11]),
                pos_z=float(row[12]),
                orientation=float(row[13]),
            ))
    return cities


def generate_sql(cities: List[CityTeleport]) -> str:
    """Generate SQL for all city teleport scrolls, techniques, vendors, and positions."""
    lines = [SQL_HEADER]

    for city in cities:
        # Scroll item
        lines.append(f"-- Scroll of Teleport {city.city}")
        lines.append(f"DELETE FROM `item_template` WHERE (`entry` = {city.scroll_id});")
        lines.append(f"INSERT INTO `item_template`")
        lines.append(f"SET `entry` = {city.scroll_id},")
        lines.append(f"    `name` = 'Scroll of Teleport {city.city}',")
        lines.append(f"    `displayid` = {city.scroll_display},")
        lines.append(f"    `Quality` = 2,")
        lines.append(f"    `bonding` = 1,")
        lines.append(f"    `stackable` = 20,")
        lines.append(f"    `RequiredSkill` = 773,")
        lines.append(f"    `RequiredSkillRank` = {city.inscription_level},")
        lines.append(f"    `spellid_1` = {city.scroll_spell},")
        lines.append(f"    `spellcharges_1` = -1;")
        lines.append("")

        # Technique item
        lines.append(f"-- Technique: Scroll of Teleport {city.city}")
        lines.append(f"DELETE FROM `item_template` WHERE (`entry` = {city.technique_id});")
        lines.append(f"INSERT INTO `item_template`")
        lines.append(f"SET `entry` = {city.technique_id},")
        lines.append(f"    `name` = 'Technique: Scroll of Teleport {city.city}',")
        lines.append(f"    `description` = 'Teaches you how to inscribe a Scroll of Teleport: {city.city}.',")
        lines.append(f"    `displayid` = 1103,")
        lines.append(f"    `Quality` = 2,")
        lines.append(f"    `bonding` = 1,")
        lines.append(f"    `BuyPrice` = 10000,")
        lines.append(f"    `SellPrice` = 2500,")
        lines.append(f"    `RequiredSkill` = 773,")
        lines.append(f"    `RequiredSkillRank` = {city.inscription_level},")
        lines.append(f"    `spellid_1` = 483,")
        lines.append(f"    `spellcharges_1` = -1,")
        lines.append(f"    `spellid_2` = {city.technique_spell},")
        lines.append(f"    `spelltrigger_2` = 6;")
        lines.append("")

        # Vendor entries
        lines.append(f"DELETE FROM `npc_vendor` WHERE (`item` = {city.technique_id});")
        for vid, vname in zip(city.vendor_ids, city.vendor_names):
            lines.append(f"-- {vname} - Scroll of Teleport {city.city}")
            lines.append(f"INSERT INTO `npc_vendor`")
            lines.append(f"SET `entry` = {vid},")
            lines.append(f"    `item` = {city.technique_id};")
        lines.append("")
        lines.append("")

    # Teleport positions
    lines.append("-- ===================================================================")
    lines.append("-- Teleport Locations")
    lines.append("-- ===================================================================")
    lines.append("")

    for city in cities:
        lines.append(f"-- {city.city}")
        lines.append(f"DELETE FROM `spell_target_position` WHERE `ID` = {city.scroll_spell};")
        lines.append(f"INSERT INTO `spell_target_position`")
        lines.append(f"SET `ID` = {city.scroll_spell},")
        if city.map_id != 0:
            lines.append(f"    `MapID` = {city.map_id},")
        lines.append(f"    `PositionX` = {city.pos_x:.2f},")
        lines.append(f"    `PositionY` = {city.pos_y:.2f},")
        lines.append(f"    `PositionZ` = {city.pos_z:.2f},")
        lines.append(f"    `Orientation` = {city.orientation:.2f};")
        lines.append("")

    # Rune of Teleportation tweaks
    lines.append("-- ===================================================================")
    lines.append("-- Rune of Teleportation — price and stack adjustments")
    lines.append("-- ===================================================================")
    lines.append("")
    lines.append("UPDATE `item_template` SET `BuyPrice` = 50000, `SellPrice` = 12500, `stackable` = 200 WHERE (`entry` = 17031);")
    lines.append("")

    return "\n".join(lines)


def run(output_path: Path, verbose: bool = True) -> Tuple[int, int]:
    """Load cities, generate SQL, write to file.

    Returns (city_count, 0).
    """
    cities = load_cities()

    if verbose:
        for c in cities:
            vendors = ', '.join(str(v) for v in c.vendor_ids)
            print(f"  {c.city:<20} scroll={c.scroll_id}  technique={c.technique_id}  inscription={c.inscription_level}  vendors=[{vendors}]")

    sql_content = generate_sql(cities)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(sql_content)

    return len(cities), 0
