-- [BASE,F-143] character-creator: characterfacialhairstyles
-- Imported by zep dbc import-module - DO NOT EDIT
-- To customize, create [F-143]_characterfacialhairstyles.sql with overrides

-- characterfacialhairstyles: 1 inserts, 9 updates, 0 deletes
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 0, 6, 11, 2, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 1, 5, 10, 3, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 2, 2, 9, 4, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 3, 3, 8, 5, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 4, 2, 7, 6, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 5, 5, 6, 7, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 6, 4, 5, 8, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 7, 3, 4, 9, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 8, 2, 3, 10, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 9, 5, 2, 11, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 10, 4, 11, 12, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 11, 3, 10, 13, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 12, 5, 9, 2, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 13, 6, 8, 3, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 14, 5, 7, 4, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 15, 4, 6, 5, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 16, 3, 5, 6, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 17, 4, 4, 7, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 18, 6, 3, 8, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 19, 5, 2, 9, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 20, 4, 11, 10, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 21, 2, 10, 11, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 22, 3, 9, 12, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 23, 5, 8, 13, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 0, 24, 2, 7, 13, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 0, 6, 11, 2, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 1, 5, 10, 3, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 2, 2, 9, 4, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 3, 3, 8, 5, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 4, 2, 7, 6, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 5, 5, 6, 7, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 6, 4, 5, 8, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 7, 3, 4, 9, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 8, 2, 3, 10, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 9, 5, 2, 11, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 10, 4, 11, 12, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 11, 3, 10, 13, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 12, 5, 9, 2, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 13, 6, 8, 3, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 14, 5, 7, 4, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 15, 4, 6, 5, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 16, 3, 5, 6, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 17, 4, 4, 7, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 18, 6, 3, 8, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 19, 5, 2, 9, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 20, 4, 11, 10, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 21, 2, 10, 11, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 22, 3, 9, 12, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 23, 5, 8, 13, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race_id`, `sex_id`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (9, 1, 24, 6, 6, 6, 0, 0);
UPDATE `characterfacialhairstyles` SET `variation_id` = 23, `geoset_1` = 13, `geoset_3` = 2 WHERE `race_id` = 12;
UPDATE `characterfacialhairstyles` SET `variation_id` = 5, `geoset_2` = 6 WHERE `race_id` = 14;
UPDATE `characterfacialhairstyles` SET `variation_id` = 27, `geoset_3` = 7 WHERE `race_id` = 15;
UPDATE `characterfacialhairstyles` SET `variation_id` = 5, `geoset_2` = 6 WHERE `race_id` = 16;
UPDATE `characterfacialhairstyles` SET `variation_id` = 15, `geoset_2` = 2, `geoset_3` = 9 WHERE `race_id` = 17;
UPDATE `characterfacialhairstyles` SET `variation_id` = 15, `geoset_2` = 2, `geoset_3` = 9, `geoset_4` = 0, `geoset_5` = 0 WHERE `race_id` = 18;
UPDATE `characterfacialhairstyles` SET `variation_id` = 4, `geoset_2` = 5 WHERE `race_id` = 19;
UPDATE `characterfacialhairstyles` SET `variation_id` = 6, `geoset_1` = 8, `geoset_2` = 2 WHERE `race_id` = 20;
UPDATE `characterfacialhairstyles` SET `variation_id` = 5, `geoset_1` = 7, `geoset_2` = 2 WHERE `race_id` = 21;