UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE (`ID` = 10831);
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE (`ID` = 10832);
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE (`ID` = 10833);
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE (`ID` = 10907);
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE (`ID` = 10906);
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE (`ID` = 10905);
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE (`ID` = 10902);
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE (`ID` = 10899);
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE (`ID` = 10897);