-- Rebuild Table
  DROP TABLE IF EXISTS `mod_auctionhousebot`;
  CREATE TABLE `mod_auctionhousebot` (
    `auctionhouse` int(11) NOT NULL DEFAULT '0' COMMENT 'mapID of the auctionhouse.',
    `name` char(25) DEFAULT NULL COMMENT 'Text name of the auctionhouse.',
    `minitems` int(11) DEFAULT '0' COMMENT 'This is the minimum number of items you want to keep in the auction house. a 0 here will make it the same as the maximum.',
    `maxitems` int(11) DEFAULT '0' COMMENT 'This is the number of items you want to keep in the auction house.',
    `percentgreytradegoods` int(11) DEFAULT '0' COMMENT 'Sets the percentage of the Grey Trade Goods auction items',
    `percentwhitetradegoods` int(11) DEFAULT '27' COMMENT 'Sets the percentage of the White Trade Goods auction items',
    `percentgreentradegoods` int(11) DEFAULT '12' COMMENT 'Sets the percentage of the Green Trade Goods auction items',
    `percentbluetradegoods` int(11) DEFAULT '10' COMMENT 'Sets the percentage of the Blue Trade Goods auction items',
    `percentpurpletradegoods` int(11) DEFAULT '1' COMMENT 'Sets the percentage of the Purple Trade Goods auction items',
    `percentorangetradegoods` int(11) DEFAULT '0' COMMENT 'Sets the percentage of the Orange Trade Goods auction items',
    `percentyellowtradegoods` int(11) DEFAULT '0' COMMENT 'Sets the percentage of the Yellow Trade Goods auction items',
    `percentgreyitems` int(11) DEFAULT '0' COMMENT 'Sets the percentage of the non trade Grey auction items',
    `percentwhiteitems` int(11) DEFAULT '10' COMMENT 'Sets the percentage of the non trade White auction items',
    `percentgreenitems` int(11) DEFAULT '30' COMMENT 'Sets the percentage of the non trade Green auction items',
    `percentblueitems` int(11) DEFAULT '8' COMMENT 'Sets the percentage of the non trade Blue auction items',
    `percentpurpleitems` int(11) DEFAULT '2' COMMENT 'Sets the percentage of the non trade Purple auction items',
    `percentorangeitems` int(11) DEFAULT '0' COMMENT 'Sets the percentage of the non trade Orange auction items',
    `percentyellowitems` int(11) DEFAULT '0' COMMENT 'Sets the percentage of the non trade Yellow auction items',
    `minpricegrey` int(11) DEFAULT '250' COMMENT 'Minimum price of Grey items (percentage).',
    `maxpricegrey` int(11) DEFAULT '500' COMMENT 'Maximum price of Grey items (percentage).',
    `minpricewhite` int(11) DEFAULT '750' COMMENT 'Minimum price of White items (percentage).',
    `maxpricewhite` int(11) DEFAULT '1000' COMMENT 'Maximum price of White items (percentage).',
    `minpricegreen` int(11) DEFAULT '1250' COMMENT 'Minimum price of Green items (percentage).',
    `maxpricegreen` int(11) DEFAULT '1500' COMMENT 'Maximum price of Green items (percentage).',
    `minpriceblue` int(11) DEFAULT '1750' COMMENT 'Minimum price of Blue items (percentage).',
    `maxpriceblue` int(11) DEFAULT '2000' COMMENT 'Maximum price of Blue items (percentage).',
    `minpricepurple` int(11) DEFAULT '3000' COMMENT 'Minimum price of Purple items (percentage).',
    `maxpricepurple` int(11) DEFAULT '4000' COMMENT 'Maximum price of Purple items (percentage).',
    `minpriceorange` int(11) DEFAULT '5000' COMMENT 'Minimum price of Orange items (percentage).',
    `maxpriceorange` int(11) DEFAULT '10000' COMMENT 'Maximum price of Orange items (percentage).',
    `minpriceyellow` int(11) DEFAULT '5000' COMMENT 'Minimum price of Yellow items (percentage).',
    `maxpriceyellow` int(11) DEFAULT '10000' COMMENT 'Maximum price of Yellow items (percentage).',
    `minbidpricegrey` int(11) DEFAULT '70' COMMENT 'Starting bid price of Grey items as a percentage of the randomly chosen buyout price. Default: 70',
    `maxbidpricegrey` int(11) DEFAULT '100' COMMENT 'Starting bid price of Grey items as a percentage of the randomly chosen buyout price. Default: 100',
    `minbidpricewhite` int(11) DEFAULT '70' COMMENT 'Starting bid price of White items as a percentage of the randomly chosen buyout price. Default: 70',
    `maxbidpricewhite` int(11) DEFAULT '100' COMMENT 'Starting bid price of White items as a percentage of the randomly chosen buyout price. Default: 100',
    `minbidpricegreen` int(11) DEFAULT '80' COMMENT 'Starting bid price of Green items as a percentage of the randomly chosen buyout price. Default: 80',
    `maxbidpricegreen` int(11) DEFAULT '100' COMMENT 'Starting bid price of Green items as a percentage of the randomly chosen buyout price. Default: 100',
    `minbidpriceblue` int(11) DEFAULT '75' COMMENT 'Starting bid price of Blue items as a percentage of the randomly chosen buyout price. Default: 75',
    `maxbidpriceblue` int(11) DEFAULT '100' COMMENT 'Starting bid price of Blue items as a percentage of the randomly chosen buyout price. Default: 100',
    `minbidpricepurple` int(11) DEFAULT '80' COMMENT 'Starting bid price of Purple items as a percentage of the randomly chosen buyout price. Default: 80',
    `maxbidpricepurple` int(11) DEFAULT '100' COMMENT 'Starting bid price of Purple items as a percentage of the randomly chosen buyout price. Default: 100',
    `minbidpriceorange` int(11) DEFAULT '80' COMMENT 'Starting bid price of Orange items as a percentage of the randomly chosen buyout price. Default: 80',
    `maxbidpriceorange` int(11) DEFAULT '100' COMMENT 'Starting bid price of Orange items as a percentage of the randomly chosen buyout price. Default: 100',
    `minbidpriceyellow` int(11) DEFAULT '80' COMMENT 'Starting bid price of Yellow items as a percentage of the randomly chosen buyout price. Default: 80',
    `maxbidpriceyellow` int(11) DEFAULT '100' COMMENT 'Starting bid price of Yellow items as a percentage of the randomly chosen buyout price. Default: 100',
    `maxstackgrey` int(11) DEFAULT '0' COMMENT 'Stack size limits for item qualities - a value of 0 will disable a maximum stack size for that quality, which will allow the bot to create items in stack as large as the item allows.',
    `maxstackwhite` int(11) DEFAULT '0' COMMENT 'Stack size limits for item qualities - a value of 0 will disable a maximum stack size for that quality, which will allow the bot to create items in stack as large as the item allows.',
    `maxstackgreen` int(11) DEFAULT '0' COMMENT 'Stack size limits for item qualities - a value of 0 will disable a maximum stack size for that quality, which will allow the bot to create items in stack as large as the item allows.',
    `maxstackblue` int(11) DEFAULT '0' COMMENT 'Stack size limits for item qualities - a value of 0 will disable a maximum stack size for that quality, which will allow the bot to create items in stack as large as the item allows.',
    `maxstackpurple` int(11) DEFAULT '0' COMMENT 'Stack size limits for item qualities - a value of 0 will disable a maximum stack size for that quality, which will allow the bot to create items in stack as large as the item allows.',
    `maxstackorange` int(11) DEFAULT '0' COMMENT 'Stack size limits for item qualities - a value of 0 will disable a maximum stack size for that quality, which will allow the bot to create items in stack as large as the item allows.',
    `maxstackyellow` int(11) DEFAULT '0' COMMENT 'Stack size limits for item qualities - a value of 0 will disable a maximum stack size for that quality, which will allow the bot to create items in stack as large as the item allows.',
    `buyerpricegrey` int(11) DEFAULT '5' COMMENT 'Multiplier to vendorprice when buying grey items from auctionhouse',
    `buyerpricewhite` int(11) DEFAULT '30' COMMENT 'Multiplier to vendorprice when buying white items from auctionhouse',
    `buyerpricegreen` int(11) DEFAULT '40' COMMENT 'Multiplier to vendorprice when buying green items from auctionhouse',
    `buyerpriceblue` int(11) DEFAULT '50' COMMENT 'Multiplier to vendorprice when buying blue items from auctionhouse',
    `buyerpricepurple` int(11) DEFAULT '60' COMMENT 'Multiplier to vendorprice when buying purple items from auctionhouse',
    `buyerpriceorange` int(11) DEFAULT '80' COMMENT 'Multiplier to vendorprice when buying orange items from auctionhouse',
    `buyerpriceyellow` int(11) DEFAULT '100' COMMENT 'Multiplier to vendorprice when buying yellow items from auctionhouse',
    `buyerbiddinginterval` int(11) DEFAULT '1' COMMENT 'Interval how frequently AHB bids on each AH. Time in minutes',
    `buyerbidsperinterval` int(11) DEFAULT '1' COMMENT 'number of bids to put in per bidding interval',
    PRIMARY KEY (`auctionhouse`)
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

  DROP TABLE IF EXISTS `mod_auctionhousebot_disabled_items`;
  CREATE TABLE `mod_auctionhousebot_disabled_items` (
    `item` mediumint(8) unsigned NOT NULL,
    PRIMARY KEY (`item`)
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- AHBot auctionhouse configuration

  -- Alliance AH
    INSERT INTO `mod_auctionhousebot` SET
    `auctionhouse` = 2,
    `name` = 'Alliance',
    `minitems` = 25000,
    `maxitems` = 25000,
    `percentwhitetradegoods` = 37,
    `percentgreenitems` = 15,
    `percentblueitems` = 10,
    `percentpurpleitems` = 5,
    `minpricegrey` = 4000,
    `maxpricegrey` = 6000,
    `minpricewhite` = 8000,
    `maxpricewhite` = 10000,
    `minpricegreen` = 12000,
    `maxpricegreen` = 14000,
    `minpriceblue` = 16000,
    `maxpriceblue` = 18000,
    `minpricepurple` = 20000,
    `maxpricepurple` = 22000,
    `minpriceorange` = 24000,
    `maxpriceorange` = 26000,
    `minpriceyellow` = 28000,
    `maxpriceyellow` = 30000,
    `maxstackgreen` = 3,
    `maxstackblue` = 2,
    `maxstackpurple` = 1,
    `maxstackorange` = 1,
    `maxstackyellow` = 1,
    `buyerpricegrey` = 1,
    `buyerpricewhite` = 5,
    `buyerpricegreen` = 20,
    `buyerpriceblue` = 30,
    `buyerpricepurple` = 40,
    `buyerpriceorange` = 50,
    `buyerpriceyellow` = 50;

  -- Horde AH
    INSERT INTO `mod_auctionhousebot` SET
    `auctionhouse` = 6,
    `name` = 'Horde',
    `minitems` = 25000,
    `maxitems` = 25000,
    `percentwhitetradegoods` = 37,
    `percentgreenitems` = 15,
    `percentblueitems` = 10,
    `percentpurpleitems` = 5,
    `minpricegrey` = 4000,
    `maxpricegrey` = 6000,
    `minpricewhite` = 8000,
    `maxpricewhite` = 10000,
    `minpricegreen` = 12000,
    `maxpricegreen` = 14000,
    `minpriceblue` = 16000,
    `maxpriceblue` = 18000,
    `minpricepurple` = 20000,
    `maxpricepurple` = 22000,
    `minpriceorange` = 24000,
    `maxpriceorange` = 26000,
    `minpriceyellow` = 28000,
    `maxpriceyellow` = 30000,
    `maxstackgreen` = 3,
    `maxstackblue` = 2,
    `maxstackpurple` = 1,
    `maxstackorange` = 1,
    `maxstackyellow` = 1,
    `buyerpricegrey` = 1,
    `buyerpricewhite` = 5,
    `buyerpricegreen` = 20,
    `buyerpriceblue` = 30,
    `buyerpricepurple` = 40,
    `buyerpriceorange` = 50,
    `buyerpriceyellow` = 50;

  -- Neutral AH
  INSERT INTO `mod_auctionhousebot` SET
  `auctionhouse` = 7,
  `name` = 'Neutral',
  `minitems` = 30000,
  `maxitems` = 30000,
  `percentwhitetradegoods` = 37,
  `percentgreenitems` = 15,
  `percentblueitems` = 10,
  `percentpurpleitems` = 5,
  `minpricegrey` = 4000,
  `maxpricegrey` = 6000,
  `minpricewhite` = 8000,
  `maxpricewhite` = 10000,
  `minpricegreen` = 12000,
  `maxpricegreen` = 14000,
  `minpriceblue` = 16000,
  `maxpriceblue` = 18000,
  `minpricepurple` = 20000,
  `maxpricepurple` = 22000,
  `minpriceorange` = 24000,
  `maxpriceorange` = 26000,
  `minpriceyellow` = 28000,
  `maxpriceyellow` = 30000,
  `maxstackgreen` = 3,
  `maxstackblue` = 2,
  `maxstackpurple` = 1,
  `maxstackorange` = 1,
  `maxstackyellow` = 1,
  `buyerpricegrey` = 1,
  `buyerpricewhite` = 5,
  `buyerpricegreen` = 20,
  `buyerpriceblue` = 30,
  `buyerpricepurple` = 40,
  `buyerpriceorange` = 50,
  `buyerpriceyellow` = 50;