-- worgoblin: achievement
-- Generated by dbc-mgr import-module

-- achievement: 2 inserts, 41 updates, 0 deletes
INSERT INTO `achievement` (`id`, `faction`, `map`, `previous`, `name_enus`, `name_flags`, `desc_enus`, `desc_flags`, `category`, `points`, `order_in_category`, `flags`, `spell_icon`, `reward_enus`, `reward_flags`, `min_criteria_demand`, `linked_achievement`) VALUES (1429, -1, -1, 0, 'Realm First! Level 80 Goblin', 16712190, 'First goblin on the realm to achieve level 80.', 16712190, 81, 0, 161, 256, 463874, '', 16712174, 0, 0);
INSERT INTO `achievement` (`id`, `faction`, `map`, `previous`, `name_enus`, `name_flags`, `desc_enus`, `desc_flags`, `category`, `points`, `order_in_category`, `flags`, `spell_icon`, `reward_enus`, `reward_flags`, `min_criteria_demand`, `linked_achievement`) VALUES (1430, -1, -1, 0, 'Realm First! Level 80 Worgen', 16712190, 'First worgen on the realm to achieve level 80.', 16712190, 81, 0, 162, 256, 463876, '', 16712174, 0, 0);
UPDATE `achievement` SET `desc_enus` = 'Get an honorable, killing blow on six different races.' WHERE `id` = 246;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Hand of A\'dal"".' WHERE `id` = 431;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Champion of the Naaru"".' WHERE `id` = 432;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Grand Marshal"".' WHERE `id` = 433;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Field Marshal"".' WHERE `id` = 434;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Commander"".' WHERE `id` = 435;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Lieutenant Commander"".' WHERE `id` = 436;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Knight-Champion"".' WHERE `id` = 437;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Knight-Captain"".' WHERE `id` = 438;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Knight"".' WHERE `id` = 439;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Sergeant Major"".' WHERE `id` = 440;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Master Sergeant"".' WHERE `id` = 441;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Private"".' WHERE `id` = 442;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""High Warlord"".' WHERE `id` = 443;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Lieutenant General"".' WHERE `id` = 444;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Warlord"".' WHERE `id` = 445;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""General"".' WHERE `id` = 446;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Champion"".' WHERE `id` = 447;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Centurion"".' WHERE `id` = 448;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Blood Guard"".' WHERE `id` = 449;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Senior Sergeant"".' WHERE `id` = 450;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Stone Guard"".' WHERE `id` = 451;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""First Sergeant"".' WHERE `id` = 452;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Sergeant"".' WHERE `id` = 453;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Scout"".' WHERE `id` = 454;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Grunt"".' WHERE `id` = 468;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Legionnaire"".' WHERE `id` = 469;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Corporal"".' WHERE `id` = 470;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Sergeant"".' WHERE `id` = 471;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Knight-Lieutenant"".' WHERE `id` = 472;
UPDATE `achievement` SET `desc_enus` = 'Earned the title, ""Marshal"".' WHERE `id` = 473;
UPDATE `achievement` SET `desc_enus` = 'Get an honorable, killing blow on six different races.' WHERE `id` = 1005;
UPDATE `achievement` SET `desc_enus` = 'Complete the quest, ""A Thief\'s Reward"", by stealing the flames from your enemy\'s capital cities.' WHERE `id` = 1145;
UPDATE `achievement` SET `name_enus` = 'My Sack is ""Gigantique""', `desc_enus` = 'Equip Haris Pilton\'s ""Gigantique"" Bag.' WHERE `id` = 1165;
UPDATE `achievement` SET `desc_enus` = 'Defend the Brewfest camp from the Dark Iron attack and complete the quest, ""This One Time, When I Was Drunk...""' WHERE `id` = 1186;
UPDATE `achievement` SET `desc_enus` = 'Use Mistletoe on the Horde ""Brothers"" during the Feast of Winter Veil.' WHERE `id` = 1685;
UPDATE `achievement` SET `desc_enus` = 'Use Mistletoe on the Alliance ""Brothers"" during the Feast of Winter Veil.' WHERE `id` = 1686;
UPDATE `achievement` SET `desc_enus` = 'Eat the eight ""Bag of Candies"" heart candies listed below.' WHERE `id` = 1701;
UPDATE `achievement` SET `desc_enus` = 'Eat each one of the ""emotion"" foods listed below.' WHERE `id` = 1780;
UPDATE `achievement` SET `desc_enus` = 'Read the volumes of ""The Schools of Arcane Magic"" found in Dalaran listed below.' WHERE `id` = 1956;
UPDATE `achievement` SET `name_enus` = '""FOOD FIGHT!""' WHERE `id` = 3579;