-- worgoblin: achievement_criteria
-- Generated by dbc-mgr import-module

-- achievement_criteria: 8 inserts, 7 updates, 0 deletes
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13471, 246, 53, 9, 1, 0, 0, 0, 0, 'Goblin', 16712190, 0, 0, 0, 0, 6);
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13472, 1005, 53, 12, 1, 0, 0, 0, 0, 'Worgen', 16712190, 0, 0, 0, 0, 6);
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13473, 2422, 110, 61815, 1, 0, 0, 0, 0, 'Goblin', 16712190, 0, 0, 0, 0, 11);
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13474, 2422, 110, 61815, 1, 0, 0, 0, 0, 'Worgen', 16712190, 0, 0, 0, 0, 12);
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13475, 291, 110, 44212, 1, 0, 0, 0, 0, 'Goblin', 16712190, 0, 0, 0, 0, 11);
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13476, 291, 110, 44212, 1, 0, 0, 0, 0, 'Worgen', 16712190, 0, 0, 0, 0, 12);
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13477, 1429, 5, 80, 0, 0, 0, 0, 0, 'Level to 80', 16712190, 2, 0, 0, 0, 1);
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES (13478, 1430, 5, 80, 0, 0, 0, 0, 0, 'Level to 80', 16712190, 2, 0, 0, 0, 1);
UPDATE `achievement_criteria` SET `desc_enus` = '""Let the Fires Come!""' WHERE `id` = 2281;
UPDATE `achievement_criteria` SET `desc_enus` = '""Let the Fires Come!""' WHERE `id` = 2282;
UPDATE `achievement_criteria` SET `desc_enus` = '""Gigantique"" Bag' WHERE `id` = 3390;
UPDATE `achievement_criteria` SET `desc_enus` = 'Winterfin ""Depth Charge""' WHERE `id` = 6960;
UPDATE `achievement_criteria` SET `desc_enus` = 'Fizzy Faire Drink ""Classic""' WHERE `id` = 9016;
UPDATE `achievement_criteria` SET `desc_enus` = '""FOOD FIGHT!""' WHERE `id` = 10940;
UPDATE `achievement_criteria` SET `desc_enus` = '""FOOD FIGHT!""' WHERE `id` = 11266;