-- worgoblin: charbaseinfo
-- Generated by dbc-mgr import-module

-- charbaseinfo: 16 inserts, 0 updates, 0 deletes
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (63, 9, 1);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (64, 9, 3);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (65, 9, 4);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (66, 9, 6);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (67, 9, 7);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (68, 9, 9);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (69, 12, 1);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (70, 12, 3);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (71, 12, 4);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (72, 12, 5);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (73, 12, 6);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (74, 12, 8);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (75, 12, 9);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (76, 12, 11);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (77, 9, 8);
INSERT INTO `charbaseinfo` (`auto_id`, `race`, `class`) VALUES (78, 9, 5);