-- worgoblin: skillline
-- Generated by dbc-mgr import-module

-- skillline: 2 inserts, 0 updates, 0 deletes
INSERT INTO `skillline` (`id`, `category`, `cost`, `name_enus`, `name_flags`, `desc_enus`, `desc_flags`, `icon_id`, `verb_enus`, `verb_flags`, `can_link`) VALUES (789, 9, 0, 'Racial - Worgen', 16712190, '', 16712172, 132203, '', 16712172, 0);
INSERT INTO `skillline` (`id`, `category`, `cost`, `name_enus`, `name_flags`, `desc_enus`, `desc_flags`, `icon_id`, `verb_enus`, `verb_flags`, `can_link`) VALUES (790, 9, 0, 'Racial - Goblin', 16712190, '', 16712172, 133032, '', 16712172, 0);