DELETE FROM `spell` WHERE `id` = 91132;

INSERT INTO `spell` SET
    `id` = 91132,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 947,
    `spell_icon_id` = 2625,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Thrallmar',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Thrallmar. Increases Thrallmar reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Thrallmar reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91133;

INSERT INTO `spell` SET
    `id` = 91133,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 946,
    `spell_icon_id` = 2413,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Honor Hold',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Honor Hold. Increases Honor Hold reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Honor Hold reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91134;

INSERT INTO `spell` SET
    `id` = 91134,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 942,
    `spell_icon_id` = 2554,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Cenarion Expedition',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Cenarion Expedition. Increases Cenarion Expedition reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Cenarion Expedition reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91135;

INSERT INTO `spell` SET
    `id` = 91135,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 1011,
    `spell_icon_id` = 2467,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Lower City',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Lower City. Increases Lower City reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Lower City reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91136;

INSERT INTO `spell` SET
    `id` = 91136,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 989,
    `spell_icon_id` = 4631,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Keepers of Time',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Keepers of Time. Increases Keepers of Time reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Keepers of Time reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91137;

INSERT INTO `spell` SET
    `id` = 91137,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 935,
    `spell_icon_id` = 4444,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Sha''tar',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Sha''tar. Increases Sha''tar reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Sha''tar reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91168;

INSERT INTO `spell` SET
    `id` = 91168,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 934,
    `spell_icon_id` = 1575,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Scryers',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Scryers. Increases Scryers reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Scryers reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91169;

INSERT INTO `spell` SET
    `id` = 91169,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 1031,
    `spell_icon_id` = 2422,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Sha''tari Skyguard',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Sha''tari Skyguard. Increases Sha''tari Skyguard reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Sha''tari Skyguard reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91170;

INSERT INTO `spell` SET
    `id` = 91170,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 970,
    `spell_icon_id` = 2033,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Sporeggar',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Sporeggar. Increases Sporeggar reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Sporeggar reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91171;

INSERT INTO `spell` SET
    `id` = 91171,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 933,
    `spell_icon_id` = 2649,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Consortium',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Consortium. Increases Consortium reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Consortium reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91172;

INSERT INTO `spell` SET
    `id` = 91172,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 1077,
    `spell_icon_id` = 3664,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Shattered Sun Offensive',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Shattered Sun Offensive. Increases Shattered Sun Offensive reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Shattered Sun Offensive reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91173;

INSERT INTO `spell` SET
    `id` = 91173,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 1015,
    `spell_icon_id` = 1928,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Netherwing',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Netherwing. Increases Netherwing reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Netherwing reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91174;

INSERT INTO `spell` SET
    `id` = 91174,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 967,
    `spell_icon_id` = 3682,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of The Violet Eye',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of The Violet Eye. Increases Violet Eye reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Violet Eye reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91175;

INSERT INTO `spell` SET
    `id` = 91175,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 922,
    `spell_icon_id` = 1853,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Tranquillien',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Tranquillien. Increases Tranquillien reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Tranquillien reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91176;

INSERT INTO `spell` SET
    `id` = 91176,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 1012,
    `spell_icon_id` = 4880,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Ashtongue Deathsworn',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Ashtongue Deathsworn. Increases Ashtongue Deathsworn reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Ashtongue Deathsworn reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91177;

INSERT INTO `spell` SET
    `id` = 91177,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 990,
    `spell_icon_id` = 3639,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of The Scale of the Sands',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of The Scale of the Sands. Increases Scale of the Sands reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Scale of the Sands reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91178;

INSERT INTO `spell` SET
    `id` = 91178,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 978,
    `spell_icon_id` = 3696,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Kurenai',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Kurenai. Increases Kurenai reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Kurenai reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91179;

INSERT INTO `spell` SET
    `id` = 91179,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 941,
    `spell_icon_id` = 4784,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Mag''har',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Mag''har. Increases Mag''har reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Mag''har reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91180;

INSERT INTO `spell` SET
    `id` = 91180,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 1038,
    `spell_icon_id` = 3954,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Ogri''la',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Ogri''la. Increases Ogri''la reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Ogri''la reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91181;

INSERT INTO `spell` SET
    `id` = 91181,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 932,
    `spell_icon_id` = 3796,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Aldor',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Aldor. Increases Aldor reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Aldor reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91204;

INSERT INTO `spell` SET
    `id` = 91204,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 72,
    `spell_icon_id` = 3807,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Stormwind',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Stormwind. Increases Stormwind reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Stormwind reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91205;

INSERT INTO `spell` SET
    `id` = 91205,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 47,
    `spell_icon_id` = 3797,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Ironforge',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Ironforge. Increases Ironforge reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Ironforge reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91206;

INSERT INTO `spell` SET
    `id` = 91206,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 54,
    `spell_icon_id` = 4232,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Gnomeregan',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Gnomeregan. Increases Gnomeregan reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Gnomeregan reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91207;

INSERT INTO `spell` SET
    `id` = 91207,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 69,
    `spell_icon_id` = 3801,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Darnassus',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Darnassus. Increases Darnassus reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Darnassus reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91208;

INSERT INTO `spell` SET
    `id` = 91208,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 930,
    `spell_icon_id` = 3796,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Exodar',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Exodar. Increases Exodar reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Exodar reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91209;

INSERT INTO `spell` SET
    `id` = 91209,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 76,
    `spell_icon_id` = 3806,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Orgrimmar',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Orgrimmar. Increases Orgrimmar reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Orgrimmar reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91210;

INSERT INTO `spell` SET
    `id` = 91210,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 530,
    `spell_icon_id` = 4239,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Darkspear',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Darkspear Trolls. Increases Darkspear Trolls reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Darkspear Trolls reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91211;

INSERT INTO `spell` SET
    `id` = 91211,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 68,
    `spell_icon_id` = 4254,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of the Undercity',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of the Undercity. Increases Undercity reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Undercity reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91212;

INSERT INTO `spell` SET
    `id` = 91212,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 81,
    `spell_icon_id` = 3803,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Thunder Bluff',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Thunder Bluff. Increases Thunder Bluff reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Thunder Bluff reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;

DELETE FROM `spell` WHERE `id` = 91213;

INSERT INTO `spell` SET
    `id` = 91213,
    `attributes` = 2164261120,
    `attributes_ex_3` = 1048576,
    `attributes_ex_4` = 128,
    `attributes_ex_6` = 4096,
    `cast_time_index` = 1,
    `proc_chance` = 101,
    `duration_index` = 21,
    `range_index` = 1,
    `equipped_item_class` = -1,
    `effect_1` = 6,
    `effect_die_sides_1` = 1,
    `effect_base_points_1` = 24,
    `effect_implicit_target_a_1` = 1,
    `effect_apply_aura_name_1` = 156,
    `effect_misc_value_a_1` = 911,
    `spell_icon_id` = 3795,
    `active_icon_id` = 2625,
    `spell_name_enus` = 'Champion of Silvermoon',
    `spell_name_flags` = 16712190,
    `spell_subtext_enus` = '',
    `spell_subtext_flags` = 16712190,
    `spell_desc_enus` = 'You champion the cause of Silvermoon City. Increases Silvermoon City reputation gained from all sources by $s1%.',
    `spell_desc_flags` = 16712190,
    `spell_tooltip_enus` = 'Increases Silvermoon City reputation gained from all sources by $s1%.',
    `spell_tooltip_flags` = 16712190,
    `effect_damage_multiplier_1` = 1.0;


-- ==============================================================================
-- CLASSIC NEUTRAL FACTION TABARDS (Phase 5B)
-- ==============================================================================

-- Champion of the Argent Dawn (faction 529) - Spell 91300
-- Uses aura 156 (all sources), icon 2637 (Argent Dawn tabard icon)
DELETE FROM `spell` WHERE `id` = 91300;
INSERT INTO `spell` SET
  `id` = 91300,
  `attributes` = 2164261120,
  `attributes_ex_3` = 1048576,
  `attributes_ex_4` = 128,
  `attributes_ex_6` = 4096,
  `cast_time_index` = 1,
  `proc_chance` = 101,
  `duration_index` = 21,
  `range_index` = 1,
  `equipped_item_class` = -1,
  `effect_1` = 6,
  `effect_die_sides_1` = 1,
  `effect_base_points_1` = 24,
  `effect_implicit_target_a_1` = 1,
  `effect_apply_aura_name_1` = 156,
  `effect_misc_value_a_1` = 529,
  `spell_icon_id` = 3744,
  `active_icon_id` = 2625,
  `spell_name_enus` = 'Champion of the Argent Dawn',
  `spell_name_flags` = 16712190,
  `spell_subtext_enus` = '',
  `spell_subtext_flags` = 16712190,
  `spell_desc_enus` = 'You champion the cause of the Argent Dawn. Increases Argent Dawn reputation gained from all sources by $s1%.',
  `spell_desc_flags` = 16712190,
  `spell_tooltip_enus` = 'Increases Argent Dawn reputation gained from all sources by $s1%.',
  `spell_tooltip_flags` = 16712190,
  `effect_damage_multiplier_1` = '1.0000000000000000';
